/**
 * generate-stories.mjs
 *
 * Generates one Storybook CSF file per `@oneui/ui-native` component from its
 * `*.showcase.native.tsx` peer. Each exported, component-prefixed showcase
 * function (e.g. `ButtonAttentionLevels`) becomes a story; helper exports that
 * are not prefixed with the component name (e.g. `HeartIcon`) are skipped.
 *
 * Run: pnpm generate:stories
 *
 * Output: stories/<Component>.stories.tsx — git-tracked so the app builds
 * without a generate step, but regenerate whenever a showcase changes.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = resolve(__dirname, '..');
const COMPONENTS_DIR = resolve(APP_ROOT, '../../packages/ui-native/src/components');
const OUT_DIR = resolve(APP_ROOT, 'stories');

// Sidebar grouping: Components/<Category>/<Component>. Anything not listed
// falls back to "Other".
const CATEGORY = {
  Button: 'Actions', LinkButton: 'Actions', IconButton: 'Actions', IconContained: 'Actions',
  Input: 'Forms', InputField: 'Forms', InputDynamicText: 'Forms', InputFeedback: 'Forms',
  Checkbox: 'Forms', CheckboxField: 'Forms', Radio: 'Forms', RadioField: 'Forms',
  Chip: 'Forms', ChipGroup: 'Forms',
  Avatar: 'Media', Image: 'Media', Logo: 'Media', Icon: 'Media',
  Badge: 'Status', CounterBadge: 'Status', IndicatorBadge: 'Status',
  Progress: 'Status', CircularProgressIndicator: 'Status', Spinner: 'Status',
  BottomNavigation: 'Navigation', BottomNavigationItem: 'Navigation', PaginationDots: 'Navigation',
  Container: 'Layout', Divider: 'Layout', Separator: 'Layout', Text: 'Layout',
};

/** "ButtonAttentionLevels" + prefix "Button" -> "Attention Levels". */
function humanize(exportName, prefix) {
  let s = exportName.startsWith(prefix) ? exportName.slice(prefix.length) : exportName;
  if (!s) s = exportName;
  return s.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2').trim();
}

function extractStoryExports(source, component) {
  const re = /^export\s+(?:function|const)\s+([A-Za-z0-9_]+)/gm;
  const names = [];
  let m;
  while ((m = re.exec(source)) !== null) {
    const name = m[1];
    // Story candidates are prefixed with the component name; helpers are not.
    if (name.startsWith(component)) names.push(name);
  }
  return names;
}

function build() {
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const components = readdirSync(COMPONENTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  let total = 0;
  let fileCount = 0;
  for (const component of components) {
    const showcasePath = resolve(COMPONENTS_DIR, component, `${component}.showcase.native.tsx`);
    if (!existsSync(showcasePath)) continue;

    const source = readFileSync(showcasePath, 'utf8');
    const exports = extractStoryExports(source, component);
    if (exports.length === 0) continue;

    const category = CATEGORY[component] ?? 'Other';
    const title = `Components/${category}/${component}`;

    const stories = exports
      .map((name) => {
        const storyConst = name === component ? `${name}Story` : name;
        const display = humanize(name, component);
        return `export const ${storyConst}: Story = {\n  name: ${JSON.stringify(display)},\n  render: () => <Showcase.${name} />,\n};`;
      })
      .join('\n\n');

    const file = `/**
 * ${component}.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/${component}/${component}.showcase.native.tsx
 * Do not edit by hand; run \`pnpm generate:stories\` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/${component}';

const meta = {
  title: ${JSON.stringify(title)},
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

${stories}
`;

    writeFileSync(resolve(OUT_DIR, `${component}.stories.tsx`), file);
    total += exports.length;
    fileCount += 1;
  }

  console.log(`Generated ${fileCount} story files, ${total} stories -> ${OUT_DIR}`);
}

build();
