// Two flavors of page emission:
//   - emitPageFromTemplate: pure, takes a TemplateNode. Used by the CLI.
//   - emitPageFromShape: convenience for the live app — calls
//     serializeSelection then forwards to emitPageFromTemplate.

import type { Editor, TLShape, TLShapeId } from 'tldraw'
import type { ComponentDef, TemplateNode } from '@/lib/componentDef'
import { serializeSelection } from '@/lib/templateSerializer'
import { emitTree, type EmitContext, type LiftedProp } from './emitTree'
import {
  countNodesOfType,
  EXTRACT_THRESHOLD,
  FIELD_SUBCOMPONENT_SOURCE,
  FIELD_SUBCOMPONENT_SOURCE_SHADCN,
} from './subComponents'
import { findFormSubmitButtonPaths, indent, mergeRootClassName, pascal } from './utils'

export interface EmitPageResult {
  componentName: string
  filename: string
  code: string
  uses: ComponentDef[]
}

export interface EmitPageOptions {
  mode?: 'default' | 'shadcn'
  /** Override the derived component name (used to dedupe collisions across
   *  multiple pages/defs at the project level). */
  componentName?: string
}

export function emitPageFromTemplate(
  template: TemplateNode,
  pageName: string,
  getDef: (id: string) => ComponentDef | undefined,
  opts: EmitPageOptions = {},
): EmitPageResult {
  const mode: 'default' | 'shadcn' = opts.mode ?? 'default'
  const componentName = opts.componentName ?? (pascal(pageName) || 'Page')

  const uses: ComponentDef[] = []
  const seen = new Set<string>()
  const externalImports = new Map<string, Set<string>>()
  let hasInteractive = false
  let hasIds = false
  const lifted: LiftedProp[] = []
  const liftedByName = new Map<string, LiftedProp>()
  const ctx: EmitContext = {
    mode,
    noteImport: (name, mod) => {
      let set = externalImports.get(mod)
      if (!set) {
        set = new Set()
        externalImports.set(mod, set)
      }
      set.add(name)
    },
    getDef,
    noteUsedDef: d => {
      if (seen.has(d.id)) return
      seen.add(d.id)
      uses.push(d)
    },
    noteInteractive: () => {
      hasInteractive = true
    },
    noteNeedsId: () => {
      hasIds = true
    },
    noteLiftedProp: p => {
      if (liftedByName.has(p.name)) return
      liftedByName.set(p.name, p)
      lifted.push(p)
    },
    noteUsedSubComponent: name => usedSubComponents.add(name),
  }
  const usedSubComponents = new Set<string>()

  // Field extraction when 3+ inputs in the tree.
  if (countNodesOfType(template, 'ui-input') >= EXTRACT_THRESHOLD) {
    ctx.extractFields = true
    usedSubComponents.add('Field')
    if (mode === 'shadcn') {
      ctx.noteImport?.('Label', '@/components/ui/label')
      ctx.noteImport?.('Input', '@/components/ui/input')
    }
  }
  ctx.submitButtonPaths = findFormSubmitButtonPaths(template)

  const jsx = mergeRootClassName(emitTree(template, ctx), 'className')

  const header: string[] = []
  if (hasInteractive || hasIds) {
    header.push(`'use client'`)
    header.push(``)
  }
  header.push(
    `// Generated by tldraw-ui-builder. Edits will be overwritten on next sync.`,
  )
  header.push(``)
  if (hasIds) header.push(`import { useId } from 'react'`)
  const needsReactType = lifted.some(l => /\bReact\./.test(l.type))
  if (needsReactType) header.push(`import type * as React from 'react'`)
  header.push(
    mode === 'shadcn'
      ? `import { cn } from '@/lib/utils'`
      : `import { cn } from './_lib'`,
  )
  for (const [mod, names] of externalImports) {
    const sorted = [...names].sort()
    header.push(`import { ${sorted.join(', ')} } from '${mod}'`)
  }
  for (const used of uses) {
    const n = pascal(used.name)
    header.push(`import { ${n} } from './${n}'`)
  }
  header.push(``)

  // Props interface with className + any lifted handlers/values.
  header.push(`export interface ${componentName}Props {`)
  for (const l of lifted) {
    const optional = l.optional === false ? '' : '?'
    header.push(`  ${l.name}${optional}: ${l.type}`)
  }
  header.push(`  className?: string`)
  header.push(`}`)
  header.push(``)

  const destructure = ['className', ...lifted.map(l => l.name)].join(', ')
  const body = [
    `export function ${componentName}(props: ${componentName}Props) {`,
    `  const { ${destructure} } = props`,
    hasIds ? `  const _id = useId()` : '',
    `  return (`,
    indent(jsx, 2),
    `  )`,
    `}`,
  ]
    .filter(line => line !== '')
    .join('\n')

  const tail: string[] = []
  if (usedSubComponents.has('Field')) {
    tail.push('')
    tail.push(
      mode === 'shadcn'
        ? FIELD_SUBCOMPONENT_SOURCE_SHADCN
        : FIELD_SUBCOMPONENT_SOURCE,
    )
  }

  return {
    componentName,
    filename: `${componentName}.tsx`,
    code: [...header, body, ...tail].join('\n') + '\n',
    uses,
  }
}

export function emitPageFromShape(
  editor: Editor,
  pageShape: TLShape,
  getDef: (id: string) => ComponentDef | undefined,
): EmitPageResult {
  const { template } = serializeSelection(editor, pageShape.id as TLShapeId)
  const name = String((pageShape.props as any).name ?? 'Page')
  return emitPageFromTemplate(template, name, getDef)
}
