// Pure project-level emitter: turns a ProjectSnapshot into the full set of
// files that should land in ./ui/. No Editor reference — the CLI uses this
// directly.

import type { ComponentDef } from '@/lib/componentDef'
import type { ProjectSnapshot } from '@/lib/projectExport'
import { emitComponent } from './emitComponent'
import { emitPageFromTemplate } from './emitPage'
import { emitTheme } from './emitTheme'
import { CN_HELPER_SOURCE, pascal } from './utils'

export interface ProjectFile {
  filename: string
  code: string
}

export interface EmitProjectResult {
  files: ProjectFile[]
}

export interface EmitProjectOptions {
  /** 'default' = raw HTML + our Tailwind tokens. 'shadcn' = compose with
   *  shadcn/ui primitives (Button, Input, Label, Checkbox). */
  mode?: 'default' | 'shadcn'
}

export function emitProject(
  snapshot: ProjectSnapshot,
  opts: EmitProjectOptions = {},
): EmitProjectResult {
  const mode: 'default' | 'shadcn' = opts.mode ?? 'default'
  const files: ProjectFile[] = []
  const getDef = (id: string) => snapshot.defs.find(d => d.id === id)

  // Theme deliverable (theme.css, tailwind.preset.ts, README.md)
  for (const t of emitTheme()) {
    files.push({ filename: t.filename, code: t.code })
  }

  // Shared utility file imported by every component (in default mode).
  // shadcn mode expects cn to come from `@/lib/utils` which already exists
  // in a shadcn project — no _lib.tsx needed.
  if (mode === 'default') {
    files.push({
      filename: '_lib.tsx',
      code: `// Generated by tldraw-ui-builder. Shared helpers used by every component.\n\n${CN_HELPER_SOURCE}\n\nexport { cn }\n`,
    })
  }

  // Track component names that have been taken so we can dedupe collisions
  // (e.g. two pages both named "Settings" → Settings, Settings2). Defs are
  // emitted first and own their names; later pages defer to them.
  const taken = new Set<string>()
  function uniqueName(desired: string): string {
    if (!taken.has(desired)) {
      taken.add(desired)
      return desired
    }
    let n = 2
    while (taken.has(`${desired}${n}`)) n++
    const final = `${desired}${n}`
    taken.add(final)
    console.warn(
      `[codegen] component name collision on "${desired}" — renaming to "${final}". Rename the page/component on the canvas to remove this notice.`,
    )
    return final
  }

  // ComponentDef files
  const exports: string[] = []
  for (const def of snapshot.defs) {
    const result = emitComponent(def, getDef, { mode })
    // Defs claim their pascal'd name first — won't be deduped against each
    // other since defs already have unique ids, but we record so later pages
    // sidestep them.
    taken.add(result.componentName)
    files.push({ filename: result.filename, code: result.code })
    exports.push(`export { ${result.componentName} } from './${result.componentName}'`)
  }

  // Pages
  for (const page of snapshot.pages) {
    const desired = pascal(page.name) || 'Page'
    const finalName = uniqueName(desired)
    const result = emitPageFromTemplate(page.template, page.name, getDef, {
      mode,
      componentName: finalName,
    })
    files.push({ filename: result.filename, code: result.code })
    exports.push(`export { ${result.componentName} } from './${result.componentName}'`)
  }

  // index.ts re-exports
  if (exports.length > 0) {
    files.push({
      filename: 'index.ts',
      code: `// Generated by tldraw-ui-builder. Re-exports the components in this folder.\n\n${exports.join('\n')}\n`,
    })
  }

  return { files }
}

/** Utility: gather every def directly or transitively referenced by `roots`. */
export function collectTransitiveDeps(
  roots: ComponentDef[],
  allDefs: ComponentDef[],
): ComponentDef[] {
  const byId = new Map<string, ComponentDef>(allDefs.map(d => [d.id, d]))
  const seen = new Set<string>()
  const out: ComponentDef[] = []
  function visit(def: ComponentDef) {
    if (seen.has(def.id)) return
    seen.add(def.id)
    out.push(def)
    // Walk templates to find ui-component-instance references.
    const stack = [def.template]
    if (def.variantSnapshots) {
      for (const t of Object.values(def.variantSnapshots)) stack.push(t)
    }
    while (stack.length > 0) {
      const node = stack.pop()!
      if (node.type === 'ui-component-instance') {
        const refId = String((node.props as any).defId ?? '')
        const ref = byId.get(refId)
        if (ref) visit(ref)
      }
      if (node.children) for (const c of node.children) stack.push(c)
    }
  }
  for (const r of roots) visit(r)
  return out
}
