// Emits the theme deliverable from the LIVE token state. theme.css + a
// Tailwind preset, both reflecting whatever the user has set in the Theme
// panel — not hardcoded defaults.

import { getTheme } from '@/lib/theme/themeStore'
import type { ThemeTokens } from '@/lib/theme/tokens'

const SETUP_README = `# tldraw-ui-builder — Theme setup

Two files: \`theme.css\` (CSS variables) and \`tailwind.preset.ts\` (Tailwind config extension).

## 1. Import the CSS

In your root stylesheet (e.g. Next.js \`app/globals.css\`, Vite \`src/index.css\`):

\`\`\`css
@import './theme.css';
@tailwind base;
@tailwind components;
@tailwind utilities;
\`\`\`

## 2. Add the Tailwind preset

In your \`tailwind.config.ts\`:

\`\`\`ts
import type { Config } from 'tailwindcss'
import uiPreset from './tailwind.preset'

const config: Config = {
  presets: [uiPreset],
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
}
export default config
\`\`\`

Your generated components can now use \`bg-brand\`, \`text-fg\`, \`rounded-token\`, \`bg-success\`, etc.
`

function makeThemeCss(t: ThemeTokens): string {
  return `/* Generated by tldraw-ui-builder.
 * Drop into your global stylesheet (e.g. app/globals.css). */

:root {
  --ui-bg: ${t.bg};
  --ui-surface: ${t.surface};
  --ui-fg: ${t.fg};
  --ui-muted: ${t.muted};
  --ui-border: ${t.border};
  --ui-brand: ${t.brand};
  --ui-brand-fg: ${t.brandFg};
  --ui-success: ${t.success};
  --ui-success-fg: ${t.successFg};
  --ui-warning: ${t.warning};
  --ui-warning-fg: ${t.warningFg};
  --ui-danger: ${t.danger};
  --ui-danger-fg: ${t.dangerFg};
  --ui-info: ${t.info};
  --ui-info-fg: ${t.infoFg};
  --ui-radius: ${t.radius}px;
  --ui-radius-sm: ${t.radiusSm}px;
  --ui-radius-lg: ${t.radiusLg}px;
  --ui-font-sans: ${t.fontSans};
}
`
}

const TAILWIND_PRESET = `// Generated by tldraw-ui-builder.
// Add as a preset to your tailwind.config:
//   import uiPreset from './tailwind.preset'
//   export default { presets: [uiPreset], content: [...] }

import type { Config } from 'tailwindcss'

const preset: Partial<Config> = {
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--ui-bg) / <alpha-value>)',
        surface: 'rgb(var(--ui-surface) / <alpha-value>)',
        fg: 'rgb(var(--ui-fg) / <alpha-value>)',
        muted: 'rgb(var(--ui-muted) / <alpha-value>)',
        border: 'rgb(var(--ui-border) / <alpha-value>)',
        brand: {
          DEFAULT: 'rgb(var(--ui-brand) / <alpha-value>)',
          fg: 'rgb(var(--ui-brand-fg) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--ui-success) / <alpha-value>)',
          fg: 'rgb(var(--ui-success-fg) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--ui-warning) / <alpha-value>)',
          fg: 'rgb(var(--ui-warning-fg) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'rgb(var(--ui-danger) / <alpha-value>)',
          fg: 'rgb(var(--ui-danger-fg) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'rgb(var(--ui-info) / <alpha-value>)',
          fg: 'rgb(var(--ui-info-fg) / <alpha-value>)',
        },
      },
      borderRadius: {
        token: 'var(--ui-radius)',
        'token-sm': 'var(--ui-radius-sm)',
        'token-lg': 'var(--ui-radius-lg)',
      },
      fontFamily: {
        sans: 'var(--ui-font-sans)',
      },
    },
  },
}

export default preset
`

export interface EmitThemeFile {
  filename: string
  language: 'css' | 'typescript' | 'markdown'
  code: string
}

export function emitTheme(): EmitThemeFile[] {
  const tokens = getTheme()
  return [
    { filename: 'theme.css', language: 'css', code: makeThemeCss(tokens) },
    { filename: 'tailwind.preset.ts', language: 'typescript', code: TAILWIND_PRESET },
    { filename: 'README.md', language: 'markdown', code: SETUP_README },
  ]
}
