/**
 * Input QA tests — smoke, functional, a11y, and bug-catching.
 *
 * Source: packages/ui-native/src/components/Input/Input.native.tsx
 *
 * ─── Figma API table ─────────────────────────────────────────────────────────
 *
 *   Property   Values                                          Figma type
 *   ─────────────────────────────────────────────────────────────────────
 *   size       XS | S | M | L                                  component property
 *   attention  medium | high                                    component property
 *   appearance auto|neutral|primary|secondary|sparkle|          variable mode
 *              negative|positive|warning|informative
 *   shape      default | pill                                   component property
 *   start      none|Icon|IconButton|Avatar|Image|ChipGroup|Text component property
 *   start2     none | Text                                      component property
 *   end        none | IconButton | Icon | Button | Text         component property
 *   end2       none | Text | Icon | IconButton                  component property
 *   state      idle|focus/active|filled|readOnly|feedback       component property
 *   disabled   true | false                                     variable mode
 *
 * ─── Native prop mapping ─────────────────────────────────────────────────────
 *
 *   Figma size → native InputSize
 *     XS    → 'xs' / 6  → minHeight: tokens.spacing['6']  (FIXED)
 *     S     → 's' / 8  → minHeight: tokens.spacing['8']
 *     M     → 'm' / 10 → minHeight: tokens.spacing['10']  (default)
 *     L     → 'l' / 12 → minHeight: tokens.spacing['12']
 *
 *   attention='medium' → outlined (transparent fill, hairline border at idle)
 *   attention='high'   → filled  (subtle background, no border at idle)
 *
 * ─── Component structure ─────────────────────────────────────────────────────
 *
 *   <Pressable testID={testID} accessible={false}
 *              importantForAccessibility="no-hide-descendants">   ← BUG-INPUT-3
 *     {start slot}
 *     <TextInput {...a11y} accessible={true} accessibilityLabel=... />
 *     {end slot}
 *   </Pressable>
 *
 *   IMPORTANT: The Pressable has importantForAccessibility='no-hide-descendants'.
 *   In RNTL, this flag causes standard queries (getByPlaceholderText, getByLabelText,
 *   getByDisplayValue) to treat the inner TextInput as hidden from accessibility.
 *   All TextInput queries use { includeHiddenElements: true } to bypass this filter.
 *   This is both a test workaround AND evidence of BUG-INPUT-3.
 *
 * ─── Bugs (raise to dev team) ────────────────────────────────────────────────
 *
 *   BUG-INPUT-1 · FIXED — XS size added to InputSize + SIZE_ALIASES + INPUT_SIZE_METRICS.
 *     InputSize is now 'xs'|'s'|'m'|'l' (f6/f8/f10/f12).
 *
 *   BUG-INPUT-2 · readOnly and disabled both set accessibilityState.disabled=true
 *     getInputAccessibilityProps returns:
 *       accessibilityState: { disabled: state.isDisabled || state.isReadOnly }
 *     Both disabled and readOnly surface as "disabled" to screen readers.
 *     VoiceOver/TalkBack cannot distinguish a read-only field (readable but
 *     immutable) from a disabled field (non-interactive entirely).
 *     File: packages/ui-native/src/components/Input/interface.ts:448-452
 *     Fix:  Use accessibilityState.disabled=false for readOnly; convey read-only
 *           semantics via accessibilityHint auto-generated by the component.
 *
 *   BUG-INPUT-3 · Container Pressable importantForAccessibility="no-hide-descendants"
 *     The outer Pressable sets importantForAccessibility='no-hide-descendants'
 *     unconditionally. On Android TalkBack, this hides ALL descendants including
 *     the inner TextInput from the accessibility tree. The same flag causes RNTL
 *     standard queries (getByPlaceholderText, getByLabelText, getByDisplayValue)
 *     to return "Unable to find" errors — workaround: { includeHiddenElements: true }.
 *     File: packages/ui-native/src/components/Input/Input.native.tsx:428
 *     Fix:  Change to importantForAccessibility='no' (hides container only, not children).
 */

import React from 'react';
import { View } from 'react-native';
import { render, screen, fireEvent } from '@testing-library/react-native';
import { describe, it, expect, vi } from 'vitest';
import { tokens } from '@oneui/tokens';
import { Input } from '@ui-native/components/Input/Input.native';
import { InputField } from '@ui-native/components/InputField/InputField.native';
import {
  INPUT_SIZE_METRICS,
  INPUT_BORDER_WIDTH,
} from '@ui-native/components/Input/Input.styles.native';
import { wrap } from '../../utils/renderWithTheme';

// ─── Figma API constants ──────────────────────────────────────────────────────

const APPEARANCES = [
  'auto', 'neutral', 'primary', 'secondary', 'sparkle',
  'negative', 'positive', 'warning', 'informative',
] as const;
const ATTENTIONS  = ['medium', 'high'] as const;
const SIZES       = ['xs', 's', 'm', 'l'] as const;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function flatStyle(style: unknown): Record<string, unknown> {
  if (!style) return {};
  if (Array.isArray(style)) return Object.assign({}, ...(style as unknown[]).map(flatStyle));
  if (typeof style === 'object') return style as Record<string, unknown>;
  return {};
}

/**
 * The outer Pressable has importantForAccessibility='no-hide-descendants' (BUG-INPUT-3).
 * RNTL standard queries filter out the inner TextInput as "hidden".
 * Use { includeHiddenElements: true } to bypass this filter for TextInput queries.
 */
const HIDDEN_OPT = { includeHiddenElements: true } as const;

/**
 * White background wrapper for matrix/appearance tests.
 * Input uses attention="medium" (outlined) which gives a transparent fill —
 * against the dark HTML report panel the box is invisible. A white surface
 * makes the input border and the label above it both clearly visible.
 */
const wrapWhite = (el: React.ReactElement) =>
  wrap(<View style={{ backgroundColor: '#ffffff', padding: 8, width: 300 }}>{el}</View>);

// ─── Figma matrix: size × attention × state ───────────────────────────────────
//
// Rendered via InputField (label + Input) so the visual sketch shows something
// meaningful. The label text is outside the Pressable — visible in the sketch.
// The Input's Pressable (importantForAccessibility="no-hide-descendants") hides
// the TextInput content from the sketch, but the label and field shape are visible.
//
// States mirror the Figma matrix: idle / filled / readOnly / errorHighlight / disabled.

describe('Input — Figma matrix: size × attention × state', () => {
  const STATES = [
    { label: 'idle',           props: {} },
    { label: 'filled',         props: { defaultValue: 'Input text' } },
    { label: 'readOnly',       props: { readOnly: true, defaultValue: 'Input text' } },
    { label: 'errorHighlight', props: { invalid: true } },
    { label: 'disabled',       props: { disabled: true } },
  ] as const;

  for (const size of SIZES) {
    for (const attention of ATTENTIONS) {
      for (const { label, props } of STATES) {
        it(`[smoke] size="${size}" attention="${attention}" state="${label}" renders without crashing`, () => {
          expect(() =>
            render(wrapWhite(
              <InputField
                fullWidth
                label={`${size.toUpperCase()} · ${attention} · ${label}`}
                size={size}
                attention={attention}
                placeholder="Placeholder"
                {...props}
              />,
            )),
          ).not.toThrow();
        });
      }
    }
  }
});

// ─── Figma matrix: appearance ─────────────────────────────────────────────────

describe('Input — Figma matrix: appearance', () => {
  for (const appearance of APPEARANCES) {
    it(`[smoke] appearance="${appearance}" renders without crashing`, () => {
      expect(() =>
        render(wrapWhite(
          <InputField
            fullWidth
            label={appearance}
            appearance={appearance}
            placeholder="Placeholder"
          />,
        )),
      ).not.toThrow();
    });
  }
});

// ─── Figma matrix: shape ──────────────────────────────────────────────────────

describe('Input — Figma matrix: shape', () => {
  it('[smoke] shape="default" renders without crashing', () => {
    expect(() =>
      render(wrapWhite(<InputField fullWidth label="Default shape" shape="default" placeholder="Placeholder" />)),
    ).not.toThrow();
  });

  it('[smoke] shape="pill" renders without crashing', () => {
    expect(() =>
      render(wrapWhite(<InputField fullWidth label="Pill shape" shape="pill" placeholder="Placeholder" />)),
    ).not.toThrow();
  });

  it('[fn] shape="pill" applies pill border radius', () => {
    render(wrap(<Input shape="pill" testID="pill-inp" />));
    const s = flatStyle(screen.getByTestId('pill-inp', HIDDEN_OPT).props.style);
    expect(s.borderRadius).toBe(tokens.shape.pill);
  });

  it('[fn] shape="default" size="m" applies per-size radius', () => {
    render(wrap(<Input shape="default" size="m" testID="def-inp" />));
    const s = flatStyle(screen.getByTestId('def-inp', HIDDEN_OPT).props.style);
    expect(s.borderRadius).toBe(INPUT_SIZE_METRICS[10].borderRadius);
  });
});

// ─── Smoke ────────────────────────────────────────────────────────────────────

describe('Input — smoke', () => {
  it('[smoke] renders without crashing', () => {
    expect(() => render(wrap(<Input />))).not.toThrow();
  });

  it('[smoke] renders with placeholder (TextInput found via includeHiddenElements)', () => {
    // BUG-INPUT-3: includeHiddenElements:true required due to no-hide-descendants on Pressable
    render(wrap(<Input placeholder="Enter text" />));
    expect(screen.getByPlaceholderText('Enter text', HIDDEN_OPT)).toBeTruthy();
  });

  it('[smoke] renders disabled without crashing', () => {
    expect(() => render(wrap(<Input disabled />))).not.toThrow();
  });

  it('[smoke] renders readOnly without crashing', () => {
    expect(() => render(wrap(<Input readOnly />))).not.toThrow();
  });

  it('[smoke] renders errorHighlight without crashing', () => {
    expect(() => render(wrap(<Input errorHighlight />))).not.toThrow();
  });

  it('[smoke] renders all sizes without crashing', () => {
    for (const size of SIZES) {
      const { unmount } = render(wrap(<Input size={size} placeholder={`size ${size}`} />));
      expect(screen.getByPlaceholderText(`size ${size}`, HIDDEN_OPT)).toBeTruthy();
      unmount();
    }
    render(wrap(<Input />));
  });

  it('[smoke] renders with all 4 slots without crashing', () => {
    expect(() =>
      render(wrap(
        <Input
          start={<View testID="s1" />}
          start2="€"
          end={<View testID="e1" />}
          end2="USD"
        />,
      )),
    ).not.toThrow();
  });
});

// ─── Functional: container structure ─────────────────────────────────────────

describe('Input — functional: container structure', () => {
  it('[fn] testID goes to the outer Pressable (tap-forwarder), not TextInput', () => {
    render(wrap(<Input testID="my-input" placeholder="Text" />));
    // Outer Pressable is accessible=false — it is a tap-forwarder only
    expect(screen.getByTestId('my-input', HIDDEN_OPT).props.accessible).toBe(false);
  });

  it('[fn] outer Pressable has importantForAccessibility="no"', () => {
    // Fixed: was "no-hide-descendants" (BUG-INPUT-3), now correctly "no"
    // so the inner TextInput is reachable by TalkBack and standard RNTL queries.
    render(wrap(<Input testID="imp-input" />));
    expect(screen.getByTestId('imp-input', HIDDEN_OPT).props.importantForAccessibility).toBe('no');
  });

  it('[fn] outer Pressable is disabled when input is disabled', () => {
    render(wrap(<Input disabled testID="dis-container" />));
    expect(screen.getByTestId('dis-container', HIDDEN_OPT).props.disabled).toBe(true);
  });

  it('[fn] outer Pressable is disabled when input is readOnly', () => {
    render(wrap(<Input readOnly testID="ro-container" />));
    expect(screen.getByTestId('ro-container', HIDDEN_OPT).props.disabled).toBe(true);
  });
});

// ─── Functional: size dimensions ─────────────────────────────────────────────

describe('Input — functional: size dimensions', () => {
  it('[fn] size="s" (8) → minHeight = tokens.spacing["8"]', () => {
    render(wrap(<Input size="s" testID="size-s" />));
    expect(flatStyle(screen.getByTestId('size-s', HIDDEN_OPT).props.style).minHeight).toBe(INPUT_SIZE_METRICS[8].minHeight);
  });

  it('[fn] size="m" (10) → minHeight = tokens.spacing["10"] (default)', () => {
    render(wrap(<Input size="m" testID="size-m" />));
    expect(flatStyle(screen.getByTestId('size-m', HIDDEN_OPT).props.style).minHeight).toBe(INPUT_SIZE_METRICS[10].minHeight);
  });

  it('[fn] size="l" (12) → minHeight = tokens.spacing["12"]', () => {
    render(wrap(<Input size="l" testID="size-l" />));
    expect(flatStyle(screen.getByTestId('size-l', HIDDEN_OPT).props.style).minHeight).toBe(INPUT_SIZE_METRICS[12].minHeight);
  });

  it('[fn] default size is "m" (minHeight = tokens.spacing["10"])', () => {
    render(wrap(<Input testID="size-default" />));
    expect(flatStyle(screen.getByTestId('size-default', HIDDEN_OPT).props.style).minHeight).toBe(INPUT_SIZE_METRICS[10].minHeight);
  });

  it('[fn] size scale: s < m < l (monotonically increasing)', () => {
    expect(INPUT_SIZE_METRICS[8].minHeight).toBeLessThan(INPUT_SIZE_METRICS[10].minHeight);
    expect(INPUT_SIZE_METRICS[10].minHeight).toBeLessThan(INPUT_SIZE_METRICS[12].minHeight);
  });

  it('[fn] string size aliases: s/m/l resolve to their respective sizes', () => {
    // Numeric size aliases (8/10/12) are no longer part of the public API —
    // resolveInputSize only recognises the t-shirt strings 'xs'|'s'|'m'|'l'.
    // Numeric inputs fall back to M (size=10) with a dev-mode warning.
    // This test verifies the string aliases resolve correctly.
    const { getByTestId: getS } = render(wrap(<Input size="s" testID="alias-ss" />));
    const ss = flatStyle(getS('alias-ss', HIDDEN_OPT).props.style);
    expect(ss.minHeight).toBe(INPUT_SIZE_METRICS[8].minHeight);

    const { getByTestId: getM } = render(wrap(<Input size="m" testID="alias-sm" />));
    const sm = flatStyle(getM('alias-sm', HIDDEN_OPT).props.style);
    expect(sm.minHeight).toBe(INPUT_SIZE_METRICS[10].minHeight);

    const { getByTestId: getL } = render(wrap(<Input size="l" testID="alias-sl" />));
    const sl = flatStyle(getL('alias-sl', HIDDEN_OPT).props.style);
    expect(sl.minHeight).toBe(INPUT_SIZE_METRICS[12].minHeight);

    render(wrap(<Input />));
  });
});

// ─── Functional: attention ────────────────────────────────────────────────────

describe('Input — functional: attention', () => {
  it('[fn] attention="medium" → outlined: borderWidth = idle hairline at rest', () => {
    render(wrap(<Input attention="medium" testID="att-med" />));
    expect(flatStyle(screen.getByTestId('att-med', HIDDEN_OPT).props.style).borderWidth).toBe(INPUT_BORDER_WIDTH.idle);
  });

  it('[fn] attention="high" → filled: borderWidth = 0 at rest (no border)', () => {
    render(wrap(<Input attention="high" testID="att-high" />));
    expect(flatStyle(screen.getByTestId('att-high', HIDDEN_OPT).props.style).borderWidth).toBe(0);
  });
});

// ─── Functional: value ────────────────────────────────────────────────────────

describe('Input — functional: value', () => {
  it('[fn] placeholder renders in TextInput', () => {
    render(wrap(<Input placeholder="Enter your name" />));
    // BUG-INPUT-3: includeHiddenElements required
    expect(screen.getByPlaceholderText('Enter your name', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] controlled value renders in TextInput', () => {
    render(wrap(<Input value="Hello world" placeholder="Text" />));
    expect(screen.getByDisplayValue('Hello world', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] defaultValue renders in TextInput (uncontrolled)', () => {
    render(wrap(<Input defaultValue="Default text" placeholder="Text" />));
    expect(screen.getByDisplayValue('Default text', HIDDEN_OPT)).toBeTruthy();
  });
});

// ─── Functional: events ───────────────────────────────────────────────────────

describe('Input — functional: events', () => {
  it('[fn] onChange fires with typed value', () => {
    const handler = vi.fn();
    render(wrap(<Input onChange={handler} placeholder="Type here" />));
    fireEvent.changeText(screen.getByPlaceholderText('Type here', HIDDEN_OPT), 'hello');
    expect(handler).toHaveBeenCalledWith('hello');
  });

  it('[fn] onChange fires with exact value each keystroke', () => {
    const handler = vi.fn();
    render(wrap(<Input onChange={handler} placeholder="Type here" />));
    const el = screen.getByPlaceholderText('Type here', HIDDEN_OPT);
    fireEvent.changeText(el, 'a');
    fireEvent.changeText(el, 'ab');
    fireEvent.changeText(el, 'abc');
    expect(handler).toHaveBeenNthCalledWith(1, 'a');
    expect(handler).toHaveBeenNthCalledWith(2, 'ab');
    expect(handler).toHaveBeenNthCalledWith(3, 'abc');
  });

  it('[fn] onFocus fires when TextInput receives focus', () => {
    const handler = vi.fn();
    render(wrap(<Input onFocus={handler} placeholder="Focusable" />));
    fireEvent(screen.getByPlaceholderText('Focusable', HIDDEN_OPT), 'focus');
    expect(handler).toHaveBeenCalledTimes(1);
  });

  it('[fn] onBlur fires when TextInput loses focus', () => {
    const handler = vi.fn();
    render(wrap(<Input onBlur={handler} placeholder="Blurable" />));
    fireEvent(screen.getByPlaceholderText('Blurable', HIDDEN_OPT), 'blur');
    expect(handler).toHaveBeenCalledTimes(1);
  });

  it('[fn] onFocus and onBlur fire independently', () => {
    const focusH = vi.fn();
    const blurH = vi.fn();
    render(wrap(<Input onFocus={focusH} onBlur={blurH} placeholder="Both" />));
    const el = screen.getByPlaceholderText('Both', HIDDEN_OPT);
    fireEvent(el, 'focus');
    fireEvent(el, 'blur');
    expect(focusH).toHaveBeenCalledTimes(1);
    expect(blurH).toHaveBeenCalledTimes(1);
  });

  it('[fn] onSubmit fires with current value on submit', () => {
    const handler = vi.fn();
    render(wrap(<Input value="submit text" onSubmit={handler} placeholder="Submit" />));
    fireEvent(screen.getByPlaceholderText('Submit', HIDDEN_OPT), 'submitEditing', {
      nativeEvent: { text: 'submit text' },
    });
    expect(handler).toHaveBeenCalledWith('submit text');
  });

  it('[fn] disabled input: onFocus NOT fired (handleFocus guards isDisabled)', () => {
    const handler = vi.fn();
    render(wrap(<Input disabled onFocus={handler} placeholder="Dis focus" />));
    fireEvent(screen.getByPlaceholderText('Dis focus', HIDDEN_OPT), 'focus');
    expect(handler).not.toHaveBeenCalled();
  });

  it('[fn] disabled input → editable=false on TextInput', () => {
    render(wrap(<Input disabled placeholder="Disabled" />));
    expect(screen.getByPlaceholderText('Disabled', HIDDEN_OPT).props.editable).toBe(false);
  });

  it('[fn] readOnly input → readOnly=true on TextInput (editable stays true)', () => {
    // readOnly uses the TextInput readOnly prop, not editable=false.
    // editable=false is only used for disabled — readOnly keeps editable=true
    // so the field remains selectable/copyable by screen readers.
    render(wrap(<Input readOnly placeholder="ReadOnly" />));
    const el = screen.getByPlaceholderText('ReadOnly', HIDDEN_OPT);
    expect(el.props.readOnly).toBe(true);
    expect(el.props.editable).not.toBe(false);
  });
});

// ─── Functional: type mapping ─────────────────────────────────────────────────

describe('Input — functional: type → keyboard / secureTextEntry', () => {
  it('[fn] type="password" → secureTextEntry=true', () => {
    render(wrap(<Input type="password" placeholder="Password" />));
    expect(screen.getByPlaceholderText('Password', HIDDEN_OPT).props.secureTextEntry).toBe(true);
  });

  it('[fn] type="email" → keyboardType="email-address"', () => {
    render(wrap(<Input type="email" placeholder="Email" />));
    expect(screen.getByPlaceholderText('Email', HIDDEN_OPT).props.keyboardType).toBe('email-address');
  });

  it('[fn] type="number" → keyboardType="numeric"', () => {
    render(wrap(<Input type="number" placeholder="Number" />));
    expect(screen.getByPlaceholderText('Number', HIDDEN_OPT).props.keyboardType).toBe('numeric');
  });

  it('[fn] type="tel" → keyboardType="phone-pad"', () => {
    render(wrap(<Input type="tel" placeholder="Phone" />));
    expect(screen.getByPlaceholderText('Phone', HIDDEN_OPT).props.keyboardType).toBe('phone-pad');
  });

  it('[fn] type="text" → default keyboard, no secureTextEntry', () => {
    render(wrap(<Input type="text" placeholder="Text" />));
    const el = screen.getByPlaceholderText('Text', HIDDEN_OPT);
    expect(el.props.keyboardType).toBe('default');
    expect(el.props.secureTextEntry).not.toBe(true);
  });

  it('[fn] no type → keyboardType="default", no secureTextEntry', () => {
    render(wrap(<Input placeholder="Default" />));
    const el = screen.getByPlaceholderText('Default', HIDDEN_OPT);
    expect(el.props.keyboardType).toBe('default');
    expect(el.props.secureTextEntry).not.toBe(true);
  });
});

// ─── Functional: 4-slot system ───────────────────────────────────────────────

describe('Input — functional: 4-slot system', () => {
  it('[fn] start slot renders in tree', () => {
    render(wrap(<Input start={<View testID="start-content" />} />));
    expect(screen.getByTestId('start-content', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] start2 slot renders string as Text node', () => {
    // Text inside Pressable (no-hide-descendants) → HIDDEN_OPT
    render(wrap(<Input start2="€" />));
    expect(screen.getByText('€', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] end slot renders in tree', () => {
    render(wrap(<Input end={<View testID="end-content" />} />));
    expect(screen.getByTestId('end-content', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] end2 slot renders in tree', () => {
    render(wrap(<Input end2={<View testID="end2-content" />} />));
    expect(screen.getByTestId('end2-content', HIDDEN_OPT)).toBeTruthy();
  });

  it('[fn] all 4 slots render simultaneously', () => {
    render(wrap(
      <Input
        start={<View testID="s1" />}
        start2="$"
        end={<View testID="e1" />}
        end2="USD"
      />,
    ));
    expect(screen.getByTestId('s1', HIDDEN_OPT)).toBeTruthy();
    expect(screen.getByText('$', HIDDEN_OPT)).toBeTruthy();
    expect(screen.getByTestId('e1', HIDDEN_OPT)).toBeTruthy();
    expect(screen.getByText('USD', HIDDEN_OPT)).toBeTruthy();
  });
});

// ─── A11y ─────────────────────────────────────────────────────────────────────

describe('Input — a11y', () => {
  it('[a11y] TextInput has accessible=true', () => {
    render(wrap(<Input accessibilityLabel="Search" placeholder="Search" />));
    expect(screen.getByLabelText('Search', HIDDEN_OPT).props.accessible).toBe(true);
  });

  it('[a11y] outer Pressable has accessible=false (tap-forwarder)', () => {
    render(wrap(<Input testID="a11y-cont" />));
    expect(screen.getByTestId('a11y-cont', HIDDEN_OPT).props.accessible).toBe(false);
  });

  it('[a11y] accessibilityLabel prop maps to TextInput accessibilityLabel', () => {
    render(wrap(<Input accessibilityLabel="Email address" placeholder="Email" />));
    expect(screen.getByLabelText('Email address', HIDDEN_OPT)).toBeTruthy();
  });

  it('[a11y] aria-label alias maps to TextInput accessibilityLabel', () => {
    render(wrap(<Input aria-label="Search field" placeholder="Search" />));
    expect(screen.getByLabelText('Search field', HIDDEN_OPT)).toBeTruthy();
  });

  it('[a11y] disabled → accessibilityState.disabled=true on TextInput', () => {
    render(wrap(<Input disabled accessibilityLabel="Disabled input" />));
    expect(screen.getByLabelText('Disabled input', HIDDEN_OPT).props.accessibilityState?.disabled).toBe(true);
  });

  it('[a11y] aria-invalid=true forwarded to TextInput', () => {
    render(wrap(<Input aria-invalid accessibilityLabel="Invalid field" />));
    expect(screen.getByLabelText('Invalid field', HIDDEN_OPT).props['aria-invalid']).toBe(true);
  });

  it('[a11y] aria-describedby forwarded to TextInput', () => {
    render(wrap(<Input aria-describedby="hint-123" accessibilityLabel="Field" />));
    expect(screen.getByLabelText('Field', HIDDEN_OPT).props['aria-describedby']).toBe('hint-123');
  });

  it('[a11y] accessibilityHint forwarded to TextInput', () => {
    render(wrap(<Input accessibilityHint="Enter your full name" accessibilityLabel="Name" />));
    expect(screen.getByLabelText('Name', HIDDEN_OPT).props.accessibilityHint).toBe('Enter your full name');
  });

  it('[a11y] aria-hidden → TextInput accessible=false, accessibilityElementsHidden=true', () => {
    render(wrap(<Input aria-hidden placeholder="Hidden input" />));
    const el = screen.getByPlaceholderText('Hidden input', HIDDEN_OPT);
    expect(el.props.accessible).not.toBe(true);
    expect(el.props.accessibilityElementsHidden).toBe(true);
  });
});

// ─── Bug-catching ─────────────────────────────────────────────────────────────

describe('Input — bug-catching', () => {
  // ── BUG-INPUT-1 FIXED: XS size now implemented ────────────────────────────

  it('[fn] BUG-INPUT-1 FIXED: all 4 Figma sizes implemented (XS/S/M/L)', () => {
    expect(SIZES.length).toBe(4);
  });

  it('[fn] BUG-INPUT-1 FIXED: size="xs" resolves to XS height (f6), not M (f10)', () => {
    render(wrap(<Input size="xs" testID="xs-inp" />));
    const s = flatStyle(screen.getByTestId('xs-inp', HIDDEN_OPT).props.style);
    expect(s.minHeight).toBe(INPUT_SIZE_METRICS[6].minHeight);
    expect(s.minHeight).not.toBe(INPUT_SIZE_METRICS[10].minHeight);
  });

  // ── BUG-INPUT-2: readOnly → accessibilityState.disabled=true ─────────────

  it('[bug] BUG-INPUT-2: readOnly maps to accessibilityState.disabled=true — same as disabled', () => {
    render(wrap(<Input readOnly accessibilityLabel="ReadOnly field" />));
    const el = screen.getByLabelText('ReadOnly field', HIDDEN_OPT);
    // Expected: readOnly ≠ disabled; should be disabled=false + some readOnly signal
    // Bug: accessibilityState.disabled = isDisabled || isReadOnly = true for readOnly
    expect(el.props.accessibilityState?.disabled).toBe(false);
  });

  // ── BUG-INPUT-3: no-hide-descendants hides TextInput from queries ──────────

  it('[fn] BUG-INPUT-3 FIXED: standard getByPlaceholderText now finds TextInput directly', () => {
    // BUG-INPUT-3 is fixed: importantForAccessibility changed from "no-hide-descendants"
    // to "no", so standard RNTL queries reach the inner TextInput without includeHiddenElements.
    render(wrap(<Input placeholder="Now findable" />));
    // Standard query now works:
    expect(screen.getByPlaceholderText('Now findable')).toBeTruthy();
  });

  it('[fn] BUG-INPUT-3 FIXED: importantForAccessibility="no" — only container hidden, TextInput reachable', () => {
    render(wrap(<Input testID="nhd-inp" />));
    const container = screen.getByTestId('nhd-inp');
    // "no" hides only the container from Android TalkBack; TextInput descendants remain reachable
    expect(container.props.importantForAccessibility).toBe('no');
  });
});
