/**
 * /internal/render-ast — headless render target for the Playwright
 * verification loop. Mounts CompositionRenderer inside the real brand CSS
 * cascade so screenshots reflect the live design system.
 *
 * Security: gated by an `x-internal-render` secret when deployed; in dev
 * we trust the origin since it's localhost-only. The AST itself is looked
 * up server-side by a short-lived token — never embedded in the URL —
 * so nothing sensitive ends up in the browser address bar.
 */

import { ASTRenderer } from '@oneui/ui/runtime';
import type { ASTRoot } from '@oneui/shared';
import { ConvexHttpClient } from 'convex/browser';
import { api } from '@oneui/convex';
import type { Id } from '@oneui/convex/_generated/dataModel';
import { consumeASTForRender } from '@/lib/playwrightRenderer';
import { RenderASTBranded } from './RenderASTBranded';
import { generateInitialRenderBrandCSS } from './brandCss';

interface SearchParams {
  token?: string;
  brandId?: string;
  theme?: string;
  platform?: string;
  density?: string;
  surfaceMode?: string;
}

export const dynamic = 'force-dynamic';

function normalizeTheme(value: string | undefined): 'light' | 'dark' {
  return value === 'dark' ? 'dark' : 'light';
}

async function loadInitialBrandCSS(
  brandId: string | undefined,
  theme: 'light' | 'dark',
): Promise<string> {
  const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!brandId || !convexUrl) return '';

  try {
    // This is the render/tooling read path: Storybook/CDN-style anonymous brand
    // reads stay allowed by Convex, while platform API routes with user-owned
    // data use createRequiredAuthedConvexClient instead.
    const convex = new ConvexHttpClient(convexUrl);
    const foundationData = await convex.query(api.foundations.getBrandOverviewData, {
      brandId: brandId as Id<'brands'>,
    });
    return generateInitialRenderBrandCSS(foundationData, theme);
  } catch (err) {
    console.warn('[internal/render-ast] initial brand CSS generation failed:', err);
    return '';
  }
}

export default async function RenderASTPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>;
}) {
  const { token, brandId, theme, platform, density, surfaceMode } = await searchParams;
  if (!token) {
    return <div style={{ padding: 24, color: 'var(--Negative-Tinted)' }}>Missing token</div>;
  }
  const ast = consumeASTForRender(token) as ASTRoot | null;
  if (!ast) {
    return <div style={{ padding: 24, color: 'var(--Negative-Tinted)' }}>AST not found or expired</div>;
  }
  const resolvedTheme = normalizeTheme(theme);
  const initialBrandCSS = await loadInitialBrandCSS(brandId, resolvedTheme);
  return (
    <>
      {initialBrandCSS ? (
        <style
          id="oneui-initial-render-foundation-tokens"
          // The CSS is generated by the same token-boundary-validated engine as
          // useBrandCSS; it is not user-authored markup.
          dangerouslySetInnerHTML={{ __html: initialBrandCSS }}
        />
      ) : null}
      {brandId ? (
        <RenderASTBranded
          ast={ast}
          brandId={brandId}
          theme={resolvedTheme}
          platform={platform}
          density={density}
          surfaceMode={surfaceMode}
        />
      ) : (
        <div
          data-render-target
          data-oneui-canvas="true"
          style={{
            minHeight: '100vh',
            background: 'var(--Surface-Main)',
            fontFamily: 'var(--Typography-Font-Text)',
          }}
        >
          <ASTRenderer
            tree={ast}
            mode="render"
            surfaceMode={surfaceMode ?? (ast.surfaceMode as string | undefined) ?? 'default'}
            platform={platform}
            density={density}
          />
        </div>
      )}
    </>
  );
}
