/// Flutter-maintained `--SelectableButton-*` defaults when Convex snapshot is partial.
/// Mirrors `SelectableButton.module.css` + `SelectableButton.tokens.ts`.
const Map<String, String> kSelectableButtonDefaultComponentTokenProperties = {
  '--SelectableButton-borderRadius': 'var(--Shape-Pill)',
  '--SelectableButton-backgroundColor': 'transparent',
  '--SelectableButton-textColor': 'var(--Primary-Medium-Text)',
  '--SelectableButton-borderColor': 'var(--Primary-Stroke-Low)',
  '--SelectableButton-backgroundColor-selected-high':
      'var(--Primary-Bold)',
  '--SelectableButton-textColor-selected-high':
      'var(--Primary-Bold-High)',
  '--SelectableButton-backgroundColor-selected-medium':
      'var(--Primary-Subtle)',
  '--SelectableButton-textColor-selected-medium':
      'var(--Primary-TintedA11y)',
  '--SelectableButton-textColor-selected-low':
      'var(--Primary-TintedA11y)',
  '--SelectableButton-borderColor-selected-low': 'var(--Primary-Bold)',
  '--SelectableButton-backgroundColor-hover': 'var(--Primary-Hover)',
  '--SelectableButton-backgroundColor-selected-high-hover':
      'var(--Primary-Bold-Hover)',
  '--SelectableButton-backgroundColor-selected-medium-hover':
      'var(--Primary-Subtle-Hover)',
  '--SelectableButton-backgroundColor-selected-low-hover':
      'var(--Primary-Hover)',
  '--SelectableButton-textColor-uncontained': 'var(--Primary-Medium-Text)',
  '--SelectableButton-textColor-uncontained-selected':
      'var(--Primary-TintedA11y)',
  '--SelectableButton-fontWeight-uncontained-selected':
      'var(--Label-FontWeight-High)',
  '--SelectableButton-fontFamily':
      'var(--Label-FontFamily, var(--Typography-Font-Primary))',
  '--SelectableButton-fontWeight': 'var(--Label-FontWeight-High)',
  '--SelectableButton-textTransform': 'none',
  '--SelectableButton-letterSpacing': 'normal',
  '--SelectableButton-transitionDuration': 'var(--Motion-Duration-M)',
  '--SelectableButton-transitionEasing':
      'var(--Motion-Easing-Transition-Moderate)',
  '--SelectableButton-fullWidth': '100%',
  '--SelectableButton-height': 'var(--Spacing-10)',
  '--SelectableButton-height-xs': 'var(--Spacing-4-5)',
  '--SelectableButton-height-s': 'var(--Spacing-8)',
  '--SelectableButton-height-m': 'var(--Spacing-10)',
  '--SelectableButton-height-l': 'var(--Spacing-12)',
  '--SelectableButton-minHeight-xs': 'var(--Spacing-4-5)',
  '--SelectableButton-minHeight-s': 'var(--Spacing-8)',
  '--SelectableButton-minHeight-m': 'var(--Spacing-10)',
  '--SelectableButton-minHeight-l': 'var(--Spacing-12)',
  '--SelectableButton-minHeight-xs-condensed': 'var(--Spacing-1-5)',
  '--SelectableButton-minHeight-s-condensed': 'var(--Spacing-4-5)',
  '--SelectableButton-minHeight-m-condensed': 'var(--Spacing-6)',
  '--SelectableButton-minHeight-l-condensed': 'var(--Spacing-8)',
  '--SelectableButton-paddingHorizontal': 'var(--Spacing-5)',
  '--SelectableButton-paddingHorizontal-xs': 'var(--Spacing-4)',
  '--SelectableButton-paddingHorizontal-s': 'var(--Spacing-4)',
  '--SelectableButton-paddingHorizontal-m': 'var(--Spacing-5)',
  '--SelectableButton-paddingHorizontal-l': 'var(--Spacing-6)',
  '--SelectableButton-paddingHorizontal-xs-condensed': 'var(--Spacing-2-5)',
  '--SelectableButton-paddingHorizontal-s-condensed': 'var(--Spacing-2-5)',
  '--SelectableButton-paddingHorizontal-m-condensed': 'var(--Spacing-3)',
  '--SelectableButton-paddingHorizontal-l-condensed': 'var(--Spacing-3-5)',
  '--SelectableButton-paddingHorizontalStart-xs-slot': 'var(--Spacing-1)',
  '--SelectableButton-paddingHorizontalEnd-xs-slot': 'var(--Spacing-1)',
  '--SelectableButton-paddingHorizontalStart-s-slot': 'var(--Spacing-3)',
  '--SelectableButton-paddingHorizontalEnd-s-slot': 'var(--Spacing-3)',
  '--SelectableButton-paddingHorizontalStart-m-slot': 'var(--Spacing-4)',
  '--SelectableButton-paddingHorizontalEnd-m-slot': 'var(--Spacing-4)',
  '--SelectableButton-paddingHorizontalStart-l-slot': 'var(--Spacing-5)',
  '--SelectableButton-paddingHorizontalEnd-l-slot': 'var(--Spacing-5)',
  '--SelectableButton-paddingVertical-xs': 'var(--Spacing-0-5)',
  '--SelectableButton-paddingVertical-s': 'var(--Spacing-0-5)',
  '--SelectableButton-paddingVertical-m': 'var(--Spacing-1)',
  '--SelectableButton-paddingVertical-l': 'var(--Spacing-2)',
  '--SelectableButton-gap': 'var(--Spacing-1-5)',
  '--SelectableButton-gap-xs': 'var(--Spacing-1)',
  '--SelectableButton-gap-s': 'var(--Spacing-1)',
  '--SelectableButton-gap-m': 'var(--Spacing-1-5)',
  '--SelectableButton-gap-l': 'var(--Spacing-1-5)',
  '--SelectableButton-fontSize': 'var(--Label-M-FontSize)',
  '--SelectableButton-fontSize-xs': 'var(--Label-XS-FontSize)',
  '--SelectableButton-fontSize-s': 'var(--Label-S-FontSize)',
  '--SelectableButton-fontSize-m': 'var(--Label-M-FontSize)',
  '--SelectableButton-fontSize-l': 'var(--Label-L-FontSize)',
  '--SelectableButton-lineHeight': 'var(--Label-M-LineHeight)',
  '--SelectableButton-lineHeight-xs': 'var(--Label-XS-LineHeight)',
  '--SelectableButton-lineHeight-s': 'var(--Label-S-LineHeight)',
  '--SelectableButton-lineHeight-m': 'var(--Label-M-LineHeight)',
  '--SelectableButton-lineHeight-l': 'var(--Label-L-LineHeight)',
  '--SelectableButton-iconSize-xs': 'var(--Spacing-3-5)',
  '--SelectableButton-iconSize-s': 'var(--Spacing-4)',
  '--SelectableButton-iconSize-m': 'var(--Spacing-5)',
  '--SelectableButton-iconSize-l': 'var(--Spacing-6)',
  '--SelectableButton-iconSize-uncontained': '1em',
  '--SelectableButton-roleBold': 'var(--Primary-Bold)',
  '--SelectableButton-roleBoldHigh': 'var(--Primary-Bold-High)',
  '--SelectableButton-roleBoldHover': 'var(--Primary-Bold-Hover)',
  '--SelectableButton-roleSubtle': 'var(--Primary-Subtle)',
  '--SelectableButton-roleSubtleHover': 'var(--Primary-Subtle-Hover)',
  '--SelectableButton-roleTintedA11y': 'var(--Primary-TintedA11y)',
  '--SelectableButton-roleMediumText': 'var(--Primary-Medium-Text)',
  '--SelectableButton-roleStrokeLow': 'var(--Primary-Stroke-Low)',
  '--SelectableButton-roleHover': 'var(--Primary-Hover)',
  '--SelectableButton-cssDecorationClipPath': 'none',
  '--SelectableButton-cssDecorationColor':
      'var(--Button-cssDecorationColor, currentColor)',
  '--SelectableButton-cssDecorationInsetStrokeWidth':
      'var(--Button-cssDecorationInsetStrokeWidth, var(--Spacing-0))',
  '--SelectableButton-cssDecorationStrokeStyle': 'solid',
  '--SelectableButton-cssDecorationStrokeWidth':
      'var(--Button-cssDecorationStrokeWidth, var(--Stroke-L))',
  '--SelectableButton-cssDecorationUnderlineWidth': 'var(--Spacing-0)',
};
