/**
 * exportBrandData.ts
 *
 * Fetches every brand + sub-brand from Convex and writes a trimmed `BrandData`
 * JSON file for each variant under `brand-data/<BrandName>/`.
 *
 * Output contains only fields consumed by `@oneui/ui-native`:
 *   foundationToNativeTheme → buildNativeTheme (foundation)
 *   OneUIBrandProvider (components)
 *
 *   brand-data/
 *     Jio/
 *       base.json          ← { foundation, components }
 *       JioMart.json       ← { foundation (sub-brand accents applied), components }
 *       MyJio.json
 *       …
 *     Tira/
 *       base.json
 *     …
 *
 * Usage:
 *   pnpm tsx apps/native-components-sample/scripts/exportBrandData.ts
 *
 * The Convex deployment URL is read from EXPO_PUBLIC_CONVEX_URL (same .env
 * used by the Expo app).
 */

import { ConvexHttpClient } from 'convex/browser';
import { api } from '@oneui/convex';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import type { DecorationConfig } from '@oneui/shared';
import { trimFoundation } from './trimBrandFoundation';
import { BRAND_DATA_VERSION } from './brandDataConstants';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const OUT_DIR = path.resolve(__dirname, '../brand-data');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Converts a brand/sub-brand name to a lowercase filesystem-safe slug. */
export function slugify(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase();
}

function lookupKey(brandName: string, variantName = 'base'): string {
  return `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;
}

function toImportIdentifier(brandSlug: string, variantSlug: string): string {
  return `brand_${slugify(brandSlug).replace(/-/g, '_')}_${slugify(variantSlug).replace(/-/g, '_')}`;
}

/**
 * Metro requires static JSON imports. After export, emit a lookup module that
 * maps brand name + variant → bundled BrandData snapshot.
 */
async function generateOfflineManifest(): Promise<void> {
  const manifestPath = path.resolve(__dirname, '../src/brand-data/offlineBrandData.generated.ts');

  // Canonical layout:
  //   brand-data/{brand}/latest.json                         → base BrandData
  //   brand-data/{brand}/sub-brands/{subbrand}/latest.json  → ThemeData delta
  const baseEntries: Array<{ importName: string; brandSlug: string; importPath: string; key: string }> = [];
  const themeEntries: Array<{ importName: string; brandSlug: string; variantSlug: string; importPath: string; key: string }> = [];

  const brandDirs = await fs.readdir(OUT_DIR, { withFileTypes: true });
  for (const brandDir of brandDirs) {
    if (!brandDir.isDirectory()) continue;
    const brandSlug = brandDir.name;
    const brandPath = path.join(OUT_DIR, brandSlug);
    const entries = await fs.readdir(brandPath, { withFileTypes: true });

    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (entry.name !== 'sub-brands') continue;
        // Walk sub-brands/ for theme delta files
        const subBrandsPath = path.join(brandPath, 'sub-brands');
        const subEntries = await fs.readdir(subBrandsPath, { withFileTypes: true });
        for (const sub of subEntries) {
          if (!sub.isDirectory()) continue;
          const variantSlug = sub.name;
          const latestPath = path.join(subBrandsPath, variantSlug, 'latest.json');
          try { await fs.access(latestPath); } catch { continue; }
          themeEntries.push({
            importName: toImportIdentifier(brandSlug, variantSlug),
            brandSlug,
            variantSlug,
            importPath: `../../brand-data/${brandSlug}/sub-brands/${variantSlug}/latest.json`,
            key: `${slugify(brandSlug)}::${slugify(variantSlug)}`,
          });
        }
      } else if (entry.name === 'latest.json') {
        // Base brand file: {brand}/latest.json
        baseEntries.push({
          importName: toImportIdentifier(brandSlug, 'base'),
          brandSlug,
          importPath: `../../brand-data/${brandSlug}/latest.json`,
          key: slugify(brandSlug),
        });
      }
    }
  }

  baseEntries.sort((a, b) => a.key.localeCompare(b.key));
  themeEntries.sort((a, b) => a.key.localeCompare(b.key));
  const totalEntries = baseEntries.length + themeEntries.length;

  const lines = [
    '/** AUTO-GENERATED by scripts/exportBrandData.ts — do not edit. */',
    "import type { BrandData, ThemeData } from '@oneui/ui-native/theme';",
    '',
    '// Base brand snapshots — { foundation, components }',
    ...baseEntries.map((e) => `import ${e.importName} from '${e.importPath}';`),
    '',
    '// Sub-brand theme deltas — raw JSON files: { themeData: {...}, colorScales?: [...] }',
    ...themeEntries.map((e) => `import ${e.importName} from '${e.importPath}';`),
    '',
    "function slugify(name: string): string {",
    "  return name.replace(/[^a-zA-Z0-9-_]/g, '-');",
    '}',
    '',
    '/** Maps brand name → base BrandData snapshot. */',
    'const OFFLINE_BRAND_DATA: Record<string, BrandData> = {',
    ...baseEntries.map((e) => `  '${e.key}': ${e.importName} as BrandData,`),
    '};',
    '',
    '/** Maps brandName::variantName → ThemeData (raw sub-brand JSON — provider normalises internally). */',
    'const OFFLINE_THEME_DATA: Record<string, ThemeData> = {',
    ...themeEntries.map((e) => `  '${e.key}': ${e.importName} as ThemeData,`),
    '};',
    '',
    '/**',
    ' * Load the base brand snapshot (foundation + components) by display name.',
    ' * Returns `undefined` if no snapshot exists — run `export:brands` to generate.',
    ' */',
    "export function getOfflineBrandData(brandName: string): BrandData | undefined {",
    '  return OFFLINE_BRAND_DATA[slugify(brandName).toLowerCase()];',
    '}',
    '',
    '/**',
    ' * Load a sub-brand theme delta by brand name + variant name.',
    ' * The raw JSON is passed directly to OneUIBrandProvider which normalises it.',
    ' * Returns `undefined` if no theme file exists for the given variant.',
    ' */',
    "export function getOfflineThemeData(brandName: string, variantName: string): ThemeData | undefined {",
    '  const key = `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;',
    '  return OFFLINE_THEME_DATA[key];',
    '}',
    '',
  ];

  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, lines.join('\n'), 'utf-8');
  console.log(`  ✓ src/brand-data/offlineBrandData.generated.ts (${baseEntries.length} brand(s), ${themeEntries.length} theme(s))`);
}

function resolveConvexUrl(): string | undefined {
  return (
    process.env.EXPO_PUBLIC_CONVEX_URL ??
    process.env.NEXT_PUBLIC_CONVEX_URL ??
    process.env.CONVEX_URL
  );
}

/** Load `.env.local` from the app dir and repo root (works regardless of cwd). */
async function loadEnvFiles(): Promise<void> {
  const candidates = [
    path.resolve(__dirname, '../.env.local'),
    path.resolve(__dirname, '../../../.env.local'),
  ];

  for (const envPath of candidates) {
    try {
      const content = await fs.readFile(envPath, 'utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
        if (!process.env[key]) process.env[key] = value;
      }
    } catch {
      // optional — file may not exist
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  await loadEnvFiles();

  const convexUrl = resolveConvexUrl();
  if (!convexUrl) {
    console.error(
      'Error: Convex URL is not set.\n' +
        '  Set EXPO_PUBLIC_CONVEX_URL in apps/native-components-sample/.env.local\n' +
        '  Run: pnpm --filter @oneui/native-components-sample export:brands',
    );
    process.exit(1);
  }

  const client = new ConvexHttpClient(convexUrl);

  console.log(`Connecting to ${convexUrl}`);

  const brands = await client.query(api.brands.list);
  console.log(`Found ${brands.length} brand(s): ${brands.map((b) => b.name).join(', ')}`);

  for (const brand of brands) {
    const brandSlug = slugify(brand.name);
    const brandDir = path.join(OUT_DIR, brandSlug);
    await fs.mkdir(brandDir, { recursive: true });

    // Fetch brand data
    const [foundation, components, subBrands] = await Promise.all([
      client.query(api.foundations.getBrandOverviewData, { brandId: brand._id }),
      client.query(api.componentTokenOverrides.getAllBrandComponentData, { brandId: brand._id }),
      client.query(api.subBrandConfigs.getByParentBrand, { parentBrandId: brand._id }),
    ]);

    // Base variant — {brand}/latest.json
    // Trimmed to the brand's OWN scales only; sub-brand delta scales are stored
    // in each sub-brand file so the base JSON stays lean.
    //
    // Decorations (SVG ornament configs) are extracted from the foundation response
    // BEFORE trimming, because trimFoundation strips them. They are stored as a
    // top-level key (parallel to foundation/components) so OneUIBrandProvider can
    // read them without parsing the foundation envelope.
    const foundationRaw = foundation as { decorations?: DecorationConfig[] } | null | undefined;
    const decorations: DecorationConfig[] = foundationRaw?.decorations ?? [];
    const trimmedFoundation = trimFoundation(foundation);
    const baseData = {
      version: BRAND_DATA_VERSION,
      foundation: trimmedFoundation,
      components,
      ...(decorations.length > 0 ? { decorations } : {}),
    };
    const basePath = path.join(brandDir, 'latest.json');
    await fs.writeFile(basePath, JSON.stringify(baseData, null, 2), 'utf-8');
    console.log(`  ✓ ${brandSlug}/latest.json`);

    // Fetch ALL scales from the brand's preset collection — not just the ones
    // the base brand selected. getBrandOverviewData only returns selected scales,
    // but sub-brands may reference scales (e.g. "red", "sky") that the base
    // brand didn't select. The collection ID is embedded in the foundation response.
    type PresetScaleEntry = { name: string; baseStep?: string; steps?: Array<{ step: string; oklch: string }> };
    const presetCollectionId = (
      (foundation as Record<string, unknown> | null | undefined)
        ?.presetSelection as { collection?: { _id?: string } } | null | undefined
    )?.collection?._id;

    let fullPresetScales: PresetScaleEntry[] = [];
    if (presetCollectionId) {
      const fullCollection = await client.query(api.presetColorScales.getCollection, {
        collectionId: presetCollectionId as never,
      });
      fullPresetScales = (fullCollection?.scales ?? []).map((s: Record<string, unknown>) => ({
        name: s.name as string,
        baseStep: s.baseStep as string | undefined,
        steps: s.steps as Array<{ step: string; oklch: string }> | undefined,
      }));
    }

    // Scale names already in the base brand — derived from the TRIMMED foundation
    // so we only count scales that the base brand actually uses (not all 36 preset
    // scales the colorConfig might reference). Delta scales for sub-brands are any
    // accent scales NOT in this set.
    const trimmedFd = trimmedFoundation as {
      presetSelection?: { selectedScales?: Array<{ name: string }> };
      color?: { config?: { brandScales?: Array<{ name: string }> } };
    } | null | undefined;
    const basePresetNames = new Set<string>(
      (trimmedFd?.presetSelection?.selectedScales ?? []).map((s) => s.name.toLowerCase()),
    );
    const baseColorConfigNames = new Set<string>(
      (trimmedFd?.color?.config?.brandScales ?? []).map((s) => s.name.toLowerCase()),
    );
    const allBaseScaleNames = new Set([...basePresetNames, ...baseColorConfigNames]);

    // Sub-brand variants — {brand}/sub-brands/{subbrand}/latest.json
    // Writes the 4-accent themeData delta + any delta color scales (scales the
    // sub-brand needs that are NOT already in the base brand).  The provider
    // injects delta scales at runtime before merging accents so every sub-brand
    // file is fully self-contained.
    for (const sub of subBrands) {
      const subSlug = slugify(sub.name);
      // Collect accent scale names in lowercase for case-insensitive matching
      // against the preset collection (collection names may differ in case from
      // the sub-brand config's scaleName values).
      const accentScaleNamesLower = new Set([
        sub.primary.scaleName.toLowerCase(),
        sub.secondary.scaleName.toLowerCase(),
        sub.sparkle.scaleName.toLowerCase(),
        sub.brandBg.scaleName.toLowerCase(),
      ]);

      // Include only scales the sub-brand needs that the base brand doesn't have.
      const deltaColorScales = fullPresetScales
        .filter((s) => accentScaleNamesLower.has(s.name.toLowerCase()) && !allBaseScaleNames.has(s.name.toLowerCase()))
        .map((s) => ({
          name: s.name,
          ...(s.baseStep ? { baseStep: s.baseStep } : {}),
          ...(s.steps?.length ? { steps: s.steps } : {}),
        }));

      const subData: Record<string, unknown> = {
        version: BRAND_DATA_VERSION,
        themeData: {
          primary: sub.primary,
          secondary: sub.secondary,
          sparkle: sub.sparkle,
          brandBg: sub.brandBg,
        },
        ...(deltaColorScales.length > 0 ? { colorScales: deltaColorScales } : {}),
      };
      const subDir = path.join(brandDir, 'sub-brands', subSlug);
      await fs.mkdir(subDir, { recursive: true });
      await fs.writeFile(path.join(subDir, 'latest.json'), JSON.stringify(subData, null, 2), 'utf-8');
      console.log(
        `  ✓ ${brandSlug}/sub-brands/${subSlug}/latest.json` +
        (deltaColorScales.length ? ` (+${deltaColorScales.length} delta scale(s))` : ''),
      );
    }
  }

  await generateOfflineManifest();

  console.log(`\nDone — ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
