/**
 * Bake jio's CDN-harvested CSS into a TypeScript module that ships with
 * @oneui/ui. BrandProvider dynamically imports this when the Vite plugin
 * isn't configured (or `oneui.brands.json` doesn't include "jio"), so a
 * bare-bones install still renders the default brand without crashing.
 *
 * The output file (packages/ui/cdn-bootstrap/jio.ts) is .gitignored and
 * regenerated automatically by `pnpm pack:all` (step 3 in build-all.ts).
 * To regenerate manually:
 *
 *   pnpm cdn:bake-jio
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const BRAND_DIR = resolve(ROOT, 'cdn-dist/brands/jio');
const SRC = resolve(BRAND_DIR, 'latest.css');
const OUT = resolve(ROOT, 'packages/ui/cdn-bootstrap/jio.ts');

if (!existsSync(SRC)) {
  console.error(`bake-jio-fallback: ${SRC} not found. Run \`pnpm cdn:harvest --slug=jio\` first.`);
  process.exit(1);
}

const css = readFileSync(SRC, 'utf8');
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

// Read sidecars from the v2 consolidated brand.json (latest version), with
// fallback to legacy per-file sidecars for older harvests. Embed `null` when
// absent so the bake degrades gracefully. Without these, BrandProvider's
// fallback path renders without themeConfig (wrong Surface step → wrong fill
// colour) and without branding (no logo SVG).
function pickKey(bundle: Record<string, unknown> | null, key: string, legacyFile: string): string {
  if (bundle && bundle[key] != null) return JSON.stringify(bundle[key]);
  const p = resolve(BRAND_DIR, legacyFile);
  if (!existsSync(p)) return 'null';
  const raw = readFileSync(p, 'utf8').trim();
  return raw.length === 0 ? 'null' : raw;
}

const latestJsonPath = resolve(BRAND_DIR, 'latest.json');
const bundle: Record<string, unknown> | null = existsSync(latestJsonPath)
  ? (JSON.parse(readFileSync(latestJsonPath, 'utf8')) as Record<string, unknown>)
  : null;

const themeConfigJson = pickKey(bundle, 'themeConfig', 'themeConfig.json');
const brandingJson    = pickKey(bundle, 'branding',    'branding.json');
const materialsJson   = pickKey(bundle, 'materials',   'materials.json');
const fontsJson       = pickKey(bundle, 'fonts',       'fonts.json');
const decorationsJson = pickKey(bundle, 'decorations', 'decorations.json');

const body = `/**
 * Baked jio brand CSS + sidecars — fallback used by BrandProvider when
 * @oneui/vite-plugin is not configured or "jio" is not listed in the
 * consumer's oneui.brands.json.
 *
 * AUTO-GENERATED by cdn-release-full-pipeline/cdn-poc/bake-jio-fallback.ts. Do not edit manually.
 * Re-run \`pnpm cdn:bake-jio\` after each harvest.
 */
const jioCSS: string = \`${escaped}\`;
export default jioCSS;

export const jioThemeConfig: unknown = ${themeConfigJson};
export const jioBranding: unknown    = ${brandingJson};
export const jioMaterials: unknown   = ${materialsJson};
export const jioFonts: unknown       = ${fontsJson};
export const jioDecorations: unknown = ${decorationsJson};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(
  `✓ wrote ${OUT} (${(css.length / 1024).toFixed(1)} KB CSS + sidecars: ` +
  `themeConfig=${themeConfigJson === 'null' ? 'missing' : 'ok'}, ` +
  `branding=${brandingJson === 'null' ? 'missing' : 'ok'}, ` +
  `materials=${materialsJson === 'null' ? 'missing' : 'ok'}, ` +
  `fonts=${fontsJson === 'null' ? 'missing' : 'ok'}, ` +
  `decorations=${decorationsJson === 'null' ? 'missing' : 'ok'})`,
);
