/** AUTO-GENERATED by scripts/exportBrandData.ts — do not edit. */
import type { BrandData } from '@oneui/ui-native/theme';

import brand_Jio_Agriculture from '../../brand-data/Jio/Agriculture.json';
import brand_Jio_base from '../../brand-data/Jio/base.json';
import brand_Jio_Business from '../../brand-data/Jio/Business.json';
import brand_Jio_Finance from '../../brand-data/Jio/Finance.json';
import brand_Jio_Home from '../../brand-data/Jio/Home.json';
import brand_Jio_JioAICloud from '../../brand-data/Jio/JioAICloud.json';
import brand_Jio_JioBlackRock from '../../brand-data/Jio/JioBlackRock.json';
import brand_Jio_JioBlast from '../../brand-data/Jio/JioBlast.json';
import brand_Jio_JioBusiness from '../../brand-data/Jio/JioBusiness.json';
import brand_Jio_JioCX from '../../brand-data/Jio/JioCX.json';
import brand_Jio_JioFinance_New from '../../brand-data/Jio/JioFinance-New.json';
import brand_Jio_JioFit from '../../brand-data/Jio/JioFit.json';
import brand_Jio_JioGames from '../../brand-data/Jio/JioGames.json';
import brand_Jio_JioHealthHub from '../../brand-data/Jio/JioHealthHub.json';
import brand_Jio_JioHome from '../../brand-data/Jio/JioHome.json';
import brand_Jio_JioMart from '../../brand-data/Jio/JioMart.json';
import brand_Jio_JioMessages from '../../brand-data/Jio/JioMessages.json';
import brand_Jio_JioMobile from '../../brand-data/Jio/JioMobile.json';
import brand_Jio_JioNews from '../../brand-data/Jio/JioNews.json';
import brand_Jio_JioPC from '../../brand-data/Jio/JioPC.json';
import brand_Jio_JioSaavn from '../../brand-data/Jio/JioSaavn.json';
import brand_Jio_JioSarthi from '../../brand-data/Jio/JioSarthi.json';
import brand_Jio_JioStar from '../../brand-data/Jio/JioStar.json';
import brand_Jio_JioThings from '../../brand-data/Jio/JioThings.json';
import brand_Jio_JioTranslate from '../../brand-data/Jio/JioTranslate.json';
import brand_Jio_JioTV from '../../brand-data/Jio/JioTV.json';
import brand_Jio_JioWave from '../../brand-data/Jio/JioWave.json';
import brand_Jio_JioWorkspace from '../../brand-data/Jio/JioWorkspace.json';
import brand_Jio_Mobile from '../../brand-data/Jio/Mobile.json';
import brand_Jio_MyJio from '../../brand-data/Jio/MyJio.json';
import brand_Jio_Shopping from '../../brand-data/Jio/Shopping.json';
import brand_One_UI_Theme_base from '../../brand-data/One-UI-Theme/base.json';
import brand_Reliance_base from '../../brand-data/Reliance/base.json';
import brand_Swadesh_base from '../../brand-data/Swadesh/base.json';
import brand_Tira_base from '../../brand-data/Tira/base.json';

function slugify(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '-');
}

function lookupKey(brandName: string, variantName = 'base'): string {
  return `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;
}

const OFFLINE_BRAND_DATA: Record<string, BrandData> = {
  'jio::agriculture': brand_Jio_Agriculture as BrandData,
  'jio::base': brand_Jio_base as BrandData,
  'jio::business': brand_Jio_Business as BrandData,
  'jio::finance': brand_Jio_Finance as BrandData,
  'jio::home': brand_Jio_Home as BrandData,
  'jio::jioaicloud': brand_Jio_JioAICloud as BrandData,
  'jio::jioblackrock': brand_Jio_JioBlackRock as BrandData,
  'jio::jioblast': brand_Jio_JioBlast as BrandData,
  'jio::jiobusiness': brand_Jio_JioBusiness as BrandData,
  'jio::jiocx': brand_Jio_JioCX as BrandData,
  'jio::jiofinance-new': brand_Jio_JioFinance_New as BrandData,
  'jio::jiofit': brand_Jio_JioFit as BrandData,
  'jio::jiogames': brand_Jio_JioGames as BrandData,
  'jio::jiohealthhub': brand_Jio_JioHealthHub as BrandData,
  'jio::jiohome': brand_Jio_JioHome as BrandData,
  'jio::jiomart': brand_Jio_JioMart as BrandData,
  'jio::jiomessages': brand_Jio_JioMessages as BrandData,
  'jio::jiomobile': brand_Jio_JioMobile as BrandData,
  'jio::jionews': brand_Jio_JioNews as BrandData,
  'jio::jiopc': brand_Jio_JioPC as BrandData,
  'jio::jiosaavn': brand_Jio_JioSaavn as BrandData,
  'jio::jiosarthi': brand_Jio_JioSarthi as BrandData,
  'jio::jiostar': brand_Jio_JioStar as BrandData,
  'jio::jiothings': brand_Jio_JioThings as BrandData,
  'jio::jiotranslate': brand_Jio_JioTranslate as BrandData,
  'jio::jiotv': brand_Jio_JioTV as BrandData,
  'jio::jiowave': brand_Jio_JioWave as BrandData,
  'jio::jioworkspace': brand_Jio_JioWorkspace as BrandData,
  'jio::mobile': brand_Jio_Mobile as BrandData,
  'jio::myjio': brand_Jio_MyJio as BrandData,
  'jio::shopping': brand_Jio_Shopping as BrandData,
  'one-ui-theme::base': brand_One_UI_Theme_base as BrandData,
  'reliance::base': brand_Reliance_base as BrandData,
  'swadesh::base': brand_Swadesh_base as BrandData,
  'tira::base': brand_Tira_base as BrandData,
};

/** Every exported (brand, variant) pair — drives the offline brand picker. */
export const OFFLINE_BRANDS: ReadonlyArray<{ brand: string; variant: string }> = [
  { brand: 'Jio', variant: 'Agriculture' },
  { brand: 'Jio', variant: 'base' },
  { brand: 'Jio', variant: 'Business' },
  { brand: 'Jio', variant: 'Finance' },
  { brand: 'Jio', variant: 'Home' },
  { brand: 'Jio', variant: 'JioAICloud' },
  { brand: 'Jio', variant: 'JioBlackRock' },
  { brand: 'Jio', variant: 'JioBlast' },
  { brand: 'Jio', variant: 'JioBusiness' },
  { brand: 'Jio', variant: 'JioCX' },
  { brand: 'Jio', variant: 'JioFinance-New' },
  { brand: 'Jio', variant: 'JioFit' },
  { brand: 'Jio', variant: 'JioGames' },
  { brand: 'Jio', variant: 'JioHealthHub' },
  { brand: 'Jio', variant: 'JioHome' },
  { brand: 'Jio', variant: 'JioMart' },
  { brand: 'Jio', variant: 'JioMessages' },
  { brand: 'Jio', variant: 'JioMobile' },
  { brand: 'Jio', variant: 'JioNews' },
  { brand: 'Jio', variant: 'JioPC' },
  { brand: 'Jio', variant: 'JioSaavn' },
  { brand: 'Jio', variant: 'JioSarthi' },
  { brand: 'Jio', variant: 'JioStar' },
  { brand: 'Jio', variant: 'JioThings' },
  { brand: 'Jio', variant: 'JioTranslate' },
  { brand: 'Jio', variant: 'JioTV' },
  { brand: 'Jio', variant: 'JioWave' },
  { brand: 'Jio', variant: 'JioWorkspace' },
  { brand: 'Jio', variant: 'Mobile' },
  { brand: 'Jio', variant: 'MyJio' },
  { brand: 'Jio', variant: 'Shopping' },
  { brand: 'One-UI-Theme', variant: 'base' },
  { brand: 'Reliance', variant: 'base' },
  { brand: 'Swadesh', variant: 'base' },
  { brand: 'Tira', variant: 'base' },
];

/** Load exported brand snapshot by display name (e.g. "Tira", "Jio") and variant ("base" or sub-brand name). */
export function getOfflineBrandData(brandName: string, variantName = 'base'): BrandData | undefined {
  return OFFLINE_BRAND_DATA[lookupKey(brandName, variantName)];
}
