/**
 * React Native starter — TERMINAL CLI integration.
 *
 * The RN starter app is generated by the standalone `@oneui/create-native-app` CLI,
 * which is published to the SAME private Azure DevOps feed as the @oneui/* runtime
 * packages (JIO-DS-OneUI-Native). Its dist is fully self-contained (tsup
 * `noExternal: [/./]` bundles every dependency), so `npx` only needs to fetch the
 * CLI tarball itself from the feed — no public-npm dependency install.
 *
 * The MCP cannot host the CLI's interactive PAT prompt — stdio IS the protocol
 * channel, so there is no TTY to the human. So instead of scaffolding in-process,
 * this module helps the tool EMIT the exact terminal command for the user to run in
 * their own shell, where the hidden PAT prompt works normally and the token never
 * passes through the MCP or the agent. This mirrors how `get_registry_setup` emits
 * steps rather than performing them.
 *
 * Self-contained: no monorepo dependency, no secret read or written.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { homedir } from 'node:os';

// ── Native private feed (Azure DevOps Artifacts) ───────────────────────────────
export const NATIVE_REGISTRY_HOST = 'jio-dsp.pkgs.visualstudio.com';
export const NATIVE_REGISTRY_FEED = 'JIO-DS-OneUI-Native';
export const NATIVE_REGISTRY_URL = `https://${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/registry/`;
export const NATIVE_FEED_CONNECT_URL = `https://jio-dsp.visualstudio.com/DS-Assets/_artifacts/feed/${NATIVE_REGISTRY_FEED}/connect`;
export const NATIVE_PAT_CREATE_URL = 'https://jio-dsp.visualstudio.com/_usersSettings/tokens';

/** The CLI package name (lives on the native feed alongside @oneui/*). */
export const CLI_PACKAGE = '@oneui/create-native-app';

export type PackageManager = 'npm' | 'pnpm' | 'yarn' | 'bun';

/** How the caller supplied the PAT: a raw token, or one already base64-encoded. */
export type PatFormat = 'raw' | 'base64';

/** A valid npm/Expo project directory name. */
export function isValidProjectName(name: string): boolean {
  return /^[a-z0-9]([a-z0-9._-]*[a-z0-9])?$/i.test(name) && name.length <= 64;
}

function readIfExists(p: string): string {
  return existsSync(p) ? readFileSync(p, 'utf8') : '';
}

export interface NativeRegistryStatus {
  /** A real (non-placeholder) auth token for the native feed is present somewhere. */
  connected: boolean;
  userNpmrcPath: string;
  projectNpmrcPath: string;
  userNpmrcExists: boolean;
  projectNpmrcExists: boolean;
}

/**
 * Detect whether the machine can pull from the native feed (needed BEFORE `npx`,
 * since the CLI itself is hosted there). Scans the user `~/.npmrc` and the project
 * `.npmrc` for a real, non-placeholder `_password` on a native-feed line.
 */
export function detectNativeRegistry(projectRoot: string): NativeRegistryStatus {
  const userNpmrcPath = resolve(homedir(), '.npmrc');
  const projectNpmrcPath = resolve(projectRoot, '.npmrc');
  const userSrc = readIfExists(userNpmrcPath);
  const projectSrc = readIfExists(projectNpmrcPath);

  const hasRealAuth = (src: string): boolean =>
    src.split('\n').some((line) => {
      if (!line.includes(NATIVE_REGISTRY_FEED)) return false;
      const m = line.match(/:_password\s*=\s*(.*)$/);
      if (!m) return false;
      const v = m[1].trim();
      return !!v && !v.includes('BASE64') && !v.includes('PLACEHOLDER') && !v.includes('[');
    });

  return {
    connected: hasRealAuth(userSrc) || hasRealAuth(projectSrc),
    userNpmrcPath,
    projectNpmrcPath,
    userNpmrcExists: !!userSrc,
    projectNpmrcExists: !!projectSrc,
  };
}

/**
 * The `npx` command that fetches + runs the CLI from the private feed.
 * No `--registry` flag is needed: the project `.npmrc` we write (see
 * {@link buildProjectNpmrc}) sets the feed as the default `registry`, so npx
 * resolves the scoped CLI package against it. Auth also comes from that `.npmrc`.
 */
export function buildCreateCommand(projectName: string, pm: PackageManager): string {
  const pmFlag = pm === 'npm' ? '' : ` --use-${pm}`;
  return `npx ${CLI_PACKAGE} ${projectName}${pmFlag}`;
}

/**
 * AI-mode create command — skips the CLI's interactive PAT prompt entirely.
 *
 * The CLI's PAT prompt uses `process.stdin.setRawMode(true)` (raw-mode character
 * reads for the masked password input), which requires a real TTY. Piped stdin
 * (heredoc) causes `setRawMode` to throw "setRawMode is not supported on this
 * terminal", hanging or crashing the CLI. Instead we pass `--skip-pat --yes`:
 *   - `--skip-pat` writes a stub `.npmrc` (BASE64_ENCODED_PAT placeholder) inside
 *     the new project directory and skips the interactive prompt entirely.
 *   - `--yes` sets CI mode — skips all remaining interactive template/name prompts.
 * After the generator exits, the caller writes the REAL project `.npmrc` (via
 * {@link writeNewProjectNpmrc}) over the stub, injecting the actual auth token.
 */
export function buildCreateCommandSkipPat(projectName: string, pm: PackageManager): string {
  const pmFlag = pm === 'npm' ? '' : ` --use-${pm}`;
  return `npx ${CLI_PACKAGE} ${projectName}${pmFlag} --skip-pat --yes`;
}

/**
 * Normalize a caller-supplied PAT into the base64 form npm expects for `_password`.
 * `raw` tokens are base64-encoded; `base64` tokens are passed through (trimmed).
 */
export function encodePat(pat: string, format: PatFormat): string {
  const value = pat.trim();
  return format === 'raw' ? Buffer.from(value, 'utf8').toString('base64') : value;
}

/**
 * Full project-level `.npmrc` content: default `registry` pointed at the native
 * feed + `always-auth` + the Azure DevOps auth-token block (both the `/npm/registry/`
 * and `/npm/` path variants). `passwordBase64` is the base64-encoded PAT.
 */
export function buildProjectNpmrc(passwordBase64: string): string {
  const reg = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/registry/`;
  const regShort = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/`;
  const email = "npm requires email to be set but doesn't use the value";
  return [
    `registry=${NATIVE_REGISTRY_URL}`,
    `always-auth=true`,
    ``,
    '; begin auth token',
    `${reg}:username=JIO-DSP`,
    `${reg}:_password=${passwordBase64}`,
    `${reg}:email=${email}`,
    `${regShort}:username=JIO-DSP`,
    `${regShort}:_password=${passwordBase64}`,
    `${regShort}:email=${email}`,
    '; end auth token',
    ``,
  ].join('\n');
}

/**
 * A self-contained shell snippet the USER pastes into their own terminal to write the
 * feed `.npmrc` — the PAT never passes through the MCP or agent. It prompts for the
 * token format (raw|base64), reads the token with terminal echo OFF, base64-encodes a
 * raw token (`base64 | tr -d '\n'` works on macOS and Linux), and writes `.npmrc` in
 * the current directory.
 *
 * Each physical line is a complete statement (compound commands joined with `;`), so
 * pasting the whole block works directly in an interactive shell.
 */
export function buildNpmrcSetupScript(): string {
  const reg = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/registry/`;
  const regShort = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/`;
  const email = "npm requires email to be set but doesn't use the value";
  return [
    `printf 'Token format — type "raw" or "base64" [base64]: '; read FMT`,
    `printf 'Paste your PAT (input hidden): '; stty -echo; read PAT; stty echo; printf '\\n'`,
    `if [ "$FMT" = "raw" ]; then PW=$(printf '%s' "$PAT" | base64 | tr -d '\\n'); else PW="$PAT"; fi`,
    `cat > .npmrc <<EOF`,
    `registry=${NATIVE_REGISTRY_URL}`,
    `always-auth=true`,
    ``,
    `; begin auth token`,
    `${reg}:username=JIO-DSP`,
    `${reg}:_password=$PW`,
    `${reg}:email=${email}`,
    `${regShort}:username=JIO-DSP`,
    `${regShort}:_password=$PW`,
    `${regShort}:email=${email}`,
    `; end auth token`,
    `EOF`,
    `unset PAT PW FMT`,
    `echo "Wrote .npmrc"`,
  ].join('\n');
}

export interface WriteNpmrcResult {
  path: string;
  /** True when an `.npmrc` already existed at this path and was overwritten. */
  overwrote: boolean;
}

/**
 * Write the bootstrap `.npmrc` into `projectRoot` — the directory the user will run
 * `npx create-oneui-native-app` from. Uses a global `registry=` so that `npx` can
 * resolve the unscoped `create-oneui-native-app` package from the private feed. npm
 * walks parent dirs for `.npmrc`, so this file also covers the CLI's own `npm install`
 * inside the newly created app subdirectory.
 */
export function writeProjectNpmrc(projectRoot: string, passwordBase64: string): WriteNpmrcResult {
  const path = resolve(projectRoot, '.npmrc');
  const overwrote = existsSync(path);
  writeFileSync(path, buildProjectNpmrc(passwordBase64), 'utf8');
  return { path, overwrote };
}

/**
 * `.npmrc` content for the GENERATED app's own directory. Uses the scoped
 * `@oneui:registry=` form so only `@oneui/*` packages resolve against the private
 * feed — public packages (react-native, expo, etc.) still hit npm. Mirrors the exact
 * format written by the CLI's own `buildNpmrc()` when it runs interactively.
 */
export function buildNewProjectNpmrc(passwordBase64: string): string {
  const reg = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/registry/`;
  const regShort = `//${NATIVE_REGISTRY_HOST}/_packaging/${NATIVE_REGISTRY_FEED}/npm/`;
  const email = "npm requires email to be set but doesn't use the value";
  return [
    `@oneui:registry=${NATIVE_REGISTRY_URL}`,
    `always-auth=true`,
    ``,
    `; begin auth token`,
    `${reg}:username=JIO-DSP`,
    `${reg}:_password=${passwordBase64}`,
    `${reg}:email=${email}`,
    `${regShort}:username=JIO-DSP`,
    `${regShort}:_password=${passwordBase64}`,
    `${regShort}:email=${email}`,
    `; end auth token`,
    ``,
    `strict-ssl=false`,
    `legacy-peer-deps=true`,
    ``,
  ].join('\n');
}

/**
 * Write the scoped `.npmrc` into the newly generated project directory (overwrites
 * the `--skip-pat` stub). Call this AFTER `create-oneui-native-app` exits.
 */
export function writeNewProjectNpmrc(projectDir: string, passwordBase64: string): WriteNpmrcResult {
  const path = resolve(projectDir, '.npmrc');
  const overwrote = existsSync(path);
  writeFileSync(path, buildNewProjectNpmrc(passwordBase64), 'utf8');
  return { path, overwrote };
}

/**
 * Distinctive name for the STAGED project `.npmrc`. Deliberately NOT `.npmrc`
 * (so npm never reads it and it can't collide with the bootstrap file). The tool
 * writes the real auth here; the agent MOVES it into the generated app dir after
 * the generator runs — this keeps the base64 PAT entirely on disk and out of the
 * tool result / agent transcript.
 */
export const STAGED_NPMRC_NAME = '.oneui-native-npmrc';

/**
 * Sentinel shown in place of the base64 PAT in any human-readable preview — the
 * real token is written to disk ({@link writeStagedNewProjectNpmrc}), never echoed.
 */
export const REDACTED_PASSWORD = '[REDACTED — real token written to disk, not shown]';

/**
 * Write the real scoped project `.npmrc` to a STAGING file in `projectRoot`
 * (see {@link STAGED_NPMRC_NAME}). Returns its path so the caller can instruct a
 * single `mv` into the generated app dir once it exists — the PAT never appears
 * in the tool output.
 */
export function writeStagedNewProjectNpmrc(projectRoot: string, passwordBase64: string): WriteNpmrcResult {
  const path = resolve(projectRoot, STAGED_NPMRC_NAME);
  const overwrote = existsSync(path);
  writeFileSync(path, buildNewProjectNpmrc(passwordBase64), 'utf8');
  return { path, overwrote };
}
