/**
 * componentRecipes.ts
 *
 * Type definitions for the Component Recipe System.
 * Recipes provide a middle tier between raw tokens and full customization:
 * 3-6 constrained design decisions per component that deterministically
 * resolve to token overrides.
 */

/**
 * A single option within a recipe decision
 */
export interface RecipeOption {
  /** Machine-readable value (e.g., "accent") */
  value: string;
  /** Human-readable label (e.g., "Accent") */
  label: string;
  /** Description of what this option does */
  description: string;
}

/**
 * A design decision presented to the user as a radio group
 */
export interface RecipeDecision {
  /** Unique identifier (e.g., "boldFillStrategy") */
  id: string;
  /** Question-format label (e.g., "What color should the Bold button use?") */
  label: string;
  /** Why this decision matters */
  rationale: string;
  /** Category for optional grouping */
  category?:
    | 'color'
    | 'shape'
    | 'typography'
    | 'spacing'
    | 'stroke'
    | 'behavior'
    | 'layout'
    | 'content'
    | 'elevation';
  /** Available options */
  options: RecipeOption[];
  /** Default option value */
  defaultOption: string;
}

/**
 * A single token override generated by a recipe decision
 */
export interface RecipeTokenOverride {
  /** Token property name (e.g., "backgroundColor.bold") */
  tokenName: string;
  /** Token value to apply (e.g., "Neutral-FG-Bold") */
  value: string;
}

/**
 * Maps each decision+option to its token overrides.
 * Structure: decision ID -> option value -> overrides[]
 */
export type RecipeResolutionMap = Record<string, Record<string, RecipeTokenOverride[]>>;

/**
 * Complete recipe definition for a component
 */
export interface ComponentRecipeDefinition {
  /** Component name (e.g., "Button") */
  componentName: string;
  /** Ordered list of design decisions */
  decisions: RecipeDecision[];
  /** Resolution map: decision ID -> option value -> token overrides */
  resolutionMap: RecipeResolutionMap;
}

/**
 * Persisted recipe selections for a brand+component
 */
export interface RecipeSelections {
  /** Map of decision ID to selected option value */
  selections: Record<string, string>;
}

/**
 * Canonical family identifiers for brand-level component theming.
 *
 * Family themes sit above per-component recipes: a brand can express broad
 * intent once ("actions are pill and roomy") while individual components can
 * still override the result through their own recipes or raw token overrides.
 */
export type ComponentThemeFamilyId =
  | 'actions'
  | 'selection'
  | 'navigation'
  | 'inputs'
  | 'display'
  | 'cards';

/**
 * A component-specific target for one component theme family.
 *
 * Each target owns its own resolution map because the same family decision can
 * touch different token names per component (e.g. Input uses `height`, Stepper
 * uses `height-s` / `height-m` / `height-l`).
 */
export interface ComponentThemeTarget {
  /** Registry component name / CSS variable prefix (e.g. "Button", "InputField") */
  componentName: string;
  /** Decision resolution map for this component only */
  resolutionMap: RecipeResolutionMap;
  /**
   * Token names that receive the exact Shape token when the family's
   * `shapeLanguage` decision is set to `custom` (e.g. Button `['borderRadius']`,
   * Slider `['trackBorderRadius', 'knobBorderRadius']`).
   */
  shapeTokens?: string[];
  /**
   * Extra overrides emitted verbatim alongside a custom shape token (e.g. the
   * Radio dot radius `calc()` expressions that track the outer radius).
   */
  derivedShapeOverrides?: RecipeTokenOverride[];
  /**
   * Factory per-size baseline for rampable metrics, in Spacing tokens.
   * Keys mirror the component manifest: metric name -> size key -> token.
   * A size key of '' targets the base (size-less) token. When the family's
   * scale decision is `custom`, ramp offsets shift these baselines along
   * SPACING_LADDER and pinned cells override individual sizes.
   */
  metricBaselines?: Record<string, Record<string, string>>;
  /**
   * Metrics whose ramp/cell output must also be written to companion tokens
   * with the same size suffix (e.g. Button `paddingHorizontal` mirrors to
   * `paddingHorizontalStart` / `paddingHorizontalEnd`, matching the preset
   * scale maps).
   */
  metricMirrors?: Record<string, string[]>;
}

/**
 * Complete brand-level component theme family definition.
 */
export interface ComponentThemeFamilyDefinition {
  /** Stable family identifier */
  id: ComponentThemeFamilyId;
  /** Human-readable family label */
  label: string;
  /** Short product description for the editor UI */
  description: string;
  /** Ordered decisions shared by this family */
  decisions: RecipeDecision[];
  /** Component targets affected by the decisions */
  targets: ComponentThemeTarget[];
}

/**
 * Persisted selections for one brand-level component theme family.
 *
 * Besides plain `decisionId -> optionValue` entries, precision parameters use
 * reserved `:`-namespaced keys (no decision id contains `:`):
 *
 *   `{decisionId}:{param}`                  — decision parameter
 *                                             (e.g. `shapeLanguage:token` -> `Shape-3-5`,
 *                                              `controlScale:ramp:paddingHorizontal` -> `-1`)
 *   `{decisionId}:cell:{tokenName}.{size}`  — explicit per-size pinned cell
 *                                             (e.g. `controlScale:cell:paddingHorizontal.10` -> `Spacing-3-5`)
 *
 * Values are always strings (ramp offsets serialize as `"-1"`, `"2"`).
 */
export interface ComponentThemeSelections {
  familyId: ComponentThemeFamilyId;
  selections: Record<string, string>;
}

/**
 * Flat override emitted after resolving a family theme against a target.
 */
export interface ComponentThemeTokenOverride extends RecipeTokenOverride {
  componentName: string;
  familyId: ComponentThemeFamilyId;
  decisionId: string;
}
