// Monorepo-aware Metro config — mirrors apps/native-sample.
// See apps/native-sample/metro.config.js for the full rationale behind
// singleton pinning and hierarchical lookup.
const { getDefaultConfig } = require('expo/metro-config');
const path = require('node:path');
const fs = require('node:fs');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];

config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

config.resolver.unstable_enablePackageExports = true;

const SINGLETONS = ['react', 'react-dom', 'react-is', 'react-native', 'scheduler'];

const SINGLETON_ORIGIN = {};
for (const name of SINGLETONS) {
  try {
    const pkgJsonPath = require.resolve(`${name}/package.json`, { paths: [projectRoot] });
    const pkgRoot = path.dirname(pkgJsonPath);
    const parentNodeModules = path.dirname(pkgRoot);
    const fakeOrigin = path.join(parentNodeModules, '__metro-singleton-origin__.js');
    if (!fs.existsSync(fakeOrigin)) {
      try {
        fs.writeFileSync(fakeOrigin, '// metro singleton anchor — generated by metro.config.js\n');
      } catch {
        // best-effort
      }
    }
    SINGLETON_ORIGIN[name] = fakeOrigin;
  } catch {
    // optional singleton missing — fine
  }
}

const previousResolveRequest = config.resolver.resolveRequest;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  for (const name of SINGLETONS) {
    const origin = SINGLETON_ORIGIN[name];
    if (!origin) continue;
    if (moduleName === name || moduleName.startsWith(`${name}/`)) {
      return context.resolveRequest(
        { ...context, originModulePath: origin },
        moduleName,
        platform,
      );
    }
  }

  if (previousResolveRequest) {
    return previousResolveRequest(context, moduleName, platform);
  }

  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
