import 'dart:math' as math;

import '../engine/color_math.dart';
import '../engine/surface_engine.dart';
import '../utils/brand_dimension_bar_color.dart' show oklchToColor;
import 'jio_brand_snapshot.dart';

/// Greyscale gradient palette — same construction as `surfaceNew.test.ts` `buildGreyscalePalette`.
ColorPalette buildGreyscalePalette() {
  final palette = <int, String>{};
  for (var i = 0; i < kSurfaceSteps.length; i++) {
    final step = kSurfaceSteps[i];
    final t = i / (kSurfaceSteps.length - 1);
    final v = (t * 255).round();
    final hx = v.toRadixString(16).padLeft(2, '0');
    palette[step] = '#$hx$hx$hx';
  }
  return palette;
}

/// Warm ramp — same as TS `buildColoredPalette` in `surfaceNew.test.ts`.
ColorPalette buildColoredPalette() {
  final palette = <int, String>{};
  for (var i = 0; i < kSurfaceSteps.length; i++) {
    final step = kSurfaceSteps[i];
    final t = i / (kSurfaceSteps.length - 1);
    final r = (t * 300).round().clamp(0, 255);
    final g = (t * 200).round().clamp(0, 255);
    final b = (t * 150).round().clamp(0, 255);
    final hr = r.toRadixString(16).padLeft(2, '0');
    final hg = g.toRadixString(16).padLeft(2, '0');
    final hb = b.toRadixString(16).padLeft(2, '0');
    palette[step] = '#$hr$hg$hb';
  }
  return palette;
}

/// Jio default brand seed values — mirrors the live Convex `Jio` brand row.
///
/// `primaryHue` / `primaryChroma` come from `jio_brand_snapshot.dart`, which
/// is regenerated by `pnpm sync:jio-snapshot` against whichever Convex
/// deployment is configured in `.env.local`. The secondary values stay
/// hand-pinned (Convex doesn't currently expose them in `brands:list`).
///
/// Regenerate the snapshot whenever Jio's hue/chroma changes in Convex.
const double kJioDefaultPrimaryHue = kJioBrandSnapshotPrimaryHue;
const double kJioDefaultPrimaryChroma = kJioBrandSnapshotPrimaryChroma;
const double kJioDefaultSecondaryHue = 140;
const double kJioDefaultSecondaryChroma = 0.12;

/// 25-step OkLCH palette for the given hue/chroma — same anchor table used by
/// `primaryFallbackFromHueChroma`, mirrors web `fallbackHexForStep` in
/// `packages/shared/src/engine/compositionDesignMdExporter.ts`.
ColorPalette buildOklchPaletteForHue(double hue, double chroma) {
  const anchors = <List<num>>[
    [100, 96],
    [200, 90],
    [300, 84],
    [500, 62],
    [700, 48],
    [800, 42],
    [900, 36],
    [1500, 28],
    [1900, 18],
    [2500, 5],
  ];

  String stepHex(int step) {
    var loIdx = 0;
    for (var i = 0; i < anchors.length - 1; i++) {
      if (step >= anchors[i][0] && step <= anchors[i + 1][0]) {
        loIdx = i;
        break;
      }
      if (step >= anchors[i + 1][0]) loIdx = i + 1;
    }
    final lo = anchors[math.min(loIdx, anchors.length - 1)];
    final hi = anchors[math.min(loIdx + 1, anchors.length - 1)];
    final loStep = lo[0].toInt();
    final loL = lo[1].toDouble();
    final hiStep = hi[0].toInt();
    final hiL = hi[1].toDouble();
    final span = hiStep - loStep == 0 ? 1 : hiStep - loStep;
    final t = (step - loStep) / span;
    final L = loL + (hiL - loL) * t;

    final distFrom50 = (L - 50).abs() / 50.0;
    final taper = math.max(0.0, 1.0 - distFrom50 * distFrom50);
    final adjustedChroma = chroma * taper;

    final c = oklchToColor(L, adjustedChroma, hue % 360.0);
    final r = (c.r * 255.0).round().clamp(0, 255);
    final g = (c.g * 255.0).round().clamp(0, 255);
    final b = (c.b * 255.0).round().clamp(0, 255);
    return '#'
        '${r.toRadixString(16).padLeft(2, '0')}'
        '${g.toRadixString(16).padLeft(2, '0')}'
        '${b.toRadixString(16).padLeft(2, '0')}';
  }

  return {for (final step in kSurfaceSteps) step: stepHex(step)};
}

/// `ThemeConfig` flavoured like the Convex `jio-default` brand — used by offline
/// test harnesses and integration tests so on-device renders pick up Jio's
/// purple primary / green secondary instead of the neutral greyscale fallback.
ThemeConfig buildJioDefaultThemeConfig() {
  final grey = buildGreyscalePalette();
  final jioPrimary =
      buildOklchPaletteForHue(kJioDefaultPrimaryHue, kJioDefaultPrimaryChroma);
  final jioSecondary = buildOklchPaletteForHue(
      kJioDefaultSecondaryHue, kJioDefaultSecondaryChroma);
  return ThemeConfig(appearances: {
    'neutral': buildScaleDefinition('Neutral', grey, 1300),
    'primary': buildScaleDefinition('Brand', jioPrimary, 1500),
    'secondary': buildScaleDefinition('Secondary', jioSecondary, 1300),
    'sparkle': buildScaleDefinition('Sparkle', jioPrimary, 1500),
    'positive': buildScaleDefinition('Positive', grey, 1300),
    'negative': buildScaleDefinition('Negative', grey, 1300),
    'warning': buildScaleDefinition('Warning', grey, 1300),
    'informative': buildScaleDefinition('Informative', grey, 1300),
    'brand-bg': buildScaleDefinition('Brand-Bg', jioPrimary, 1500),
  });
}

/// Greyscale demo theme for Storybook when no Convex brand is loaded.
///
/// Includes every appearance [SingleTextButton] stories showcase (web parity:
/// `SingleTextButton.stories.tsx` lists 11 roles). Distinct [baseStep] per role
/// so greyscale ramps read as separate swatches in the Appearances grid.
///
/// Primary [baseStep] is mid-dark (600): on a light page parent (2500), bold
/// surfaces read charcoal-like with nested bold inversion — same pattern as web/RN.
ThemeConfig buildStorybookDemoThemeConfig() {
  final grey = buildGreyscalePalette();
  return ThemeConfig(appearances: {
    'neutral': buildScaleDefinition('Neutral', grey, 1300),
    'primary': buildScaleDefinition('Brand', grey, 600),
    'secondary': buildScaleDefinition('Secondary', grey, 900),
    'tertiary': buildScaleDefinition('Tertiary', grey, 1100),
    'quaternary': buildScaleDefinition('Quaternary', grey, 1500),
    'sparkle': buildScaleDefinition('Sparkle', grey, 700),
    'brand-bg': buildScaleDefinition('Brand-Bg', grey, 500),
    'positive': buildScaleDefinition('Positive', grey, 1300),
    'negative': buildScaleDefinition('Negative', grey, 1300),
    'warning': buildScaleDefinition('Warning', grey, 1300),
    'informative': buildScaleDefinition('Informative', grey, 1300),
  });
}
