/**
 * Virtual-module source generators. Each bundler plugin (vite/webpack/esbuild)
 * has its own resolve+load semantics, but the JS source they emit for the
 * virtual modules is identical and lives here.
 *
 * Three virtual modules:
 *   - `virtual:oneui-brands` — manifest with one lazy loader per brand/sub-brand
 *   - `virtual:oneui-brand/<slug>` — CSS string + sidecar objects for one brand
 *   - `virtual:oneui-sub-brand/<parent>::<sub>` — delta CSS + sub-brand themeConfig
 */

import { existsSync, readFileSync } from 'node:fs';
import {
  brandingPath,
  cssPath,
  decorationsPath,
  fontsPath,
  materialsPath,
  themeCssPath,
  themeThemeConfigPath,
  themeConfigPath,
} from './paths';
import type { Branding, CacheManifest, ResolvedOptions } from './types';

export const VIRT_INDEX = 'virtual:oneui-brands';
export const VIRT_BRAND_PREFIX = 'virtual:oneui-brand/';
export const VIRT_SUB_BRAND_PREFIX = 'virtual:oneui-sub-brand/';

/** Package subpaths plugins must alias to the same index module as `VIRT_INDEX`. */
export const BRAND_LOADER_MODULE_IDS = [
  '@oneui/ui/brand-loader',
  '@jds4/oneui-react/brand-loader',
] as const;

export function isBrandLoaderModuleId(id: string): boolean {
  return (BRAND_LOADER_MODULE_IDS as readonly string[]).includes(id);
}

export function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function readCachedAsset<T>(file: string, parse: (s: string) => T, fallback: T): T {
  if (!existsSync(file)) return fallback;
  try {
    return parse(readFileSync(file, 'utf8'));
  } catch {
    return fallback;
  }
}

const parseJsonArray = (s: string): unknown[] => {
  const v: unknown = JSON.parse(s);
  return Array.isArray(v) ? v : [];
};
const parseJsonAny = (s: string): unknown => JSON.parse(s) as unknown;
const parseBranding = (s: string): Branding => {
  const parsed = JSON.parse(s) as Partial<Branding>;
  return {
    brandName: typeof parsed.brandName === 'string' ? parsed.brandName : '',
    logoSvg: parsed.logoSvg ?? null,
  };
};

/**
 * Source for `virtual:oneui-brands` — lazy import map + manifest entries the
 * BrandProvider reads to discover available brands/sub-brands.
 *
 * `themeImportSpec` lets each bundler decide its own import-spec format
 * (e.g. webpack uses a virtual-file path, esbuild uses a namespace, vite
 * uses the bare `virtual:` identifier).
 */
export function generateIndexModuleSource(
  resolved: ResolvedOptions,
  manifest: CacheManifest,
  brandImportSpec: (slug: string) => string,
  themeImportSpec: (parent: string, sub: string) => string,
): string {
  const slugs = Object.keys(resolved.brands);

  const loaders = slugs
    .map(
      (slug) =>
        `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(brandImportSpec(slug))}),`,
    )
    .join('\n');

  const subEntries: string[] = [];
  const subMeta: string[] = [];
  const themeSlugs: string[] = [];
  for (const slug of slugs) {
    for (const themeSlug of resolved.brands[slug].themes) {
      const key = `${slug}::${themeSlug}`;
      themeSlugs.push(key);
      subEntries.push(
        `  ${JSON.stringify(key)}: () => import(${JSON.stringify(themeImportSpec(slug, themeSlug))}),`,
      );
      const m = manifest.brands[slug]?.themes?.[themeSlug];
      subMeta.push(
        `  ${JSON.stringify(key)}: ${JSON.stringify({
          parent: slug,
          sub: themeSlug,
          bytes: m?.bytes ?? 0,
          hash: m?.hash ?? '',
        })},`,
      );
    }
  }

  const meta = slugs
    .map((slug) => {
      const m = manifest.brands[slug];
      return `  ${JSON.stringify(slug)}: ${JSON.stringify({
        version: m?.version ?? resolved.brands[slug].version,
        bytes: m?.bytes ?? 0,
        hash: m?.hash ?? '',
        themes: resolved.brands[slug].themes,
      })},`;
    })
    .join('\n');

  return `// Generated by @oneui/cdn
export const brands = {
${loaders}
};
export const themes = {
${subEntries.join('\n')}
};
export const manifest = {
${meta}
};
export const themeManifest = {
${subMeta.join('\n')}
};
export const availableBrands = ${JSON.stringify(slugs)};
export const availableThemes = ${JSON.stringify(themeSlugs)};
`;
}

/** Source for `virtual:oneui-brand/<slug>` — brand CSS + sidecar exports. */
export function generateBrandModuleSource(slug: string, cacheDir: string): string {
  const cssFile = cssPath(cacheDir, slug);
  const css = existsSync(cssFile) ? readFileSync(cssFile, 'utf8') : '';
  const decorations = readCachedAsset<unknown[]>(decorationsPath(cacheDir, slug), parseJsonArray, []);
  const themeConfig = readCachedAsset<unknown | null>(
    themeConfigPath(cacheDir, slug),
    parseJsonAny,
    null,
  );
  const materialsFoundation = readCachedAsset<unknown | null>(
    materialsPath(cacheDir, slug),
    parseJsonAny,
    null,
  );
  const branding = readCachedAsset<Branding>(brandingPath(cacheDir, slug), parseBranding, {
    brandName: slug,
    logoSvg: null,
  });
  const safeBranding: Branding =
    branding.brandName.length > 0 ? branding : { ...branding, brandName: slug };
  const fontsFoundation = readCachedAsset<unknown | null>(
    fontsPath(cacheDir, slug),
    parseJsonAny,
    null,
  );

  return `// Generated by @oneui/cdn — brand: ${slug}
export default \`${escapeForTemplateLiteral(css)}\`;
export const decorations = ${JSON.stringify(decorations)};
export const themeConfig = ${JSON.stringify(themeConfig)};
export const materialsFoundation = ${JSON.stringify(materialsFoundation)};
export const branding = ${JSON.stringify(safeBranding)};
export const fontsFoundation = ${JSON.stringify(fontsFoundation)};
`;
}

/** Source for `virtual:oneui-sub-brand/<parent>::<sub>` — delta CSS + themeConfig. */
export function generateThemeModuleSource(
  parentSlug: string,
  themeSlug: string,
  cacheDir: string,
): string {
  const cssFile = themeCssPath(cacheDir, parentSlug, themeSlug);
  const css = existsSync(cssFile) ? readFileSync(cssFile, 'utf8') : '';
  const themeConfig = readCachedAsset<unknown | null>(
    themeThemeConfigPath(cacheDir, parentSlug, themeSlug),
    parseJsonAny,
    null,
  );
  return `// Generated by @oneui/cdn — sub-brand: ${parentSlug}/${themeSlug}
export default \`${escapeForTemplateLiteral(css)}\`;
export const themeConfig = ${JSON.stringify(themeConfig)};
`;
}
