// Monorepo-aware Metro config for Expo.
//
// pnpm + React Native has two known sharp edges in this workspace:
//
//  1. React duplication: with `node-linker=hoisted` plus `react` listed
//     in @oneui/ui-native's devDependencies, pnpm produces TWO physical
//     react directories — `node_modules/react` (a real folder, hoisted
//     for the app) and `packages/ui-native/node_modules/react` (a
//     symlink into `.pnpm/react@18.3.1/node_modules/react`). Metro
//     identifies modules by file path, so it bundles both copies and
//     `OneUINativeThemeProvider` ends up calling `useMemo` on a React
//     instance that never had its dispatcher initialised → the classic
//     "Cannot read property 'useMemo' of null" / "Invalid hook call".
//
//  2. Wrong-version hoisting: an earlier attempt set
//     `disableHierarchicalLookup: true` to solve (1). That fixed React
//     but forced *every* nested `require` to resolve from the root
//     `node_modules`, where pnpm hoists `whatwg-url@16` for jsdom.
//     `whatwg-url@16` touches `SharedArrayBuffer.prototype` at module
//     init, which Hermes does not implement → bundle crash.
//
// Strategy:
//   - Watch the workspace root so package edits hot-reload.
//   - Add the workspace root to `nodeModulesPaths` for shared lookups.
//   - Leave hierarchical lookup ENABLED (default) so libraries like
//     `node-fetch` keep resolving their own nested `whatwg-url@5`.
//   - Pin React's runtime singletons via `resolveRequest`: any bare or
//     subpath import of these packages is rewritten to resolve from a
//     synthetic origin inside the canonical workspace-root copy, so
//     Metro always lands on the same physical folder.
//   - `unstable_enablePackageExports: true` so subpath exports like
//     `@oneui/ui-native/showcase/Button` resolve.
const { getDefaultConfig } = require('expo/metro-config');
const path = require('node:path');
const fs = require('node:fs');
// NOTE: withNativeWind is intentionally NOT applied here.
// NativeWind 4's CSS interop transformer triggers a blocking Tailwind
// compilation watcher at Metro startup and requires react-native-worklets
// (Reanimated 4 only). We use Reanimated 3, so NativeWind's metro
// integration is incompatible. The @oneui/ui-rnr package uses inline
// `style` objects for all brand-aware colours; Tailwind utility strings
// from `className=` are silently stripped by RN without the transformer,
// which is fine because the only classes used there are layout/sizing
// helpers that are fully replicated via the inline styles anyway.

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];

config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

config.resolver.unstable_enablePackageExports = true;

// Web-only icon loaders use dynamic `import()` (Vite). Block so Metro never
// parses them if a barrel import accidentally pulls `packages/ui/src/icons/Icon.tsx`.
const iconLoadersPattern = new RegExp(
  `${path.resolve(workspaceRoot, 'packages/ui/src/icons/iconLoaders')}\\.ts$`,
);
config.resolver.blockList = [
  ...(Array.isArray(config.resolver.blockList) ? config.resolver.blockList : []),
  iconLoadersPattern,
];

// Resolve each singleton via the project's `require.resolve` (always lands on
// the workspace-root copy because that's the highest-priority hoisted dir).
// We then build a synthetic origin file path INSIDE that singleton's parent
// `node_modules`, so when Metro calls hierarchical resolution from this
// origin it walks straight into the canonical singleton folder — never the
// nested `.pnpm` symlinks under `packages/*/node_modules`.
const SINGLETONS = ['react', 'react-dom', 'react-is', 'react-native', 'scheduler'];

const SINGLETON_ORIGIN = {};
for (const name of SINGLETONS) {
  try {
    const pkgJsonPath = require.resolve(`${name}/package.json`, { paths: [projectRoot] });
    const pkgRoot = path.dirname(pkgJsonPath);
    // pkgRoot looks like .../node_modules/<name>. The synthetic origin sits
    // one level above the singleton so hierarchical lookup finds <name>.
    const parentNodeModules = path.dirname(pkgRoot);
    const fakeOrigin = path.join(parentNodeModules, '__metro-singleton-origin__.js');
    if (!fs.existsSync(fakeOrigin)) {
      try {
        fs.writeFileSync(fakeOrigin, '// metro singleton anchor — generated by metro.config.js\n');
      } catch {
        // best-effort; resolver still works because Metro only needs the path
      }
    }
    SINGLETON_ORIGIN[name] = fakeOrigin;
  } catch {
    // Missing optional singleton (e.g. react-dom on a pure RN install) is fine.
  }
}

const previousResolveRequest = config.resolver.resolveRequest;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  for (const name of SINGLETONS) {
    const origin = SINGLETON_ORIGIN[name];
    if (!origin) continue;
    if (moduleName === name || moduleName.startsWith(`${name}/`)) {
      return context.resolveRequest(
        { ...context, originModulePath: origin },
        moduleName,
        platform
      );
    }
  }

  if (previousResolveRequest) {
    return previousResolveRequest(context, moduleName, platform);
  }

  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
