/**
 * Central registry of stable test IDs.
 *
 * Keeping selectors in one place gives Playwright suites a single source of
 * truth and avoids brittle string duplication across the app.
 */
export const TESTIDS = {
  layout: {
    shell: 'app-shell',
    header: 'site-header',
    headerSearch: 'header-search',
    headerSearchSubmit: 'header-search-submit',
    primaryNav: 'primary-nav',
    mobileNav: 'mobile-bottom-nav',
    footer: 'site-footer',
    skipLink: 'skip-to-content',
    main: 'main-content',
    cartBadge: 'header-cart-badge',
    notificationBadge: 'header-notification-badge',
    themeToggle: 'theme-toggle',
    avatar: 'header-avatar',
    demoBack: 'demo-back-to-catalog',
  },
  home: {
    page: 'page-home',
    hero: 'home-hero',
    heroCta: 'home-hero-cta',
    serviceSearch: 'home-service-search',
    themeSettings: 'home-theme-settings',
    quickAction: (id: string) => `home-quick-action-${id}`,
    serviceCard: (id: string) => `home-service-card-${id}`,
    offerCard: (id: string) => `home-offer-card-${id}`,
  },
  plans: {
    page: 'page-plans',
    filterChips: 'plans-filter-chips',
    filterChip: (id: string) => `plans-filter-${id}`,
    sortToggle: 'plans-sort-toggle',
    card: (id: string) => `plan-card-${id}`,
    rechargeBtn: (id: string) => `plan-recharge-${id}`,
    compareToggle: (id: string) => `plan-compare-${id}`,
    compareBtn: 'plans-compare-btn',
    compareDialog: 'plans-compare-dialog',
  },
  recharge: {
    modal: 'recharge-modal',
    mobileInput: 'recharge-mobile-input',
    planSummary: 'recharge-plan-summary',
    confirmBtn: 'recharge-confirm-btn',
    cancelBtn: 'recharge-cancel-btn',
    successDialog: 'recharge-success-dialog',
    successClose: 'recharge-success-close',
  },
  devices: {
    page: 'page-devices',
    search: 'devices-search',
    categoryChips: 'devices-category-chips',
    categoryChip: (id: string) => `devices-category-${id}`,
    card: (id: string) => `device-card-${id}`,
    wishlistBtn: (id: string) => `device-wishlist-${id}`,
    stepper: (id: string) => `device-stepper-${id}`,
    addBtn: (id: string) => `device-add-${id}`,
    detailsBtn: (id: string) => `device-details-${id}`,
    detailsModal: 'device-details-modal',
    pagination: 'devices-pagination',
    empty: 'devices-empty',
  },
  support: {
    page: 'page-support',
    search: 'support-search',
    categoryTab: (id: string) => `support-tab-${id}`,
    faqItem: (id: string) => `support-faq-${id}`,
    contactBtn: 'support-contact-btn',
    contactModal: 'support-contact-modal',
    contactSubmit: 'support-contact-submit',
    contactSuccess: 'support-contact-success',
  },
  account: {
    page: 'page-account',
    tab: (id: string) => `account-tab-${id}`,
    editProfileBtn: 'account-edit-profile',
    profileModal: 'account-profile-modal',
    profileName: 'account-profile-name',
    profileSave: 'account-profile-save',
    notifySwitch: 'account-notify-switch',
    smsSwitch: 'account-sms-switch',
    emailSwitch: 'account-email-switch',
    themeOption: (id: string) => `account-theme-${id}`,
    componentInfoSwitch: 'account-component-info-switch',
    languageRadio: (id: string) => `account-language-${id}`,
    dataSlider: 'account-data-slider',
    savedPlan: (id: string) => `account-saved-plan-${id}`,
    saveSuccess: 'account-save-success',
  },
  notifications: {
    page: 'page-notifications',
    item: (id: string) => `notification-${id}`,
    markRead: (id: string) => `notification-read-${id}`,
    markAllRead: 'notifications-mark-all',
    filterChips: 'notifications-filter',
    filterChip: (id: string) => `notifications-filter-${id}`,
    empty: 'notifications-empty',
  },
  rewards: {
    page: 'page-rewards',
    couponCard: (id: string) => `coupon-card-${id}`,
    copyBtn: (id: string) => `coupon-copy-${id}`,
    redeemBtn: (id: string) => `reward-redeem-${id}`,
    rewardCard: (id: string) => `reward-card-${id}`,
    pointsMeter: 'rewards-points-meter',
  },
  accessibility: {
    page: 'page-accessibility',
    keyboardDemo: 'a11y-keyboard-demo',
    focusDemo: 'a11y-focus-demo',
    focusTrapModal: 'a11y-focus-modal',
    srDemo: 'a11y-sr-demo',
    liveRegion: 'a11y-live-region',
    announceBtn: 'a11y-announce-btn',
  },
  coverage: {
    page: 'page-coverage',
    componentTable: 'coverage-component-table',
    componentRow: (name: string) => `coverage-row-${name.toLowerCase()}`,
    pageTable: 'coverage-page-table',
    missingList: 'coverage-missing-list',
    propertyPanel: 'coverage-property-panel',
    filterInput: 'coverage-filter-input',
  },
  showcase: {
    page: 'page-showcase',
    modal: 'showcase-modal',
    modalOpen: 'showcase-modal-open',
  },
  qaPlayground: {
    page: 'page-qa-playground',
    search: 'qa-playground-search',
    categoryFilter: 'qa-playground-category-filter',
    statusFilter: 'qa-playground-status-filter',
    card: (slug: string) => `qa-playground-card-${slug}`,
    detailPage: 'page-qa-component',
    scenarios: (slug: string) => `qa-scenarios-${slug}`,
    coveragePage: 'page-qa-coverage',
    coverageTable: 'qa-coverage-table',
    coverageRow: (slug: string) => `qa-coverage-row-${slug}`,
  },
} as const
