/** AUTO-GENERATED by scripts/exportBrandData.ts — do not edit. */
import type { BrandData, ThemeData } from '@oneui/ui-native/theme';

// Base brand snapshots — { foundation, components }
import brand_banana_base from '../../brand-data/banana/latest.json';
import brand_jio_base from '../../brand-data/jio/latest.json';
import brand_native_test_base from '../../brand-data/native-test/latest.json';
import brand_one_ui_theme_base from '../../brand-data/one-ui-theme/latest.json';
import brand_reliance_base from '../../brand-data/reliance/latest.json';
import brand_swadesh_base from '../../brand-data/swadesh/latest.json';
import brand_tira_base from '../../brand-data/tira/latest.json';

// Sub-brand theme deltas — raw JSON files: { themeData: {...}, colorScales?: [...] }
import brand_jio_agriculture from '../../brand-data/jio/sub-brands/agriculture/latest.json';
import brand_jio_business from '../../brand-data/jio/sub-brands/business/latest.json';
import brand_jio_finance from '../../brand-data/jio/sub-brands/finance/latest.json';
import brand_jio_home from '../../brand-data/jio/sub-brands/home/latest.json';
import brand_jio_jioaicloud from '../../brand-data/jio/sub-brands/jioaicloud/latest.json';
import brand_jio_jioblackrock from '../../brand-data/jio/sub-brands/jioblackrock/latest.json';
import brand_jio_jioblast from '../../brand-data/jio/sub-brands/jioblast/latest.json';
import brand_jio_jiobusiness from '../../brand-data/jio/sub-brands/jiobusiness/latest.json';
import brand_jio_jiocx from '../../brand-data/jio/sub-brands/jiocx/latest.json';
import brand_jio_jiofinance_new from '../../brand-data/jio/sub-brands/jiofinance-new/latest.json';
import brand_jio_jiofit from '../../brand-data/jio/sub-brands/jiofit/latest.json';
import brand_jio_jiogames from '../../brand-data/jio/sub-brands/jiogames/latest.json';
import brand_jio_jiohealthhub from '../../brand-data/jio/sub-brands/jiohealthhub/latest.json';
import brand_jio_jiohome from '../../brand-data/jio/sub-brands/jiohome/latest.json';
import brand_jio_jiomart from '../../brand-data/jio/sub-brands/jiomart/latest.json';
import brand_jio_jiomessages from '../../brand-data/jio/sub-brands/jiomessages/latest.json';
import brand_jio_jiomobile from '../../brand-data/jio/sub-brands/jiomobile/latest.json';
import brand_jio_jionews from '../../brand-data/jio/sub-brands/jionews/latest.json';
import brand_jio_jiopc from '../../brand-data/jio/sub-brands/jiopc/latest.json';
import brand_jio_jiosaavn from '../../brand-data/jio/sub-brands/jiosaavn/latest.json';
import brand_jio_jiosarthi from '../../brand-data/jio/sub-brands/jiosarthi/latest.json';
import brand_jio_jiostar from '../../brand-data/jio/sub-brands/jiostar/latest.json';
import brand_jio_jiothings from '../../brand-data/jio/sub-brands/jiothings/latest.json';
import brand_jio_jiotranslate from '../../brand-data/jio/sub-brands/jiotranslate/latest.json';
import brand_jio_jiotv from '../../brand-data/jio/sub-brands/jiotv/latest.json';
import brand_jio_jiowave from '../../brand-data/jio/sub-brands/jiowave/latest.json';
import brand_jio_jioworkspace from '../../brand-data/jio/sub-brands/jioworkspace/latest.json';
import brand_jio_mobile from '../../brand-data/jio/sub-brands/mobile/latest.json';
import brand_jio_myjio from '../../brand-data/jio/sub-brands/myjio/latest.json';
import brand_jio_shopping from '../../brand-data/jio/sub-brands/shopping/latest.json';

function slugify(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '-');
}

/** Maps brand name → base BrandData snapshot. */
const OFFLINE_BRAND_DATA: Record<string, BrandData> = {
  'banana': brand_banana_base as BrandData,
  'jio': brand_jio_base as BrandData,
  'native-test': brand_native_test_base as BrandData,
  'one-ui-theme': brand_one_ui_theme_base as BrandData,
  'reliance': brand_reliance_base as BrandData,
  'swadesh': brand_swadesh_base as BrandData,
  'tira': brand_tira_base as BrandData,
};

/** Maps brandName::variantName → ThemeData (raw sub-brand JSON — provider normalises internally). */
const OFFLINE_THEME_DATA: Record<string, ThemeData> = {
  'jio::agriculture': brand_jio_agriculture as ThemeData,
  'jio::business': brand_jio_business as ThemeData,
  'jio::finance': brand_jio_finance as ThemeData,
  'jio::home': brand_jio_home as ThemeData,
  'jio::jioaicloud': brand_jio_jioaicloud as ThemeData,
  'jio::jioblackrock': brand_jio_jioblackrock as ThemeData,
  'jio::jioblast': brand_jio_jioblast as ThemeData,
  'jio::jiobusiness': brand_jio_jiobusiness as ThemeData,
  'jio::jiocx': brand_jio_jiocx as ThemeData,
  'jio::jiofinance-new': brand_jio_jiofinance_new as ThemeData,
  'jio::jiofit': brand_jio_jiofit as ThemeData,
  'jio::jiogames': brand_jio_jiogames as ThemeData,
  'jio::jiohealthhub': brand_jio_jiohealthhub as ThemeData,
  'jio::jiohome': brand_jio_jiohome as ThemeData,
  'jio::jiomart': brand_jio_jiomart as ThemeData,
  'jio::jiomessages': brand_jio_jiomessages as ThemeData,
  'jio::jiomobile': brand_jio_jiomobile as ThemeData,
  'jio::jionews': brand_jio_jionews as ThemeData,
  'jio::jiopc': brand_jio_jiopc as ThemeData,
  'jio::jiosaavn': brand_jio_jiosaavn as ThemeData,
  'jio::jiosarthi': brand_jio_jiosarthi as ThemeData,
  'jio::jiostar': brand_jio_jiostar as ThemeData,
  'jio::jiothings': brand_jio_jiothings as ThemeData,
  'jio::jiotranslate': brand_jio_jiotranslate as ThemeData,
  'jio::jiotv': brand_jio_jiotv as ThemeData,
  'jio::jiowave': brand_jio_jiowave as ThemeData,
  'jio::jioworkspace': brand_jio_jioworkspace as ThemeData,
  'jio::mobile': brand_jio_mobile as ThemeData,
  'jio::myjio': brand_jio_myjio as ThemeData,
  'jio::shopping': brand_jio_shopping as ThemeData,
};

/**
 * Load the base brand snapshot (foundation + components) by display name.
 * Returns `undefined` if no snapshot exists — run `export:brands` to generate.
 */
export function getOfflineBrandData(brandName: string): BrandData | undefined {
  return OFFLINE_BRAND_DATA[slugify(brandName).toLowerCase()];
}

/**
 * Load a sub-brand theme delta by brand name + variant name.
 * The raw JSON is passed directly to OneUIBrandProvider which normalises it.
 * Returns `undefined` if no theme file exists for the given variant.
 */
export function getOfflineThemeData(brandName: string, variantName: string): ThemeData | undefined {
  const key = `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;
  return OFFLINE_THEME_DATA[key];
}
