import type {
  AppNotification,
  Coupon,
  Device,
  FaqItem,
  HomeOffer,
  Plan,
  Reward,
} from './types'

export const PLANS: Plan[] = [
  {
    id: 'p-239',
    name: 'Smart Saver',
    price: 239,
    validityDays: 28,
    dataPerDay: 1.5,
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioTV', 'JioCinema', 'JioCloud'],
    category: 'popular',
    tag: 'Most popular',
  },
  {
    id: 'p-299',
    name: 'Everyday Plus',
    price: 299,
    validityDays: 28,
    dataPerDay: 2,
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioTV', 'JioCinema', 'JioCloud', 'JioSecurity'],
    category: 'popular',
  },
  {
    id: 'p-179',
    name: 'Data Lite',
    price: 179,
    validityDays: 28,
    dataPerDay: 1,
    calls: 'Unlimited',
    sms: '300 total',
    benefits: ['JioTV', 'JioCinema'],
    category: 'value',
  },
  {
    id: 'p-666',
    name: 'Unlimited Pro',
    price: 666,
    validityDays: 84,
    dataPerDay: 2,
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioTV', 'JioCinema', 'JioCloud', 'JioSecurity'],
    category: 'unlimited',
    tag: 'Best value',
  },
  {
    id: 'p-3199',
    name: 'Annual Max',
    price: 3199,
    validityDays: 365,
    dataPerDay: 2.5,
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioTV', 'JioCinema', 'JioCloud', 'JioSecurity', 'Netflix Mobile'],
    category: 'annual',
    tag: '12 months',
  },
  {
    id: 'p-449',
    name: 'Data Booster',
    price: 449,
    validityDays: 28,
    dataPerDay: 3,
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['JioTV', 'JioCinema', 'JioCloud'],
    category: 'data',
  },
]

export const DEVICES: Device[] = [
  {
    id: 'd-jiophone',
    name: 'JioPhone Next',
    brand: 'Jio',
    price: 5999,
    mrp: 7499,
    rating: 4.2,
    ratingCount: 1820,
    image: 'https://picsum.photos/seed/jiophone/400/400',
    category: 'smartphone',
    highlights: ['4G VoLTE', 'Android Go', '13MP camera'],
    inStock: true,
  },
  {
    id: 'd-galaxy',
    name: 'Galaxy A55 5G',
    brand: 'Samsung',
    price: 38999,
    mrp: 42999,
    rating: 4.5,
    ratingCount: 4310,
    image: 'https://picsum.photos/seed/galaxy/400/400',
    category: 'smartphone',
    highlights: ['5G', '120Hz AMOLED', '50MP OIS'],
    inStock: true,
  },
  {
    id: 'd-tabs9',
    name: 'Galaxy Tab S9',
    brand: 'Samsung',
    price: 72999,
    mrp: 79999,
    rating: 4.6,
    ratingCount: 980,
    image: 'https://picsum.photos/seed/tabs9/400/400',
    category: 'tablet',
    highlights: ['11" AMOLED', 'S Pen', 'Snapdragon 8 Gen 2'],
    inStock: true,
  },
  {
    id: 'd-jiofiber',
    name: 'JioFiber Router',
    brand: 'Jio',
    price: 2499,
    mrp: 2999,
    rating: 4.1,
    ratingCount: 2640,
    image: 'https://picsum.photos/seed/router/400/400',
    category: 'router',
    highlights: ['Dual band', 'Up to 1 Gbps', '4 LAN ports'],
    inStock: true,
  },
  {
    id: 'd-jiofiber-tv',
    name: 'JioTV+ Set Top Box',
    brand: 'Jio',
    price: 3499,
    mrp: 3999,
    rating: 4.3,
    ratingCount: 1510,
    image: 'https://picsum.photos/seed/jiotv/400/400',
    category: 'tv',
    highlights: ['4K HDR', 'Voice remote', '500+ channels'],
    inStock: true,
  },
  {
    id: 'd-iphone',
    name: 'iPhone 15',
    brand: 'Apple',
    price: 79900,
    mrp: 79900,
    rating: 4.7,
    ratingCount: 8920,
    image: 'https://picsum.photos/seed/iphone15/400/400',
    category: 'smartphone',
    highlights: ['A16 Bionic', 'Dynamic Island', '48MP'],
    inStock: false,
  },
  {
    id: 'd-ipad',
    name: 'iPad Air 11"',
    brand: 'Apple',
    price: 59900,
    mrp: 64900,
    rating: 4.6,
    ratingCount: 1240,
    image: 'https://picsum.photos/seed/ipadair/400/400',
    category: 'tablet',
    highlights: ['M2 chip', 'Liquid Retina', 'Apple Pencil Pro'],
    inStock: true,
  },
  {
    id: 'd-mesh',
    name: 'JioMesh Extender',
    brand: 'Jio',
    price: 1999,
    mrp: 2499,
    rating: 4.0,
    ratingCount: 760,
    image: 'https://picsum.photos/seed/mesh/400/400',
    category: 'router',
    highlights: ['Whole-home WiFi', 'Plug & play', 'App control'],
    inStock: true,
  },
  {
    id: 'd-fireTv',
    name: 'Jio 4K Smart TV 43"',
    brand: 'Jio',
    price: 24999,
    mrp: 31999,
    rating: 4.2,
    ratingCount: 3110,
    image: 'https://picsum.photos/seed/smarttv/400/400',
    category: 'tv',
    highlights: ['4K UHD', 'Dolby Audio', 'Built-in apps'],
    inStock: true,
  },
]

export const FAQS: FaqItem[] = [
  {
    id: 'faq-recharge-1',
    category: 'recharge',
    question: 'How do I recharge my Jio number?',
    answer:
      'Go to Mobile Plans, pick a plan, enter your registered mobile number and confirm. You can pay via UPI, cards, or JioMart wallet.',
  },
  {
    id: 'faq-recharge-2',
    category: 'recharge',
    question: 'When does my recharge get activated?',
    answer: 'Most recharges activate instantly. In rare cases it can take up to 30 minutes.',
  },
  {
    id: 'faq-devices-1',
    category: 'devices',
    question: 'What is the delivery time for devices?',
    answer: 'Standard delivery is 2–4 business days. Express delivery is available in select pincodes.',
  },
  {
    id: 'faq-devices-2',
    category: 'devices',
    question: 'Can I return a device?',
    answer: 'Devices can be returned within 7 days of delivery if unused and in original packaging.',
  },
  {
    id: 'faq-account-1',
    category: 'account',
    question: 'How do I update my profile details?',
    answer: 'Open My Account, go to the Profile tab and tap Edit profile to update your name, email and phone.',
  },
  {
    id: 'faq-account-2',
    category: 'account',
    question: 'How do I reset my password?',
    answer: 'Use the Account & login help on this page to trigger an OTP-based password reset.',
  },
  {
    id: 'faq-network-1',
    category: 'network',
    question: 'Why is my data slow?',
    answer: 'Check your daily data balance, toggle airplane mode, or restart the device. Fair-usage throttling may apply after your daily quota.',
  },
  {
    id: 'faq-network-2',
    category: 'network',
    question: 'How do I check network coverage?',
    answer: 'Use the coverage map in Support to verify 4G/5G availability in your area.',
  },
]

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-1',
    kind: 'offer',
    title: '₹50 off your next recharge',
    message: 'Use code JIO50 before the end of the month.',
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    read: false,
  },
  {
    id: 'n-2',
    kind: 'recharge',
    title: 'Recharge successful',
    message: 'Your Smart Saver ₹239 plan is now active.',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    read: false,
  },
  {
    id: 'n-3',
    kind: 'account',
    title: 'New login detected',
    message: 'A new device signed in to your account.',
    timestamp: new Date(Date.now() - 26 * 3600000).toISOString(),
    read: true,
  },
  {
    id: 'n-4',
    kind: 'system',
    title: 'Scheduled maintenance',
    message: 'Network upgrades in your area on Sunday 2–4 AM.',
    timestamp: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    read: true,
  },
  {
    id: 'n-5',
    kind: 'offer',
    title: 'Galaxy A55 price drop',
    message: 'Now ₹38,999. Limited period offer.',
    timestamp: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    read: false,
  },
]

export const COUPONS: Coupon[] = [
  {
    id: 'c-jio50',
    code: 'JIO50',
    title: '₹50 off recharge',
    description: 'On plans of ₹239 and above',
    expiry: '30 Jun 2026',
    category: 'recharge',
  },
  {
    id: 'c-device10',
    code: 'DEVICE10',
    title: '10% off devices',
    description: 'Max discount ₹3,000 on smartphones',
    expiry: '15 Jul 2026',
    category: 'devices',
  },
  {
    id: 'c-fiberfree',
    code: 'FIBERFREE',
    title: 'Free installation',
    description: 'On new JioFiber connections',
    expiry: '31 Dec 2026',
    category: 'fiber',
  },
]

export const REWARDS: Reward[] = [
  { id: 'r-cashback', title: '₹100 cashback', description: 'Redeem for 500 points', points: 500, icon: 'star' },
  { id: 'r-data', title: '5 GB data add-on', description: 'Redeem for 300 points', points: 300, icon: 'smartphone' },
  { id: 'r-ott', title: '1 month JioCinema Premium', description: 'Redeem for 800 points', points: 800, icon: 'tv' },
  { id: 'r-voucher', title: '₹200 device voucher', description: 'Redeem for 1000 points', points: 1000, icon: 'bookmark' },
]

export const HOME_OFFERS: HomeOffer[] = COUPONS.map((coupon) => ({
  id: coupon.id.replace(/^c-/, ''),
  title: coupon.title,
  tag:
    coupon.code === 'JIO50'
      ? `Use ${coupon.code}`
      : coupon.category === 'devices'
        ? 'Limited time'
        : 'New users',
  appearance:
    coupon.category === 'recharge'
      ? 'positive'
      : coupon.category === 'devices'
        ? 'informative'
        : 'sparkle',
}))
