/**
 * Jio web alpha component catalog.
 *
 * This is the package-level source of truth for the first publishable alpha:
 * web components only, validated against the Jio brand. Components not listed
 * as `alpha` remain importable if exported elsewhere, but are not part of the
 * supported alpha adoption surface.
 */

export type JioAlphaSupportStatus = 'alpha' | 'experimental' | 'internal';

export interface JioAlphaComponentCatalogEntry {
  name: string;
  status: JioAlphaSupportStatus;
  importPath?: string;
  storyPath?: string;
  docsPath?: string;
  surfaceAware: boolean;
  multiAccent: boolean;
  notes?: string;
}

const componentPath = (folder: string) => `packages/ui/src/components/${folder}`;
const componentImport = (folder: string) => `@oneui/ui/components/${folder}`;
const componentDocs = (slug: string) => `docs/components/generated/${slug}.docs.json`;

export const JIO_WEB_ALPHA_COMPONENTS = [
  {
    name: 'Surface',
    status: 'alpha',
    importPath: componentImport('Surface'),
    storyPath: `${componentPath('Surface')}/Surface.stories.tsx`,
    docsPath: componentDocs('surface'),
    surfaceAware: true,
    multiAccent: false,
    notes: 'Required wrapper for non-default backgrounds and surface context.',
  },
  {
    name: 'Text',
    status: 'alpha',
    importPath: componentImport('Text'),
    storyPath: `${componentPath('Text')}/Text.stories.tsx`,
    docsPath: componentDocs('text'),
    surfaceAware: true,
    multiAccent: true,
    notes: 'Typography primitive for generated copy hierarchy and surface-aware text colour.',
  },
  {
    name: 'Button',
    status: 'alpha',
    importPath: componentImport('Button'),
    storyPath: `${componentPath('Button')}/Button.stories.tsx`,
    docsPath: componentDocs('button'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'IconButton',
    status: 'alpha',
    importPath: componentImport('IconButton'),
    storyPath: `${componentPath('IconButton')}/IconButton.stories.tsx`,
    docsPath: componentDocs('iconbutton'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'LinkButton',
    status: 'alpha',
    importPath: componentImport('LinkButton'),
    storyPath: `${componentPath('LinkButton')}/LinkButton.stories.tsx`,
    docsPath: componentDocs('linkbutton'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'FAB',
    status: 'alpha',
    importPath: componentImport('FAB'),
    storyPath: `${componentPath('FAB')}/FAB.stories.tsx`,
    docsPath: componentDocs('fab'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'Badge',
    status: 'alpha',
    importPath: componentImport('Badge'),
    storyPath: `${componentPath('Badge')}/Badge.stories.tsx`,
    docsPath: componentDocs('badge'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Avatar',
    status: 'alpha',
    importPath: componentImport('Avatar'),
    storyPath: `${componentPath('Avatar')}/Avatar.stories.tsx`,
    docsPath: componentDocs('avatar'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Chip',
    status: 'alpha',
    importPath: componentImport('Chip'),
    storyPath: `${componentPath('Chip')}/Chip.stories.tsx`,
    docsPath: componentDocs('chip'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'ChipGroup',
    status: 'alpha',
    importPath: componentImport('ChipGroup'),
    storyPath: `${componentPath('ChipGroup')}/ChipGroup.stories.tsx`,
    docsPath: componentDocs('chipgroup'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'InputField',
    status: 'alpha',
    importPath: componentImport('Input'),
    storyPath: `${componentPath('Input')}/Input.stories.tsx`,
    docsPath: componentDocs('inputfield'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Checkbox',
    status: 'alpha',
    importPath: componentImport('Checkbox'),
    storyPath: `${componentPath('Checkbox')}/Checkbox.stories.tsx`,
    docsPath: componentDocs('checkbox'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Radio',
    status: 'alpha',
    importPath: componentImport('Radio'),
    storyPath: `${componentPath('Radio')}/Radio.stories.tsx`,
    docsPath: componentDocs('radio'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Switch',
    status: 'alpha',
    importPath: componentImport('Switch'),
    storyPath: `${componentPath('Switch')}/Switch.stories.tsx`,
    docsPath: componentDocs('switch'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Slider',
    status: 'alpha',
    importPath: componentImport('Slider'),
    storyPath: `${componentPath('Slider')}/Slider.stories.tsx`,
    docsPath: componentDocs('slider'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Tabs',
    status: 'alpha',
    importPath: componentImport('Tabs'),
    storyPath: `${componentPath('Tabs')}/Tabs.stories.tsx`,
    docsPath: componentDocs('tabs'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'ListItem',
    status: 'alpha',
    importPath: componentImport('ListItem'),
    storyPath: `${componentPath('ListItem')}/ListItem.stories.tsx`,
    docsPath: componentDocs('listitem'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'ListItemGroup',
    status: 'alpha',
    importPath: componentImport('ListItemGroup'),
    storyPath: `${componentPath('ListItemGroup')}/ListItemGroup.stories.tsx`,
    docsPath: componentDocs('listitemgroup'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'Divider',
    status: 'alpha',
    importPath: componentImport('Divider'),
    storyPath: `${componentPath('Divider')}/Divider.stories.tsx`,
    docsPath: componentDocs('divider'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Image',
    status: 'alpha',
    importPath: componentImport('Image'),
    storyPath: `${componentPath('Image')}/Image.stories.tsx`,
    docsPath: componentDocs('image'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'Icon',
    status: 'alpha',
    importPath: componentImport('Icon'),
    storyPath: `${componentPath('Icon')}/Icon.stories.tsx`,
    docsPath: componentDocs('icon'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'Logo',
    status: 'alpha',
    importPath: componentImport('Logo'),
    storyPath: `${componentPath('Logo')}/Logo.stories.tsx`,
    docsPath: componentDocs('logo'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'Spinner',
    status: 'alpha',
    importPath: componentImport('Spinner'),
    storyPath: `${componentPath('Spinner')}/Spinner.stories.tsx`,
    docsPath: componentDocs('spinner'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'Tooltip',
    status: 'alpha',
    importPath: componentImport('Tooltip'),
    storyPath: `${componentPath('Tooltip')}/Tooltip.stories.tsx`,
    docsPath: componentDocs('tooltip'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'PaginationDots',
    status: 'alpha',
    importPath: componentImport('PaginationDots'),
    storyPath: `${componentPath('PaginationDots')}/PaginationDots.stories.tsx`,
    docsPath: componentDocs('paginationdots'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'Container',
    status: 'alpha',
    importPath: componentImport('Container'),
    storyPath: `${componentPath('Container')}/Container.stories.tsx`,
    docsPath: componentDocs('container'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'Grid',
    status: 'alpha',
    importPath: componentImport('Grid'),
    storyPath: `${componentPath('Grid')}/Grid.stories.tsx`,
    docsPath: componentDocs('grid'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'Stepper',
    status: 'alpha',
    importPath: componentImport('Stepper'),
    storyPath: `${componentPath('Stepper')}/Stepper.stories.tsx`,
    docsPath: componentDocs('stepper'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'CounterBadge',
    status: 'alpha',
    importPath: componentImport('CounterBadge'),
    storyPath: `${componentPath('CounterBadge')}/CounterBadge.stories.tsx`,
    docsPath: componentDocs('counterbadge'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'IndicatorBadge',
    status: 'alpha',
    importPath: componentImport('IndicatorBadge'),
    storyPath: `${componentPath('IndicatorBadge')}/IndicatorBadge.stories.tsx`,
    docsPath: componentDocs('indicatorbadge'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'BottomNavigation',
    status: 'alpha',
    importPath: componentImport('BottomNavigation'),
    storyPath: `${componentPath('BottomNavigation')}/BottomNavigation.stories.tsx`,
    docsPath: componentDocs('bottomnavigation'),
    surfaceAware: true,
    multiAccent: true,
  },
  {
    name: 'WebHeader',
    status: 'alpha',
    importPath: componentImport('WebHeader'),
    storyPath: `${componentPath('WebHeader')}/WebHeader.stories.tsx`,
    docsPath: componentDocs('webheader'),
    surfaceAware: false,
    multiAccent: false,
  },
  {
    name: 'PrimaryNav',
    status: 'alpha',
    importPath: componentImport('WebHeader'),
    storyPath: `${componentPath('WebHeader')}/WebHeader.stories.tsx`,
    docsPath: componentDocs('webheader'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'HeaderItem',
    status: 'alpha',
    importPath: componentImport('WebHeader'),
    storyPath: `${componentPath('WebHeader')}/WebHeader.stories.tsx`,
    docsPath: componentDocs('webheader'),
    surfaceAware: true,
    multiAccent: false,
  },
  {
    name: 'Carousel',
    status: 'alpha',
    importPath: componentImport('Carousel'),
    storyPath: `${componentPath('Carousel')}/Carousel.stories.tsx`,
    docsPath: componentDocs('carousel'),
    surfaceAware: true,
    multiAccent: true,
    notes: 'Alpha once recipe, metadata registry entry, generated docs, and slug checks pass.',
  },
] as const satisfies readonly JioAlphaComponentCatalogEntry[];

export const JIO_WEB_ALPHA_EXPERIMENTAL_COMPONENTS = [
  'Accordion',
  'AlertDialog',
  'CheckboxGroup',
  'CircularProgressIndicator',
  'LinearProgressIndicator',
  'Collapsible',
  'Dialog',
  'Fieldset',
  'Form',
  'Link',
  'Menu',
  'Meter',
  'NavigationMenu',
  'NumberField',
  'Popover',
  'PreviewCard',
  'Progress',
  'ScrollArea',
  'SegmentedControl',
  'SelectableButton',
  'SelectableIconButton',
  'SelectableSingleTextButton',
  'SingleTextButton',
  'Select',
  'Separator',
  'Toast',
  'Toggle',
  'ToggleGroup',
  'Toolbar',
  'TouchSlider',
] as const;

export const JIO_WEB_ALPHA_INTERNAL_COMPONENTS = [
  'ChatComposer',
  'ChatSurface',
  'ComponentHarness',
  'GridOverlay',
  'Platform',
] as const;

export const JIO_WEB_ALPHA_COMPONENT_NAMES = JIO_WEB_ALPHA_COMPONENTS.map(
  (component) => component.name,
);

export function isJioWebAlphaComponent(name: string): boolean {
  return (JIO_WEB_ALPHA_COMPONENT_NAMES as readonly string[]).includes(name);
}
