/**
 * exportBrandData.ts
 *
 * Fetches every brand + sub-brand from Convex and writes a trimmed `BrandData`
 * JSON file for each variant under `brand-data/<BrandName>/`.
 *
 * Output contains only fields consumed by `@oneui/ui-native`:
 *   foundationToNativeTheme → buildNativeTheme (foundation)
 *   OneUIBrandProvider (components)
 *
 *   brand-data/
 *     Jio/
 *       base.json          ← { foundation, components }
 *       JioMart.json       ← { foundation (sub-brand accents applied), components }
 *       MyJio.json
 *       …
 *     Tira/
 *       base.json
 *     …
 *
 * Usage:
 *   pnpm tsx apps/native-sample/scripts/exportBrandData.ts
 *
 * The Convex deployment URL is read from EXPO_PUBLIC_CONVEX_URL (same .env
 * used by the Expo app).
 */

import { ConvexHttpClient } from 'convex/browser';
import { api } from '@oneui/convex';
import { applySubBrandAccentsToFoundation } from '@oneui/shared';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { trimFoundation } from './trimBrandFoundation';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const OUT_DIR = path.resolve(__dirname, '../brand-data');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function slugify(name: string): string {
  return name.replace(/[^a-zA-Z0-9-_]/g, '-');
}

function lookupKey(brandName: string, variantName = 'base'): string {
  return `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;
}

function toImportIdentifier(brandSlug: string, variantSlug: string): string {
  return `brand_${slugify(brandSlug).replace(/-/g, '_')}_${slugify(variantSlug).replace(/-/g, '_')}`;
}

/**
 * Metro requires static JSON imports. After export, emit a lookup module that
 * maps brand name + variant → bundled BrandData snapshot.
 */
async function generateOfflineManifest(): Promise<void> {
  const manifestPath = path.resolve(__dirname, '../src/brand-data/offlineBrandData.generated.ts');
  const entries: Array<{
    importName: string;
    brandSlug: string;
    variantSlug: string;
    importPath: string;
    key: string;
  }> = [];

  const brandDirs = await fs.readdir(OUT_DIR, { withFileTypes: true });
  for (const brandDir of brandDirs) {
    if (!brandDir.isDirectory()) continue;
    const brandSlug = brandDir.name;
    const files = await fs.readdir(path.join(OUT_DIR, brandSlug));
    for (const file of files) {
      if (!file.endsWith('.json')) continue;
      const variantSlug = file.replace(/\.json$/, '');
      entries.push({
        importName: toImportIdentifier(brandSlug, variantSlug),
        brandSlug,
        variantSlug,
        importPath: `../../brand-data/${brandSlug}/${file}`,
        key: lookupKey(brandSlug, variantSlug),
      });
    }
  }

  entries.sort((a, b) => a.key.localeCompare(b.key));

  const lines = [
    '/** AUTO-GENERATED by scripts/exportBrandData.ts — do not edit. */',
    "import type { BrandData } from '@oneui/ui-native/theme';",
    '',
    ...entries.map((entry) => `import ${entry.importName} from '${entry.importPath}';`),
    '',
    "function slugify(name: string): string {",
    "  return name.replace(/[^a-zA-Z0-9-_]/g, '-');",
    '}',
    '',
    'function lookupKey(brandName: string, variantName = \'base\'): string {',
    '  return `${slugify(brandName).toLowerCase()}::${slugify(variantName).toLowerCase()}`;',
    '}',
    '',
    'const OFFLINE_BRAND_DATA: Record<string, BrandData> = {',
    ...entries.map((entry) => `  '${entry.key}': ${entry.importName} as BrandData,`),
    '};',
    '',
    '/** Every exported (brand, variant) pair — drives the offline brand picker. */',
    'export const OFFLINE_BRANDS: ReadonlyArray<{ brand: string; variant: string }> = [',
    ...entries.map((entry) => `  { brand: '${entry.brandSlug}', variant: '${entry.variantSlug}' },`),
    '];',
    '',
    '/** Load exported brand snapshot by display name (e.g. "Tira", "Jio") and variant ("base" or sub-brand name). */',
    'export function getOfflineBrandData(brandName: string, variantName = \'base\'): BrandData | undefined {',
    '  return OFFLINE_BRAND_DATA[lookupKey(brandName, variantName)];',
    '}',
    '',
  ];

  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, lines.join('\n'), 'utf-8');
  console.log(`  ✓ src/brand-data/offlineBrandData.generated.ts (${entries.length} variant(s))`);
}

function resolveConvexUrl(): string | undefined {
  return (
    process.env.EXPO_PUBLIC_CONVEX_URL ??
    process.env.NEXT_PUBLIC_CONVEX_URL ??
    process.env.CONVEX_URL
  );
}

/** Load `.env.local` from the app dir and repo root (works regardless of cwd). */
async function loadEnvFiles(): Promise<void> {
  const candidates = [
    path.resolve(__dirname, '../.env.local'),
    path.resolve(__dirname, '../../../.env.local'),
  ];

  for (const envPath of candidates) {
    try {
      const content = await fs.readFile(envPath, 'utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
        if (!process.env[key]) process.env[key] = value;
      }
    } catch {
      // optional — file may not exist
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  await loadEnvFiles();

  const convexUrl = resolveConvexUrl();
  if (!convexUrl) {
    console.error(
      'Error: Convex URL is not set.\n' +
        '  Set EXPO_PUBLIC_CONVEX_URL in apps/native-sample/.env.local\n' +
        '  Run: pnpm --filter @oneui/native-sample export:brands',
    );
    process.exit(1);
  }

  const client = new ConvexHttpClient(convexUrl);

  console.log(`Connecting to ${convexUrl}`);

  const brands = await client.query(api.brands.list);
  console.log(`Found ${brands.length} brand(s): ${brands.map((b) => b.name).join(', ')}`);

  for (const brand of brands) {
    const brandSlug = slugify(brand.name);
    const brandDir = path.join(OUT_DIR, brandSlug);
    await fs.mkdir(brandDir, { recursive: true });

    // Fetch brand data
    const [foundation, components, subBrands] = await Promise.all([
      client.query(api.foundations.getBrandOverviewData, { brandId: brand._id }),
      client.query(api.componentTokenOverrides.getAllBrandComponentData, { brandId: brand._id }),
      client.query(api.subBrandConfigs.getByParentBrand, { parentBrandId: brand._id }),
    ]);

    // Base variant — trim after fetch; components pass through unchanged
    const baseData = {
      foundation: trimFoundation(foundation),
      components,
    };
    const basePath = path.join(brandDir, 'base.json');
    await fs.writeFile(basePath, JSON.stringify(baseData, null, 2), 'utf-8');
    console.log(`  ✓ ${brandSlug}/base.json`);

    // Sub-brand variants — merge accents on full foundation, then trim
    for (const sub of subBrands) {
      const resolvedFoundation = applySubBrandAccentsToFoundation(
        foundation as Record<string, unknown> | null | undefined,
        sub,
      );
      const subData = {
        foundation: trimFoundation(resolvedFoundation),
        components,
      };
      const subSlug = slugify(sub.name);
      const subPath = path.join(brandDir, `${subSlug}.json`);
      await fs.writeFile(subPath, JSON.stringify(subData, null, 2), 'utf-8');
      console.log(`  ✓ ${brandSlug}/${subSlug}.json`);
    }
  }

  await generateOfflineManifest();

  console.log(`\nDone — ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
