/**
 * Jio Icons Initialization
 *
 * Registers the Jio icon loader and catalog with the UI package
 * so that IconBrowser and Icon components can load Jio icons.
 *
 * Icons are loaded from a single pre-built JSON data file (jio-icons-data.json)
 * instead of 1,622 individual dynamic imports. The data file is generated by
 * `scripts/build-jio-icon-data.ts` and served from /public.
 */

import React from 'react';
import {
  setJioIconLoader,
  setJioIconCatalog,
  getJioIconLoader,
} from '@oneui/ui/icons/IconContext';
import type { IconComponent } from '@oneui/shared';
import { initIconSetLoaders } from './initIconSetLoaders';
import { initJioIcons as initTreeShakeableJioIcons } from '@oneui/icons-jio';
import { initTiraIcons, tiraIconCatalog } from '@oneui/icons-tira';
import { setIconSetCatalog } from '@oneui/ui/icons/IconContext';

interface JioIconData {
  /** viewBox */
  v: string;
  /** SVG inner HTML (path elements) */
  d: string;
}

// Cache for constructed icon components
const jioIconCache: Record<string, IconComponent> = {};

// Track initialization state
let initialized = false;

// Lazy icon data loading — fetched once when first icon is requested
let iconDataPromise: Promise<Record<string, JioIconData>> | null = null;
let iconDataCache: Record<string, JioIconData> | null = null;

// Lazy catalog loading — deferred until needed (icon browser page)
let catalogPromise: Promise<string[]> | null = null;

/**
 * Fetch the parsed Jio icon catalog. Module-level cached so repeated
 * calls share one fetch — the SandpackCanvas reuses this rather than
 * issuing a duplicate fetch for the iframe bridge.
 */
export function getJioIconData(): Promise<Record<string, JioIconData>> {
  if (iconDataCache) return Promise.resolve(iconDataCache);
  if (!iconDataPromise) {
    iconDataPromise = fetch('/jio-icons-data.json')
      .then((res) => res.json())
      .then((data: Record<string, JioIconData>) => {
        iconDataCache = data;
        return data;
      });
  }
  return iconDataPromise;
}

function getIconCatalog(): Promise<string[]> {
  if (!catalogPromise) {
    catalogPromise = import('../Jio_Icons/icon-catalog.json').then(
      (m) => (m.default as { searchIndex: string[] }).searchIndex
    );
  }
  return catalogPromise;
}

/**
 * Create a React component from SVG data
 */
function createIconComponent(data: JioIconData): IconComponent {
  const SvgIcon = React.forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>(
    (props, ref) =>
      React.createElement('svg', {
        ref,
        xmlns: 'http://www.w3.org/2000/svg',
        fill: 'none',
        viewBox: data.v,
        ...props,
        dangerouslySetInnerHTML: { __html: data.d },
      })
  );
  SvgIcon.displayName = 'JioIcon';
  return SvgIcon as unknown as IconComponent;
}

/**
 * Load a Jio icon by name from the pre-built data bundle
 */
async function loadJioIcon(name: string): Promise<IconComponent | null> {
  // Check component cache first
  if (jioIconCache[name]) {
    return jioIconCache[name];
  }

  try {
    const data = await getJioIconData();
    const iconData = data[name];
    if (!iconData) return null;

    const component = createIconComponent(iconData);
    jioIconCache[name] = component;
    return component;
  } catch (error) {
    console.error(`[JioIcons] Failed to load icon: ${name}`, error);
    return null;
  }
}

/**
 * Check if Jio icons have been initialized
 */
export function isJioIconsInitialized(): boolean {
  return initialized || getJioIconLoader() !== null;
}

/**
 * Initialize Jio icons
 * Call this once at app startup
 * Safe to call multiple times - will only initialize once
 *
 * Registers the icon loader synchronously (needed for Icon rendering).
 * The icon data and catalog are loaded lazily on first use.
 */
export function initJioIcons(): void {
  // External icon-pack loaders live in initIconSetLoaders (module promise
  // cache + phosphor name fallbacks) — single registration path.
  initIconSetLoaders();

  // Prevent double initialization
  if (initialized) {
    return;
  }

  // Register the tree-shakeable jio icon loader and catalog immediately
  initTreeShakeableJioIcons();
  initTiraIcons();
  setIconSetCatalog('tira', tiraIconCatalog);

  initialized = true;
}

/**
 * Preload the Jio icon catalog when a page actually needs browsing/search.
 * Safe to call multiple times.
 */
export async function ensureJioIconCatalogLoaded(): Promise<void> {
  // Catalog is pre-registered by @oneui/icons-jio, no fetch needed.
}

export default initJioIcons;
