import 'demo_product_catalog.dart';

/// Beauty catalog inspired by [Tira Beauty](https://www.tirabeauty.com/).
final kTiraProducts = <DemoProduct>[
  DemoProduct(
    id: 'benefit-mascara',
    brandName: 'Benefit Cosmetics',
    name: 'Benefit Badgal Bounce Fuller Looking Volumizing Mascara',
    price: 949,
    mrp: 999,
    category: 'makeup',
    packLabel: '1 pc',
    rating: 4.0,
    reviewCount: 87,
    offerLabel: '1 Offer',
    badgeLabel: 'ONLY ON TIRA',
    bestseller: true,
  ),
  DemoProduct(
    id: 'cerave-cleanser',
    brandName: 'CeraVe',
    name: 'CeraVe Foaming Cleanser For Normal To Oily Skin',
    price: 599,
    mrp: 699,
    category: 'skin',
    packLabel: '236 ml',
    rating: 4.5,
    reviewCount: 312,
    offerLabel: '1 Offer · Free gifts',
    badgeLabel: 'DERM APPROVED',
    bestseller: true,
  ),
  DemoProduct(
    id: 'clayco-scrub',
    brandName: 'ClayCo.',
    name: 'ClayCo. Matcha Enzyme Scrub For Dead Skin Removal (70 g)',
    price: 799,
    mrp: 899,
    category: 'skin',
    packLabel: '70 g',
    rating: 3.9,
    reviewCount: 1800,
    offerLabel: '1 Offer · Free gifts',
    badgeLabel: 'NEW',
    bestseller: true,
  ),
  DemoProduct(
    id: 'boj-sun',
    brandName: 'Beauty of Joseon',
    name: 'Beauty of Joseon Relief Sun SPF 50+ PA++++',
    price: 799,
    mrp: 950,
    category: 'skin',
    packLabel: '50 ml',
    rating: 4.6,
    reviewCount: 540,
    offerLabel: '1 Offer',
    badgeLabel: 'NEW',
  ),
  DemoProduct(
    id: 'cosrx-snail',
    brandName: 'COSRX',
    name: 'COSRX Advanced Snail 96 Mucin Power Essence',
    price: 1299,
    mrp: 1450,
    category: 'skin',
    packLabel: '100 ml',
    rating: 4.7,
    reviewCount: 920,
    offerLabel: '1 Offer',
    badgeLabel: 'DERM APPROVED',
  ),
  DemoProduct(
    id: 'ordinary-toner',
    brandName: 'The Ordinary',
    name: 'The Ordinary Glycolic Acid 7% Toning Solution',
    price: 890,
    mrp: 990,
    category: 'skin',
    packLabel: '240 ml',
    rating: 4.3,
    reviewCount: 410,
    offerLabel: '1 Offer',
  ),
  DemoProduct(
    id: 'huda-lip',
    brandName: 'Huda Beauty',
    name: 'Huda Beauty Power Bullet Matte Lipstick',
    price: 1999,
    mrp: 2200,
    category: 'makeup',
    packLabel: '1 pc',
    rating: 4.4,
    reviewCount: 156,
    offerLabel: '1 Offer',
    badgeLabel: 'ONLY ON TIRA',
  ),
  DemoProduct(
    id: 'fenty-gloss',
    brandName: 'FENTY BEAUTY',
    name: 'FENTY BEAUTY Gloss Bomb Universal Lip Luminizer',
    price: 1699,
    mrp: 1899,
    category: 'makeup',
    packLabel: '1 pc',
    rating: 4.8,
    reviewCount: 203,
    offerLabel: '1 Offer · Free gifts',
  ),
  DemoProduct(
    id: 'plum-mist',
    brandName: 'Plum',
    name: 'Plum BodyLovin Hawaiian Rumba Body Mist',
    price: 525,
    mrp: 575,
    category: 'fragrance',
    packLabel: '150 ml',
    rating: 4.2,
    reviewCount: 88,
    offerLabel: '1 Offer',
  ),
  DemoProduct(
    id: 'minimalist-vitc',
    brandName: 'Minimalist',
    name: 'Minimalist 10% Vitamin C Face Serum',
    price: 599,
    mrp: 699,
    category: 'skin',
    packLabel: '30 ml',
    rating: 4.1,
    reviewCount: 670,
    offerLabel: '1 Offer',
    inStock: false,
  ),
  DemoProduct(
    id: 'dr-althea',
    brandName: 'Dr.Althea',
    name: 'Dr.Althea 345 Relief Cream',
    price: 649,
    mrp: 799,
    category: 'skin',
    packLabel: '50 ml',
    rating: 4.5,
    reviewCount: 245,
    offerLabel: '1 Offer',
    badgeLabel: 'DERM APPROVED',
  ),
  DemoProduct(
    id: 'axis-y-serum',
    brandName: 'Axis-Y',
    name: 'Axis-Y Dark Spot Correcting Glow Serum',
    price: 899,
    mrp: 1050,
    category: 'skin',
    packLabel: '50 ml',
    rating: 4.6,
    reviewCount: 390,
    offerLabel: '1 Offer · Free gifts',
  ),
];

/// Horizontal category strip on the Tira home page.
const kTiraCategoryNav = <String>[
  "What's New",
  'Makeup',
  'Skin',
  'Hair',
  'Fragrance',
  'Men',
  'Bath & Body',
  'Tools & Appliances',
  'Mom & Baby',
  'Wellness',
  'Minis',
  'Homegrown',
  'Gifts',
];

const kTiraHeaderNav = <String>[
  'Brands',
  'Tira Red',
  'Offers',
  'Top Shelf',
  'For You',
];

final kTiraJustDropped = kTiraProducts.take(6).toList();

final kTiraDermPicks = kTiraProducts
    .where((p) => p.badgeLabel == 'DERM APPROVED' || p.category == 'skin')
    .take(6)
    .toList();
