/**
 * Avatar.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Avatar/Avatar.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Avatar';

const meta = {
  title: "Components/Media/Avatar",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const AvatarDefault: Story = {
  name: "Default",
  render: () => <Showcase.AvatarDefault />,
};

export const AvatarVariants: Story = {
  name: "Variants",
  render: () => <Showcase.AvatarVariants />,
};

export const AvatarAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.AvatarAttentionLevels />,
};

export const AvatarSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.AvatarSizes />,
};

export const AvatarStates: Story = {
  name: "States",
  render: () => <Showcase.AvatarStates />,
};

export const AvatarImageFallback: Story = {
  name: "Image Fallback",
  render: () => <Showcase.AvatarImageFallback />,
};

export const AvatarAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.AvatarAppearances />,
};

export const AvatarThemes: Story = {
  name: "Themes",
  render: () => <Showcase.AvatarThemes />,
};

export const AvatarSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.AvatarSurfaceContext />,
};

export const AvatarWithIcons: Story = {
  name: "With Icons",
  render: () => <Showcase.AvatarWithIcons />,
};

export const AvatarResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.AvatarResponsive />,
};

export const AvatarPlayground: Story = {
  name: "Playground",
  render: () => <Showcase.AvatarPlayground />,
};
