/**
 * Badge.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Badge/Badge.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Badge';

const meta = {
  title: "Components/Status/Badge",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const BadgeDefault: Story = {
  name: "Default",
  render: () => <Showcase.BadgeDefault />,
};

export const BadgeVariants: Story = {
  name: "Variants",
  render: () => <Showcase.BadgeVariants />,
};

export const BadgeSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.BadgeSizes />,
};

export const BadgeWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.BadgeWithSlots />,
};

export const BadgeSizesWithSlots: Story = {
  name: "Sizes With Slots",
  render: () => <Showcase.BadgeSizesWithSlots />,
};

export const BadgeAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.BadgeAppearances />,
};

export const BadgeThemes: Story = {
  name: "Themes",
  render: () => <Showcase.BadgeThemes />,
};

export const BadgeSlotAdaptation: Story = {
  name: "Slot Adaptation",
  render: () => <Showcase.BadgeSlotAdaptation />,
};

export const BadgeResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.BadgeResponsive />,
};

export const BadgeFigmaSlotMatrix: Story = {
  name: "Figma Slot Matrix",
  render: () => <Showcase.BadgeFigmaSlotMatrix />,
};

export const BadgeSurfaceContextBold: Story = {
  name: "Surface Context Bold",
  render: () => <Showcase.BadgeSurfaceContextBold />,
};

export const BadgeSurfaceContextSubtle: Story = {
  name: "Surface Context Subtle",
  render: () => <Showcase.BadgeSurfaceContextSubtle />,
};

export const BadgeSurfaceContextAllModes: Story = {
  name: "Surface Context All Modes",
  render: () => <Showcase.BadgeSurfaceContextAllModes />,
};

export const BadgeAccessibilityWithSlots: Story = {
  name: "Accessibility With Slots",
  render: () => <Showcase.BadgeAccessibilityWithSlots />,
};
