/**
 * BottomNavigationItem.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/BottomNavigationItem/BottomNavigationItem.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/BottomNavigationItem';

const meta = {
  title: "Components/Navigation/BottomNavigationItem",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const BottomNavigationItemDefault: Story = {
  name: "Default",
  render: () => <Showcase.BottomNavigationItemDefault />,
};

export const BottomNavigationItemLabelTypes: Story = {
  name: "Label Types",
  render: () => <Showcase.BottomNavigationItemLabelTypes />,
};

export const BottomNavigationItemStates: Story = {
  name: "States",
  render: () => <Showcase.BottomNavigationItemStates />,
};

export const BottomNavigationItemWithIcons: Story = {
  name: "With Icons",
  render: () => <Showcase.BottomNavigationItemWithIcons />,
};

export const BottomNavigationItemIconOnly: Story = {
  name: "Icon Only",
  render: () => <Showcase.BottomNavigationItemIconOnly />,
};
