/**
 * BottomNavigation.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/BottomNavigation/BottomNavigation.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/BottomNavigation';

const meta = {
  title: "Components/Navigation/BottomNavigation",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const BottomNavigationDefault: Story = {
  name: "Default",
  render: () => <Showcase.BottomNavigationDefault />,
};

export const BottomNavigationLabelTypes: Story = {
  name: "Label Types",
  render: () => <Showcase.BottomNavigationLabelTypes />,
};

export const BottomNavigationTwoLineLongLabels: Story = {
  name: "Two Line Long Labels",
  render: () => <Showcase.BottomNavigationTwoLineLongLabels />,
};

export const BottomNavigationIconOnlyAccessibility: Story = {
  name: "Icon Only Accessibility",
  render: () => <Showcase.BottomNavigationIconOnlyAccessibility />,
};

export const BottomNavigationItemCounts: Story = {
  name: "Item Counts",
  render: () => <Showcase.BottomNavigationItemCounts />,
};

export const BottomNavigationMaxItemsEnforced: Story = {
  name: "Max Items Enforced",
  render: () => <Showcase.BottomNavigationMaxItemsEnforced />,
};

export const BottomNavigationStates: Story = {
  name: "States",
  render: () => <Showcase.BottomNavigationStates />,
};

export const BottomNavigationControlled: Story = {
  name: "Controlled",
  render: () => <Showcase.BottomNavigationControlled />,
};

export const BottomNavigationSelectionExclusivity: Story = {
  name: "Selection Exclusivity",
  render: () => <Showcase.BottomNavigationSelectionExclusivity />,
};

export const BottomNavigationSurfaceModes: Story = {
  name: "Surface Modes",
  render: () => <Showcase.BottomNavigationSurfaceModes />,
};

export const BottomNavigationAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.BottomNavigationAppearances />,
};
