/**
 * Button.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Button/Button.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Button';

const meta = {
  title: "Components/Actions/Button",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ButtonDefault: Story = {
  name: "Default",
  render: () => <Showcase.ButtonDefault />,
};

export const ButtonAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.ButtonAttentionLevels />,
};

export const ButtonThemes: Story = {
  name: "Themes",
  render: () => <Showcase.ButtonThemes />,
};

export const ButtonSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.ButtonSizes />,
};

export const ButtonCondensed: Story = {
  name: "Condensed",
  render: () => <Showcase.ButtonCondensed />,
};

export const ButtonStates: Story = {
  name: "States",
  render: () => <Showcase.ButtonStates />,
};

export const ButtonWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.ButtonWithSlots />,
};

export const ButtonFullWidth: Story = {
  name: "Full Width",
  render: () => <Showcase.ButtonFullWidth />,
};

export const ButtonResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.ButtonResponsive />,
};

export const ButtonAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.ButtonAppearances />,
};

export const ButtonContained: Story = {
  name: "Contained",
  render: () => <Showcase.ButtonContained />,
};

export const ButtonSlotPadding: Story = {
  name: "Slot Padding",
  render: () => <Showcase.ButtonSlotPadding />,
};

export const ButtonLoadingWithSlots: Story = {
  name: "Loading With Slots",
  render: () => <Showcase.ButtonLoadingWithSlots />,
};

export const ButtonDensity: Story = {
  name: "Density",
  render: () => <Showcase.ButtonDensity />,
};

export const ButtonMotion: Story = {
  name: "Motion",
  render: () => <Showcase.ButtonMotion />,
};

export const ButtonSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.ButtonSurfaceContext />,
};

export const ButtonPlayground: Story = {
  name: "Playground",
  render: () => <Showcase.ButtonPlayground />,
};
