/**
 * Checkbox.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Checkbox/Checkbox.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Checkbox';

const meta = {
  title: "Components/Forms/Checkbox",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const CheckboxDefault: Story = {
  name: "Default",
  render: () => <Showcase.CheckboxDefault />,
};

export const CheckboxSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.CheckboxSizes />,
};

export const CheckboxStates: Story = {
  name: "States",
  render: () => <Showcase.CheckboxStates />,
};

export const CheckboxAccents: Story = {
  name: "Accents",
  render: () => <Showcase.CheckboxAccents />,
};

export const CheckboxAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.CheckboxAppearances />,
};

export const CheckboxReadOnly: Story = {
  name: "Read Only",
  render: () => <Showcase.CheckboxReadOnly />,
};

export const CheckboxWithLabel: Story = {
  name: "With Label",
  render: () => <Showcase.CheckboxWithLabel />,
};

export const CheckboxSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.CheckboxSurfaceContext />,
};

export const CheckboxThemes: Story = {
  name: "Themes",
  render: () => <Showcase.CheckboxThemes />,
};

export const CheckboxInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.CheckboxInteractive />,
};
