/**
 * CheckboxField.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/CheckboxField/CheckboxField.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/CheckboxField';

const meta = {
  title: "Components/Forms/CheckboxField",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const CheckboxFieldDefault: Story = {
  name: "Default",
  render: () => <Showcase.CheckboxFieldDefault />,
};

export const CheckboxFieldSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.CheckboxFieldSizes />,
};

export const CheckboxFieldStates: Story = {
  name: "States",
  render: () => <Showcase.CheckboxFieldStates />,
};

export const CheckboxFieldRequiredAndError: Story = {
  name: "Required And Error",
  render: () => <Showcase.CheckboxFieldRequiredAndError />,
};

export const CheckboxFieldMultiOption: Story = {
  name: "Multi Option",
  render: () => <Showcase.CheckboxFieldMultiOption />,
};

export const CheckboxFieldWithDynamicText: Story = {
  name: "With Dynamic Text",
  render: () => <Showcase.CheckboxFieldWithDynamicText />,
};

export const CheckboxFieldSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.CheckboxFieldSurfaceContext />,
};

export const CheckboxFieldFullWidth: Story = {
  name: "Full Width",
  render: () => <Showcase.CheckboxFieldFullWidth />,
};
