/**
 * ChipGroup.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/ChipGroup/ChipGroup.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/ChipGroup';

const meta = {
  title: "Components/Forms/ChipGroup",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ChipGroupDefaultValueNormalization: Story = {
  name: "Default Value Normalization",
  render: () => <Showcase.ChipGroupDefaultValueNormalization />,
};

export const ChipGroupDefault: Story = {
  name: "Default",
  render: () => <Showcase.ChipGroupDefault />,
};

export const ChipGroupSingleSelect: Story = {
  name: "Single Select",
  render: () => <Showcase.ChipGroupSingleSelect />,
};

export const ChipGroupMultiSelect: Story = {
  name: "Multi Select",
  render: () => <Showcase.ChipGroupMultiSelect />,
};

export const ChipGroupVariants: Story = {
  name: "Variants",
  render: () => <Showcase.ChipGroupVariants />,
};

export const ChipGroupVertical: Story = {
  name: "Vertical",
  render: () => <Showcase.ChipGroupVertical />,
};

export const ChipGroupNoWrap: Story = {
  name: "No Wrap",
  render: () => <Showcase.ChipGroupNoWrap />,
};

export const ChipGroupDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.ChipGroupDisabled />,
};
