/**
 * Chip.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Chip/Chip.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Chip';

const meta = {
  title: "Components/Forms/Chip",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ChipAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.ChipAttentionLevels />,
};

export const ChipSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.ChipSizes />,
};

export const ChipSelectedChange: Story = {
  name: "Selected Change",
  render: () => <Showcase.ChipSelectedChange />,
};

export const ChipStates: Story = {
  name: "States",
  render: () => <Showcase.ChipStates />,
};

export const ChipWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.ChipWithSlots />,
};

export const ChipAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.ChipAppearances />,
};

export const ChipSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.ChipSurfaceContext />,
};

export const ChipSlotPaddingMatrix: Story = {
  name: "Slot Padding Matrix",
  render: () => <Showcase.ChipSlotPaddingMatrix />,
};
