/**
 * CircularProgressIndicator.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/CircularProgressIndicator/CircularProgressIndicator.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/CircularProgressIndicator';

const meta = {
  title: "Components/Status/CircularProgressIndicator",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const CircularProgressIndicatorDefault: Story = {
  name: "Default",
  render: () => <Showcase.CircularProgressIndicatorDefault />,
};

export const CircularProgressIndicatorVariants: Story = {
  name: "Variants",
  render: () => <Showcase.CircularProgressIndicatorVariants />,
};

export const CircularProgressIndicatorSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.CircularProgressIndicatorSizes />,
};

export const CircularProgressIndicatorAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.CircularProgressIndicatorAppearances />,
};

export const CircularProgressIndicatorWithContent: Story = {
  name: "With Content",
  render: () => <Showcase.CircularProgressIndicatorWithContent />,
};

export const CircularProgressIndicatorStates: Story = {
  name: "States",
  render: () => <Showcase.CircularProgressIndicatorStates />,
};

export const CircularProgressIndicatorInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.CircularProgressIndicatorInteractive />,
};

export const CircularProgressIndicatorSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.CircularProgressIndicatorSurfaceContext />,
};

export const CircularProgressIndicatorEntryExit: Story = {
  name: "Entry Exit",
  render: () => <Showcase.CircularProgressIndicatorEntryExit />,
};

export const CircularProgressIndicatorDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.CircularProgressIndicatorDisabled />,
};
