/**
 * Container.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Container/Container.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Container';

const meta = {
  title: "Components/Layout/Container",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ContainerFluid: Story = {
  name: "Fluid",
  render: () => <Showcase.ContainerFluid />,
};

export const ContainerFixed: Story = {
  name: "Fixed",
  render: () => <Showcase.ContainerFixed />,
};

export const ContainerFullBleed: Story = {
  name: "Full Bleed",
  render: () => <Showcase.ContainerFullBleed />,
};

export const ContainerCustomMaxWidth: Story = {
  name: "Custom Max Width",
  render: () => <Showcase.ContainerCustomMaxWidth />,
};

export const ContainerVariants: Story = {
  name: "Variants",
  render: () => <Showcase.ContainerVariants />,
};
