/**
 * CounterBadge.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/CounterBadge/CounterBadge.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/CounterBadge';

const meta = {
  title: "Components/Status/CounterBadge",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const CounterBadgeDefault: Story = {
  name: "Default",
  render: () => <Showcase.CounterBadgeDefault />,
};

export const CounterBadgeVariants: Story = {
  name: "Variants",
  render: () => <Showcase.CounterBadgeVariants />,
};

export const CounterBadgeSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.CounterBadgeSizes />,
};

export const CounterBadgeMaxValue: Story = {
  name: "Max Value",
  render: () => <Showcase.CounterBadgeMaxValue />,
};

export const CounterBadgeAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.CounterBadgeAppearances />,
};

export const CounterBadgeResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.CounterBadgeResponsive />,
};

export const CounterBadgeMotion: Story = {
  name: "Motion",
  render: () => <Showcase.CounterBadgeMotion />,
};

export const CounterBadgeThemes: Story = {
  name: "Themes",
  render: () => <Showcase.CounterBadgeThemes />,
};
