/**
 * Divider.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Divider/Divider.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Divider';

const meta = {
  title: "Components/Layout/Divider",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const DividerDefault: Story = {
  name: "Default",
  render: () => <Showcase.DividerDefault />,
};

export const DividerOrientations: Story = {
  name: "Orientations",
  render: () => <Showcase.DividerOrientations />,
};

export const DividerSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.DividerSizes />,
};

export const DividerAttentions: Story = {
  name: "Attentions",
  render: () => <Showcase.DividerAttentions />,
};

export const DividerAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.DividerAttentionLevels />,
};

export const DividerWithIcon: Story = {
  name: "With Icon",
  render: () => <Showcase.DividerWithIcon />,
};

export const DividerWithLabel: Story = {
  name: "With Label",
  render: () => <Showcase.DividerWithLabel />,
};

export const DividerRoundCaps: Story = {
  name: "Round Caps",
  render: () => <Showcase.DividerRoundCaps />,
};

export const DividerSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.DividerSurfaceContext />,
};

export const DividerVerticalSizes: Story = {
  name: "Vertical Sizes",
  render: () => <Showcase.DividerVerticalSizes />,
};

export const DividerVerticalAttentionLevels: Story = {
  name: "Vertical Attention Levels",
  render: () => <Showcase.DividerVerticalAttentionLevels />,
};

export const DividerVerticalWithIcon: Story = {
  name: "Vertical With Icon",
  render: () => <Showcase.DividerVerticalWithIcon />,
};

export const DividerVerticalWithLabel: Story = {
  name: "Vertical With Label",
  render: () => <Showcase.DividerVerticalWithLabel />,
};

export const DividerVertical: Story = {
  name: "Vertical",
  render: () => <Showcase.DividerVertical />,
};

export const DividerAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.DividerAppearances />,
};
