/**
 * Icon.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Icon/Icon.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Icon';

const meta = {
  title: "Components/Media/Icon",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const IconDefault: Story = {
  name: "Default",
  render: () => <Showcase.IconDefault />,
};

export const IconSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.IconSizes />,
};

export const IconAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.IconAppearances />,
};

export const IconEmphasisLevels: Story = {
  name: "Emphasis Levels",
  render: () => <Showcase.IconEmphasisLevels />,
};

export const IconWithIcons: Story = {
  name: "With Icons",
  render: () => <Showcase.IconWithIcons />,
};

export const IconInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.IconInteractive />,
};

export const IconSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.IconSurfaceContext />,
};

export const IconInContext: Story = {
  name: "In Context",
  render: () => <Showcase.IconInContext />,
};
