/**
 * IconButton.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/IconButton/IconButton.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/IconButton';

const meta = {
  title: "Components/Actions/IconButton",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const IconButtonDefault: Story = {
  name: "Default",
  render: () => <Showcase.IconButtonDefault />,
};

export const IconButtonAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.IconButtonAttentionLevels />,
};

export const IconButtonSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.IconButtonSizes />,
};

export const IconButtonCondensed: Story = {
  name: "Condensed",
  render: () => <Showcase.IconButtonCondensed />,
};

export const IconButtonStates: Story = {
  name: "States",
  render: () => <Showcase.IconButtonStates />,
};

export const IconButtonAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.IconButtonAppearances />,
};

export const IconButtonLayouts: Story = {
  name: "Layouts",
  render: () => <Showcase.IconButtonLayouts />,
};

export const IconButtonFullWidth: Story = {
  name: "Full Width",
  render: () => <Showcase.IconButtonFullWidth />,
};

export const IconButtonWithJdsIcon: Story = {
  name: "With Jds Icon",
  render: () => <Showcase.IconButtonWithJdsIcon />,
};

export const IconButtonSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.IconButtonSurfaceContext />,
};

export const IconButtonLoadingSizes: Story = {
  name: "Loading Sizes",
  render: () => <Showcase.IconButtonLoadingSizes />,
};

export const IconButtonResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.IconButtonResponsive />,
};

export const IconButtonLoadingStates: Story = {
  name: "Loading States",
  render: () => <Showcase.IconButtonLoadingStates />,
};

export const IconButtonMotion: Story = {
  name: "Motion",
  render: () => <Showcase.IconButtonMotion />,
};
