/**
 * IconContained.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/IconContained/IconContained.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/IconContained';

const meta = {
  title: "Components/Actions/IconContained",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const IconContainedDefault: Story = {
  name: "Default",
  render: () => <Showcase.IconContainedDefault />,
};

export const IconContainedAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.IconContainedAttentionLevels />,
};

export const IconContainedSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.IconContainedSizes />,
};

export const IconContainedStates: Story = {
  name: "States",
  render: () => <Showcase.IconContainedStates />,
};

export const IconContainedWithIcons: Story = {
  name: "With Icons",
  render: () => <Showcase.IconContainedWithIcons />,
};

export const IconContainedAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.IconContainedAppearances />,
};

export const IconContainedThemes: Story = {
  name: "Themes",
  render: () => <Showcase.IconContainedThemes />,
};

export const IconContainedSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.IconContainedSurfaceContext />,
};
