/**
 * Image.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Image/Image.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Image';

const meta = {
  title: "Components/Media/Image",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ImageDefault: Story = {
  name: "Default",
  render: () => <Showcase.ImageDefault />,
};

export const ImageAspectRatios: Story = {
  name: "Aspect Ratios",
  render: () => <Showcase.ImageAspectRatios />,
};

export const ImageObjectFitModes: Story = {
  name: "Object Fit Modes",
  render: () => <Showcase.ImageObjectFitModes />,
};

export const ImageStates: Story = {
  name: "States",
  render: () => <Showcase.ImageStates />,
};

export const ImageWithFallback: Story = {
  name: "With Fallback",
  render: () => <Showcase.ImageWithFallback />,
};

export const ImageInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.ImageInteractive />,
};

export const ImageResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.ImageResponsive />,
};

export const ImageCornerRadius: Story = {
  name: "Corner Radius",
  render: () => <Showcase.ImageCornerRadius />,
};

export const ImageGallery: Story = {
  name: "Gallery",
  render: () => <Showcase.ImageGallery />,
};
