/**
 * IndicatorBadge.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/IndicatorBadge/IndicatorBadge.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/IndicatorBadge';

const meta = {
  title: "Components/Status/IndicatorBadge",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const IndicatorBadgeDefault: Story = {
  name: "Default",
  render: () => <Showcase.IndicatorBadgeDefault />,
};

export const IndicatorBadgeSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.IndicatorBadgeSizes />,
};

export const IndicatorBadgeAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.IndicatorBadgeAppearances />,
};

export const IndicatorBadgeSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.IndicatorBadgeSurfaceContext />,
};

export const IndicatorBadgeThemes: Story = {
  name: "Themes",
  render: () => <Showcase.IndicatorBadgeThemes />,
};

export const IndicatorBadgeResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.IndicatorBadgeResponsive />,
};

export const IndicatorBadgeMotion: Story = {
  name: "Motion",
  render: () => <Showcase.IndicatorBadgeMotion />,
};

export const IndicatorBadgeWithComponents: Story = {
  name: "With Components",
  render: () => <Showcase.IndicatorBadgeWithComponents />,
};
