/**
 * InputFeedback.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/InputFeedback/InputFeedback.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/InputFeedback';

const meta = {
  title: "Components/Forms/InputFeedback",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const InputFeedbackDefault: Story = {
  name: "Default",
  render: () => <Showcase.InputFeedbackDefault />,
};

export const InputFeedbackMatrix: Story = {
  name: "Matrix",
  render: () => <Showcase.InputFeedbackMatrix />,
};

export const InputFeedbackVariants: Story = {
  name: "Variants",
  render: () => <Showcase.InputFeedbackVariants />,
};

export const InputFeedbackAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.InputFeedbackAttentionLevels />,
};

export const InputFeedbackSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.InputFeedbackSizes />,
};

export const InputFeedbackSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.InputFeedbackSurfaceContext />,
};

export const InputFeedbackDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.InputFeedbackDisabled />,
};
