/**
 * InputDynamicText.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/InputDynamicText/InputDynamicText.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/InputDynamicText';

const meta = {
  title: "Components/Forms/InputDynamicText",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const InputDynamicTextDefault: Story = {
  name: "Default",
  render: () => <Showcase.InputDynamicTextDefault />,
};

export const InputDynamicTextFigmaSizes: Story = {
  name: "Figma Sizes",
  render: () => <Showcase.InputDynamicTextFigmaSizes />,
};

export const InputDynamicTextSlotCombinations: Story = {
  name: "Slot Combinations",
  render: () => <Showcase.InputDynamicTextSlotCombinations />,
};

export const InputDynamicTextDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.InputDynamicTextDisabled />,
};

export const InputDynamicTextLiveRegion: Story = {
  name: "Live Region",
  render: () => <Showcase.InputDynamicTextLiveRegion />,
};

export const InputDynamicTextOnSurfaceBold: Story = {
  name: "On Surface Bold",
  render: () => <Showcase.InputDynamicTextOnSurfaceBold />,
};

export const InputDynamicTextEmpty: Story = {
  name: "Empty",
  render: () => <Showcase.InputDynamicTextEmpty />,
};
