/**
 * Input.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Input/Input.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Input';

const meta = {
  title: "Components/Forms/Input",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const InputDefault: Story = {
  name: "Default",
  render: () => <Showcase.InputDefault />,
};

export const InputSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.InputSizes />,
};

export const InputAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.InputAttentionLevels />,
};

export const InputAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.InputAppearances />,
};

export const InputShapes: Story = {
  name: "Shapes",
  render: () => <Showcase.InputShapes />,
};

export const InputStates: Story = {
  name: "States",
  render: () => <Showcase.InputStates />,
};

export const InputDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.InputDisabled />,
};

export const InputWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.InputWithSlots />,
};

export const InputControlled: Story = {
  name: "Controlled",
  render: () => <Showcase.InputControlled />,
};

export const InputSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.InputSurfaceContext />,
};

export const InputSearch: Story = {
  name: "Search",
  render: () => <Showcase.InputSearch />,
};
