/**
 * InputField.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/InputField/InputField.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/InputField';

const meta = {
  title: "Components/Forms/InputField",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const InputFieldDefault: Story = {
  name: "Default",
  render: () => <Showcase.InputFieldDefault />,
};

export const InputFieldSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.InputFieldSizes />,
};

export const InputFieldAttentions: Story = {
  name: "Attentions",
  render: () => <Showcase.InputFieldAttentions />,
};

export const InputFieldAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.InputFieldAppearances />,
};

export const InputFieldShapes: Story = {
  name: "Shapes",
  render: () => <Showcase.InputFieldShapes />,
};

export const InputFieldStates: Story = {
  name: "States",
  render: () => <Showcase.InputFieldStates />,
};

export const InputFieldWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.InputFieldWithSlots />,
};

export const InputFieldFullComposition: Story = {
  name: "Full Composition",
  render: () => <Showcase.InputFieldFullComposition />,
};

export const InputFieldControlled: Story = {
  name: "Controlled",
  render: () => <Showcase.InputFieldControlled />,
};

export const InputFieldSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.InputFieldSurfaceContext />,
};

export const InputFieldSearch: Story = {
  name: "Search",
  render: () => <Showcase.InputFieldSearch />,
};
