/**
 * LinkButton.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/LinkButton/LinkButton.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/LinkButton';

const meta = {
  title: "Components/Actions/LinkButton",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const LinkButtonDefault: Story = {
  name: "Default",
  render: () => <Showcase.LinkButtonDefault />,
};

export const LinkButtonAttentionLevels: Story = {
  name: "Attention Levels",
  render: () => <Showcase.LinkButtonAttentionLevels />,
};

export const LinkButtonSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.LinkButtonSizes />,
};

export const LinkButtonStates: Story = {
  name: "States",
  render: () => <Showcase.LinkButtonStates />,
};

export const LinkButtonAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.LinkButtonAppearances />,
};

export const LinkButtonWithSlots: Story = {
  name: "With Slots",
  render: () => <Showcase.LinkButtonWithSlots />,
};

export const LinkButtonResponsive: Story = {
  name: "Responsive",
  render: () => <Showcase.LinkButtonResponsive />,
};

export const LinkButtonSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.LinkButtonSurfaceContext />,
};

export const LinkButtonLoadingStates: Story = {
  name: "Loading States",
  render: () => <Showcase.LinkButtonLoadingStates />,
};
