/**
 * Logo.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Logo/Logo.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Logo';

const meta = {
  title: "Components/Media/Logo",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const LogoSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.LogoSizes />,
};

export const LogoVariants: Story = {
  name: "Variants",
  render: () => <Showcase.LogoVariants />,
};

export const LogoCustomSize: Story = {
  name: "Custom Size",
  render: () => <Showcase.LogoCustomSize />,
};

export const LogoContentSources: Story = {
  name: "Content Sources",
  render: () => <Showcase.LogoContentSources />,
};

export const LogoFromImage: Story = {
  name: "From Image",
  render: () => <Showcase.LogoFromImage />,
};

export const LogoFromChildren: Story = {
  name: "From Children",
  render: () => <Showcase.LogoFromChildren />,
};

export const LogoImageFallback: Story = {
  name: "Image Fallback",
  render: () => <Showcase.LogoImageFallback />,
};

export const LogoDefault: Story = {
  name: "Default",
  render: () => <Showcase.LogoDefault />,
};

export const LogoSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.LogoSurfaceContext />,
};

export const LogoInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.LogoInteractive />,
};

export const LogoThemes: Story = {
  name: "Themes",
  render: () => <Showcase.LogoThemes />,
};
