/**
 * PaginationDots.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/PaginationDots/PaginationDots.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/PaginationDots';

const meta = {
  title: "Components/Navigation/PaginationDots",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const PaginationDotsDefault: Story = {
  name: "Default",
  render: () => <Showcase.PaginationDotsDefault />,
};

export const PaginationDotsBasic: Story = {
  name: "Basic",
  render: () => <Showcase.PaginationDotsBasic />,
};

export const PaginationDotsAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.PaginationDotsAppearances />,
};

export const PaginationDotsLoopVsNonLoop: Story = {
  name: "Loop Vs Non Loop",
  render: () => <Showcase.PaginationDotsLoopVsNonLoop />,
};

export const PaginationDotsLoop: Story = {
  name: "Loop",
  render: () => <Showcase.PaginationDotsLoop />,
};

export const PaginationDotsLongSequence: Story = {
  name: "Long Sequence",
  render: () => <Showcase.PaginationDotsLongSequence />,
};

export const PaginationDotsInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.PaginationDotsInteractive />,
};

export const PaginationDotsReadOnly: Story = {
  name: "Read Only",
  render: () => <Showcase.PaginationDotsReadOnly />,
};

export const PaginationDotsDegenerate: Story = {
  name: "Degenerate",
  render: () => <Showcase.PaginationDotsDegenerate />,
};

export const PaginationDotsShortSequence: Story = {
  name: "Short Sequence",
  render: () => <Showcase.PaginationDotsShortSequence />,
};

export const PaginationDotsSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.PaginationDotsSurfaceContext />,
};
