/**
 * Progress.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Progress/Progress.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Progress';

const meta = {
  title: "Components/Status/Progress",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ProgressDefault: Story = {
  name: "Default",
  render: () => <Showcase.ProgressDefault />,
};

export const ProgressSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.ProgressSizes />,
};

export const ProgressIndeterminate: Story = {
  name: "Indeterminate",
  render: () => <Showcase.ProgressIndeterminate />,
};

export const ProgressBoundaries: Story = {
  name: "Boundaries",
  render: () => <Showcase.ProgressBoundaries />,
};

export const ProgressValueRange: Story = {
  name: "Value Range",
  render: () => <Showcase.ProgressValueRange />,
};

export const ProgressSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.ProgressSurfaceContext />,
};
