/**
 * RadioField.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/RadioField/RadioField.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/RadioField';

const meta = {
  title: "Components/Forms/RadioField",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const RadioFieldDefault: Story = {
  name: "Default",
  render: () => <Showcase.RadioFieldDefault />,
};

export const RadioFieldSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.RadioFieldSizes />,
};

export const RadioFieldStates: Story = {
  name: "States",
  render: () => <Showcase.RadioFieldStates />,
};

export const RadioFieldRequiredAndError: Story = {
  name: "Required And Error",
  render: () => <Showcase.RadioFieldRequiredAndError />,
};

export const RadioFieldIntegratedSingle: Story = {
  name: "Integrated Single",
  render: () => <Showcase.RadioFieldIntegratedSingle />,
};

export const RadioFieldWithDynamicText: Story = {
  name: "With Dynamic Text",
  render: () => <Showcase.RadioFieldWithDynamicText />,
};

export const RadioFieldSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.RadioFieldSurfaceContext />,
};

export const RadioFieldFullWidth: Story = {
  name: "Full Width",
  render: () => <Showcase.RadioFieldFullWidth />,
};
