/**
 * Radio.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Radio/Radio.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Radio';

const meta = {
  title: "Components/Forms/Radio",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const RadioSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.RadioSizes />,
};

export const RadioStates: Story = {
  name: "States",
  render: () => <Showcase.RadioStates />,
};

export const RadioAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.RadioAppearances />,
};

export const RadioReadOnly: Story = {
  name: "Read Only",
  render: () => <Showcase.RadioReadOnly />,
};

export const RadioWithLabel: Story = {
  name: "With Label",
  render: () => <Showcase.RadioWithLabel />,
};

export const RadioSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.RadioSurfaceContext />,
};

export const RadioInteractive: Story = {
  name: "Interactive",
  render: () => <Showcase.RadioInteractive />,
};
