/**
 * Separator.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Separator/Separator.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Separator';

const meta = {
  title: "Components/Layout/Separator",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const SeparatorHorizontal: Story = {
  name: "Horizontal",
  render: () => <Showcase.SeparatorHorizontal />,
};

export const SeparatorVertical: Story = {
  name: "Vertical",
  render: () => <Showcase.SeparatorVertical />,
};
