/**
 * Spinner.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Spinner/Spinner.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Spinner';

const meta = {
  title: "Components/Status/Spinner",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const SpinnerDefault: Story = {
  name: "Default",
  render: () => <Showcase.SpinnerDefault />,
};

export const SpinnerSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.SpinnerSizes />,
};

export const SpinnerSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.SpinnerSurfaceContext />,
};

export const SpinnerMotion: Story = {
  name: "Motion",
  render: () => <Showcase.SpinnerMotion />,
};
