/**
 * Switch.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Switch/Switch.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Switch';

const meta = {
  title: "Components/Other/Switch",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const SwitchDefault: Story = {
  name: "Default",
  render: () => <Showcase.SwitchDefault />,
};

export const SwitchSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.SwitchSizes />,
};

export const SwitchStates: Story = {
  name: "States",
  render: () => <Showcase.SwitchStates />,
};

export const SwitchAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.SwitchAppearances />,
};

export const SwitchAccents: Story = {
  name: "Accents",
  render: () => <Showcase.SwitchAccents />,
};

export const SwitchReadOnly: Story = {
  name: "Read Only",
  render: () => <Showcase.SwitchReadOnly />,
};

export const SwitchWithLabel: Story = {
  name: "With Label",
  render: () => <Showcase.SwitchWithLabel />,
};

export const SwitchSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.SwitchSurfaceContext />,
};

export const SwitchControlled: Story = {
  name: "Controlled",
  render: () => <Showcase.SwitchControlled />,
};

export const SwitchThemes: Story = {
  name: "Themes",
  render: () => <Showcase.SwitchThemes />,
};
