/**
 * Text.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Text/Text.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Text';

const meta = {
  title: "Components/Layout/Text",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const TextDefault: Story = {
  name: "Default",
  render: () => <Showcase.TextDefault />,
};

export const TextVariants: Story = {
  name: "Variants",
  render: () => <Showcase.TextVariants />,
};

export const TextSizes: Story = {
  name: "Sizes",
  render: () => <Showcase.TextSizes />,
};

export const TextAttentionAndWeight: Story = {
  name: "Attention And Weight",
  render: () => <Showcase.TextAttentionAndWeight />,
};

export const TextAppearances: Story = {
  name: "Appearances",
  render: () => <Showcase.TextAppearances />,
};

export const TextDecorations: Story = {
  name: "Decorations",
  render: () => <Showcase.TextDecorations />,
};

export const TextSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.TextSurfaceContext />,
};

export const TextTruncation: Story = {
  name: "Truncation",
  render: () => <Showcase.TextTruncation />,
};

export const TextAlignment: Story = {
  name: "Alignment",
  render: () => <Showcase.TextAlignment />,
};

export const TextLink: Story = {
  name: "Link",
  render: () => <Showcase.TextLink />,
};

export const TextTruncationAlignmentAndLink: Story = {
  name: "Truncation Alignment And Link",
  render: () => <Showcase.TextTruncationAlignmentAndLink />,
};

export const TextDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.TextDisabled />,
};
