/**
 * Tooltip.stories.tsx — GENERATED by scripts/generate-stories.mjs.
 * Source of truth: packages/ui-native/src/components/Tooltip/Tooltip.showcase.native.tsx
 * Do not edit by hand; run `pnpm generate:stories` to refresh.
 */
import type { Meta, StoryObj } from '@storybook/react-native';
import * as Showcase from '@oneui/ui-native/showcase/Tooltip';

const meta = {
  title: "Components/Other/Tooltip",
} satisfies Meta<unknown>;

export default meta;
type Story = StoryObj<typeof meta>;

export const TooltipDefault: Story = {
  name: "Default",
  render: () => <Showcase.TooltipDefault />,
};

export const TooltipPositions: Story = {
  name: "Positions",
  render: () => <Showcase.TooltipPositions />,
};

export const TooltipArrow: Story = {
  name: "Arrow",
  render: () => <Showcase.TooltipArrow />,
};

export const TooltipTriggerModes: Story = {
  name: "Trigger Modes",
  render: () => <Showcase.TooltipTriggerModes />,
};

export const TooltipDelay: Story = {
  name: "Delay",
  render: () => <Showcase.TooltipDelay />,
};

export const TooltipDisabled: Story = {
  name: "Disabled",
  render: () => <Showcase.TooltipDisabled />,
};

export const TooltipControlled: Story = {
  name: "Controlled",
  render: () => <Showcase.TooltipControlled />,
};

export const TooltipMaxWidth: Story = {
  name: "Max Width",
  render: () => <Showcase.TooltipMaxWidth />,
};

export const TooltipMotion: Story = {
  name: "Motion",
  render: () => <Showcase.TooltipMotion />,
};

export const TooltipLongContent: Story = {
  name: "Long Content",
  render: () => <Showcase.TooltipLongContent />,
};

export const TooltipPortal: Story = {
  name: "Portal",
  render: () => <Showcase.TooltipPortal />,
};

export const TooltipInsideBoldSurface: Story = {
  name: "Inside Bold Surface",
  render: () => <Showcase.TooltipInsideBoldSurface />,
};

export const TooltipInsideSubtleSurface: Story = {
  name: "Inside Subtle Surface",
  render: () => <Showcase.TooltipInsideSubtleSurface />,
};

export const TooltipSurfaceContext: Story = {
  name: "Surface Context",
  render: () => <Showcase.TooltipSurfaceContext />,
};
