/**
 * OneUI components wrapped with ComponentInspector for QA validation.
 * Monorepo adapter — imports from `@oneui/ui` instead of published `@jds4/oneui-react`.
 */
import { BrandProvider as RawBrandProvider } from '@oneui/ui/components/BrandProvider';
import { Surface as RawSurface } from '@oneui/ui/components/Surface';
import { IndicatorBadge as RawIndicatorBadge } from '@oneui/ui/components/IndicatorBadge';
import { Logo as RawLogo } from '@oneui/ui/components/Logo';
import { Avatar as RawAvatar } from '@oneui/ui/components/Avatar';
import { Badge as RawBadge } from '@oneui/ui/components/Badge';
import { BottomNavItem as RawBottomNavItem, BottomNavigation as RawBottomNavigation } from '@oneui/ui/components/BottomNavigation';
import { Button as RawButton } from '@oneui/ui/components/Button';
import { Checkbox as RawCheckbox } from '@oneui/ui/components/Checkbox';
import { CheckboxField as RawCheckboxField } from '@oneui/ui/components/CheckboxField';
import { Chip as RawChip } from '@oneui/ui/components/Chip';
import { ChipGroup as RawChipGroup } from '@oneui/ui/components/ChipGroup';
import { CircularProgressIndicator as RawCircularProgressIndicator } from '@oneui/ui/components/CircularProgressIndicator';
import { Container as RawContainer } from '@oneui/ui/components/Container';
import { CounterBadge as RawCounterBadge } from '@oneui/ui/components/CounterBadge';
import { Divider as RawDivider } from '@oneui/ui/components/Divider';
import { Icon as RawIcon } from '@oneui/ui/components/Icon';
import { IconButton as RawIconButton } from '@oneui/ui/components/IconButton';
import { IconContained as RawIconContained } from '@oneui/ui/components/IconContained';
import { Image as RawImage } from '@oneui/ui/components/Image';
import { Input as RawInput, InputDynamicText as RawInputDynamicText, InputFeedback as RawInputFeedback } from '@oneui/ui/components/Input';
import { InputField as RawInputField } from '@oneui/ui/components/InputField';
import { Modal as RawModal } from '@oneui/ui/components/Modal';
import { Pagination as RawPagination } from '@oneui/ui/components/Pagination';
import { PaginationDots as RawPaginationDots } from '@oneui/ui/components/PaginationDots';
import { Radio as RawRadio, RadioGroup as RawRadioGroup } from '@oneui/ui/components/Radio';
import { RadioField as RawRadioField } from '@oneui/ui/components/RadioField';
import { SelectableButton as RawSelectableButton } from '@oneui/ui/components/SelectableButton';
import { SelectableIconButton as RawSelectableIconButton } from '@oneui/ui/components/SelectableIconButton';
import { SelectableSingleTextButton as RawSelectableSingleTextButton } from '@oneui/ui/components/SelectableSingleTextButton';
import { SingleTextButton as RawSingleTextButton } from '@oneui/ui/components/SingleTextButton';
import { Slider as RawSlider } from '@oneui/ui/components/Slider';
import { Stepper as RawStepper } from '@oneui/ui/components/Stepper';
import { Switch as RawSwitch } from '@oneui/ui/components/Switch';
import { TouchSlider as RawTouchSlider } from '@oneui/ui/components/TouchSlider';
import { TabGroup as RawTabGroup, TabItem as RawTabItem, TabPanel as RawTabPanel } from '@oneui/ui/components/Tabs';
import { Text as RawText } from '@oneui/ui/components/Text';
import { TooltipProvider as RawTooltipProvider } from '@oneui/ui/components/Tooltip';

import { AdaptiveTooltip } from '@/sample-app/components/AdaptiveTooltip';
import { withComponentInfo } from './withComponentInfo';

export { RawBrandProvider as BrandProvider };
export { RawTooltipProvider as TooltipProvider };

export const Surface = withComponentInfo(RawSurface, 'Surface') as typeof RawSurface;
export const Avatar = withComponentInfo(RawAvatar, 'Avatar') as typeof RawAvatar;
export const Badge = withComponentInfo(RawBadge, 'Badge') as typeof RawBadge;
export const BottomNavigation = withComponentInfo(RawBottomNavigation, 'BottomNavigation') as typeof RawBottomNavigation;
export const BottomNavItem = withComponentInfo(RawBottomNavItem, 'BottomNavItem') as typeof RawBottomNavItem;
export const Button = withComponentInfo(RawButton, 'Button') as typeof RawButton;
export const Checkbox = withComponentInfo(RawCheckbox, 'Checkbox') as typeof RawCheckbox;
export const CheckboxField = withComponentInfo(RawCheckboxField, 'CheckboxField') as typeof RawCheckboxField;
export const Chip = withComponentInfo(RawChip, 'Chip') as typeof RawChip;
export const ChipGroup = withComponentInfo(RawChipGroup, 'ChipGroup') as typeof RawChipGroup;
export const CircularProgressIndicator = withComponentInfo(RawCircularProgressIndicator, 'CircularProgressIndicator') as typeof RawCircularProgressIndicator;
export const Container = withComponentInfo(RawContainer, 'Container') as typeof RawContainer;
export const CounterBadge = withComponentInfo(RawCounterBadge, 'CounterBadge') as typeof RawCounterBadge;
export const Divider = withComponentInfo(RawDivider, 'Divider') as typeof RawDivider;
export const Icon = withComponentInfo(RawIcon, 'Icon') as typeof RawIcon;
export const IconButton = withComponentInfo(RawIconButton, 'IconButton') as typeof RawIconButton;
export const IconContained = withComponentInfo(RawIconContained, 'IconContained') as typeof RawIconContained;
export const Image = withComponentInfo(RawImage, 'Image') as typeof RawImage;
export const IndicatorBadge = withComponentInfo(RawIndicatorBadge, 'IndicatorBadge') as typeof RawIndicatorBadge;
export const Input = withComponentInfo(RawInput, 'Input') as typeof RawInput;
export const InputDynamicText = withComponentInfo(RawInputDynamicText, 'InputDynamicText') as typeof RawInputDynamicText;
export const InputFeedback = withComponentInfo(RawInputFeedback, 'InputFeedback') as typeof RawInputFeedback;
export const InputField = withComponentInfo(RawInputField, 'InputField') as typeof RawInputField;
export const Logo = withComponentInfo(RawLogo, 'Logo') as typeof RawLogo;
export const Modal = withComponentInfo(RawModal, 'Modal') as typeof RawModal;
export const Pagination = withComponentInfo(RawPagination, 'Pagination') as typeof RawPagination;
export const PaginationDots = withComponentInfo(RawPaginationDots, 'PaginationDots') as typeof RawPaginationDots;
export const Radio = withComponentInfo(RawRadio, 'Radio') as typeof RawRadio;
export const RadioGroup = withComponentInfo(RawRadioGroup, 'RadioGroup') as typeof RawRadioGroup;
export const RadioField = withComponentInfo(RawRadioField, 'RadioField') as typeof RawRadioField;
export const SelectableButton = withComponentInfo(RawSelectableButton, 'SelectableButton') as typeof RawSelectableButton;
export const SelectableIconButton = withComponentInfo(RawSelectableIconButton, 'SelectableIconButton') as typeof RawSelectableIconButton;
export const SelectableSingleTextButton = withComponentInfo(RawSelectableSingleTextButton, 'SelectableSingleTextButton') as typeof RawSelectableSingleTextButton;
export const SingleTextButton = withComponentInfo(RawSingleTextButton, 'SingleTextButton') as typeof RawSingleTextButton;
export const Slider = withComponentInfo(RawSlider, 'Slider') as typeof RawSlider;
export const Stepper = withComponentInfo(RawStepper, 'Stepper') as typeof RawStepper;
export const Switch = withComponentInfo(RawSwitch, 'Switch') as typeof RawSwitch;
export const TouchSlider = withComponentInfo(RawTouchSlider, 'TouchSlider') as typeof RawTouchSlider;
export const TabGroup = withComponentInfo(RawTabGroup, 'TabGroup') as typeof RawTabGroup;
export const Tabs = TabGroup;
export const TabItem = withComponentInfo(RawTabItem, 'TabItem') as typeof RawTabItem;
export const TabPanel = withComponentInfo(RawTabPanel, 'TabPanel') as typeof RawTabPanel;
export const Text = withComponentInfo(RawText, 'Text') as typeof RawText;
export const Tooltip = withComponentInfo(AdaptiveTooltip, 'Tooltip') as typeof AdaptiveTooltip;
