import 'package:flutter/material.dart';
import 'package:ui_flutter/storybook.dart';

import '../widgets/qa_story_canvas.dart';
import 'qa_scenario_categories.dart';

class QaScenarioBand {
  const QaScenarioBand({
    required this.category,
    required this.title,
    required this.subtitle,
    required this.child,
  });

  final QaScenarioCategory category;
  final String title;
  final String subtitle;
  final Widget child;
}

QaScenarioBand _band(
  QaScenarioCategory category, {
  required String title,
  required String subtitle,
  required Widget child,
}) =>
    QaScenarioBand(category: category, title: title, subtitle: subtitle, child: child);

List<QaScenarioBand> qaScenariosForSlug(String slug) {
  switch (slug) {
    case 'checkbox':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Checkbox.stories Default — size, appearance, state props',
            child: QaStoryCanvas(child: const CheckboxDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L × unchecked, checked, indeterminate',
            child: CheckboxFoundationsPage(story: CheckboxFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'States',
            subtitle: 'Unchecked, checked, indeterminate, disabled, read-only',
            child: CheckboxFoundationsPage(story: CheckboxFoundationStory.states)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent appearance roles on the brand',
            child: CheckboxFoundationsPage(story: CheckboxFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Checked on secondary Surface modes',
            child: CheckboxFoundationsPage(story: CheckboxFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Read-only',
            subtitle: 'Read-only blocks toggle while preserving checked state',
            child: CheckboxFoundationsPage(story: CheckboxFoundationStory.readOnly)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Single checkbox — tap to toggle',
            child: QaStoryCanvas(minHeight: 200, child: const CheckboxInteractiveStoryPage())),
      ];
    case 'checkbox-field':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'CheckboxField.stories Default — label, description, required',
            child: QaStoryCanvas(child: const CheckboxFieldDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Field size tokens S / M / L',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.sizes)),
        _band(QaScenarioCategory.realWorld,
            title: 'Multi options',
            subtitle: 'Checkbox group with field label and description',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.multiOptions)),
        _band(QaScenarioCategory.realWorld,
            title: 'With dynamic text',
            subtitle: 'Character count row and helper button',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.withDynamicText)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Field on tinted surfaces',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Disabled, invalid, required, feedback-only',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Invalid feedback',
            subtitle: 'Error string and validation semantics',
            child: CheckboxFieldFoundationsPage(story: CheckboxFieldFoundationStory.invalid)),
      ];
    case 'input':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Input.stories Default — size, appearance, attention',
            child: QaStoryCanvas(child: const InputDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Height and padding tokens',
            child: InputFoundationsPage(story: InputFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role fills',
            child: InputFoundationsPage(story: InputFoundationStory.appearances)),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'High / medium / low input fills',
            child: InputFoundationsPage(story: InputFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.realWorld,
            title: 'Full composition',
            subtitle: 'Label, slots, helper, and feedback together',
            child: InputFoundationsPage(story: InputFoundationStory.fullComposition)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Input on nested surfaces',
            child: InputFoundationsPage(story: InputFoundationStory.inputSurfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Disabled, read-only, invalid',
            child: InputFoundationsPage(story: InputFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Controlled',
            subtitle: 'Controlled value and onChange',
            child: InputFoundationsPage(story: InputFoundationStory.controlled)),
      ];
    case 'input-field':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'InputField.stories Default',
            child: QaStoryCanvas(child: const InputFieldDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Field + input size matrix',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based field fills',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Full composition',
            subtitle: 'Label, feedback, dynamic text, and slots',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.fullComposition)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Field on nested surfaces',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Invalid, disabled, and read-only field',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Controlled',
            subtitle: 'Controlled value and onChange',
            child: InputFieldFoundationsPage(story: InputFieldFoundationStory.controlled)),
      ];
    case 'input-dynamic-text':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Character count and helper text',
            child: QaStoryCanvas(child: const InputDynamicTextDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Figma sizes',
            subtitle: 'S / M / L dynamic text rows',
            child: InputDynamicTextFoundationsPage(story: InputDynamicTextFoundationStory.figmaSizes)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Dynamic text on tinted surfaces',
            child: InputDynamicTextFoundationsPage(story: InputDynamicTextFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Live region',
            subtitle: 'Polite live-region updates for count changes',
            child: InputDynamicTextFoundationsPage(story: InputDynamicTextFoundationStory.liveRegion)),
      ];
    case 'input-feedback':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Helper and error feedback rows',
            child: QaStoryCanvas(child: const InputFeedbackDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Variants and attention',
            subtitle: 'Alert vs status variants × attention levels',
            child: InputFeedbackFoundationsPage(story: InputFeedbackFoundationStory.variantsAndAttention)),
        _band(QaScenarioCategory.api,
            title: 'Roles',
            subtitle: 'Positive, negative, warning, informative appearances',
            child: InputFeedbackFoundationsPage(story: InputFeedbackFoundationStory.roles)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Feedback on nested surfaces',
            child: InputFeedbackFoundationsPage(story: InputFeedbackFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Custom icon',
            subtitle: 'Feedback with custom start icon slot',
            child: InputFeedbackFoundationsPage(story: InputFeedbackFoundationStory.customIcon)),
      ];
    case 'radio':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Radio.stories Default',
            child: QaStoryCanvas(child: const RadioDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L radio dots',
            child: RadioFoundationsPage(story: RadioFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent roles',
            child: RadioFoundationsPage(story: RadioFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Radio on tinted surfaces',
            child: RadioFoundationsPage(story: RadioFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Checked, disabled, read-only',
            child: RadioFoundationsPage(story: RadioFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Single-select within group',
            child: QaStoryCanvas(child: const RadioInteractiveStoryPage())),
      ];
    case 'slider':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Slider.stories Default — value, step, appearance',
            child: QaStoryCanvas(child: const SliderDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent appearance roles',
            child: SliderFoundationsPage(story: SliderFoundationStory.appearances)),
        _band(QaScenarioCategory.api,
            title: 'States',
            subtitle: 'Default, disabled, and read-only',
            child: SliderFoundationsPage(story: SliderFoundationStory.states)),
        _band(QaScenarioCategory.api,
            title: 'Types',
            subtitle: 'Continuous single-thumb vs range dual-thumb',
            child: SliderFoundationsPage(story: SliderFoundationStory.types)),
        _band(QaScenarioCategory.api,
            title: 'Knob styles',
            subtitle: 'Outside vs inside knob styles',
            child: SliderFoundationsPage(story: SliderFoundationStory.knobStyles)),
        _band(QaScenarioCategory.realWorld,
            title: 'With steps',
            subtitle: 'Snapping vs free drag with visible step ticks',
            child: SliderFoundationsPage(story: SliderFoundationStory.withSteps)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Secondary appearance on Surface modes',
            child: SliderFoundationsPage(story: SliderFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Single slider — drag to change value',
            child: QaStoryCanvas(
                minHeight: 200, child: const SliderInteractiveStoryPage())),
      ];
    case 'touch-slider':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'TouchSlider.stories Default — progress style, appearance',
            child: QaStoryCanvas(child: const TouchSliderDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Progress styles',
            subtitle: 'Rounded vs sharp fill caps',
            child: TouchSliderFoundationsPage(
                story: TouchSliderFoundationStory.progressStyles)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent appearance roles',
            child: TouchSliderFoundationsPage(
                story: TouchSliderFoundationStory.appearances)),
        _band(QaScenarioCategory.api,
            title: 'States',
            subtitle: 'Default, disabled, and read-only',
            child: TouchSliderFoundationsPage(story: TouchSliderFoundationStory.states)),
        _band(QaScenarioCategory.realWorld,
            title: 'With slots',
            subtitle: 'Start icon slot composition',
            child: TouchSliderFoundationsPage(
                story: TouchSliderFoundationStory.withSlots)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Matched and mismatched surface appearances',
            child: TouchSliderFoundationsPage(
                story: TouchSliderFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Single touch slider — drag to change value',
            child: QaStoryCanvas(
                minHeight: 200,
                child: const TouchSliderInteractiveStoryPage())),
      ];
    case 'radio-field':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'RadioField.stories Default',
            child: QaStoryCanvas(child: const RadioFieldDefaultStoryPage())),
        _band(QaScenarioCategory.realWorld,
            title: 'With description',
            subtitle: 'Label + description layout',
            child: RadioFieldFoundationsPage(story: RadioFieldFoundationStory.multiOptionsWithDescription)),
        _band(QaScenarioCategory.realWorld,
            title: 'With feedback',
            subtitle: 'Field-level validation feedback',
            child: RadioFieldFoundationsPage(story: RadioFieldFoundationStory.withFeedback)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Disabled',
            subtitle: 'Disabled field blocks selection',
            child: RadioFieldFoundationsPage(story: RadioFieldFoundationStory.disabled)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Required',
            subtitle: 'Required asterisk on field label',
            child: RadioFieldFoundationsPage(story: RadioFieldFoundationStory.required)),
        _band(QaScenarioCategory.interaction,
            title: 'Multi options',
            subtitle: 'Radio group selection within field',
            child: RadioFieldFoundationsPage(story: RadioFieldFoundationStory.multiOptions)),
      ];
    case 'badge':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Badge.stories Default — attention, size',
            child: QaStoryCanvas(child: const BadgeDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'XS through XL height tokens',
            child: BadgeFoundationsPage(story: BadgeFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role fills',
            child: BadgeFoundationsPage(story: BadgeFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'With slots',
            subtitle: 'Start/end icon and badge slots',
            child: BadgeFoundationsPage(story: BadgeFoundationStory.withSlots)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Badge on bold and subtle surfaces',
            child: BadgeFoundationsPage(story: BadgeFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Slot adaptation',
            subtitle: 'Slot auto-sizing per badge size',
            child: BadgeFoundationsPage(story: BadgeFoundationStory.slotAdaptation)),
      ];
    case 'counter-badge':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'CounterBadge.stories Default',
            child: QaStoryCanvas(child: const CounterBadgeDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'XS / S / M count pills',
            child: CounterBadgeFoundationsPage(story: CounterBadgeFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based fill colours',
            child: CounterBadgeFoundationsPage(story: CounterBadgeFoundationStory.appearances)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Max value',
            subtitle: 'Value capped at max (e.g. 99+)',
            child: CounterBadgeFoundationsPage(story: CounterBadgeFoundationStory.maxValue)),
      ];
    case 'indicator-badge':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'IndicatorBadge.stories Default',
            child: QaStoryCanvas(child: const IndicatorBadgeDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L dot diameters',
            child: IndicatorBadgeFoundationsPage(story: IndicatorBadgeFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Positive, negative, informative dots',
            child: IndicatorBadgeFoundationsPage(story: IndicatorBadgeFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'With components',
            subtitle: 'Dot overlaid on avatar and icon button',
            child: IndicatorBadgeFoundationsPage(story: IndicatorBadgeFoundationStory.withComponents)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Indicator on tinted surfaces',
            child: IndicatorBadgeFoundationsPage(story: IndicatorBadgeFoundationStory.surfaceContext)),
      ];
    case 'avatar':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Avatar.stories Default',
            child: QaStoryCanvas(child: const AvatarDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: '2XS through 2XL diameters',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Variants',
            subtitle: 'Image, initials, icon fallbacks',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.variants)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role fills',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Avatar on tinted surfaces',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Image fallback',
            subtitle: 'Broken URL → default icon / custom fallback',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.imageFallback)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Enabled and disabled',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Pressable avatar with onPress',
            child: AvatarFoundationsPage(story: AvatarFoundationStory.interactive)),
      ];
    case 'text':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Text.stories Default',
            child: QaStoryCanvas(child: const TextDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Variants',
            subtitle: 'Display, headline, title, body, label, code',
            child: TextFoundationsPage(story: TextFoundationStory.variants)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based text colours',
            child: TextFoundationsPage(story: TextFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Typography on nested surfaces',
            child: TextFoundationsPage(story: TextFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Truncation',
            subtitle: 'Ellipsis, alignment, and link decoration',
            child: TextFoundationsPage(story: TextFoundationStory.truncationAlignmentLink)),
      ];
    case 'image':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Image.stories Default',
            child: QaStoryCanvas(child: const ImageDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Aspect ratios',
            subtitle: '1:1, 16:9, and custom ratios',
            child: ImageFoundationsPage(story: ImageFoundationStory.aspectRatios)),
        _band(QaScenarioCategory.api,
            title: 'Object fit',
            subtitle: 'Cover, contain, fill modes',
            child: ImageFoundationsPage(story: ImageFoundationStory.objectFitModes)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Loading and error fallbacks',
            child: ImageFoundationsPage(story: ImageFoundationStory.states)),
        _band(QaScenarioCategory.edgeCases,
            title: 'With fallback',
            subtitle: 'Custom fallback slot on load error',
            child: ImageFoundationsPage(story: ImageFoundationStory.withFallback)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Pressable image with onPress',
            child: ImageFoundationsPage(story: ImageFoundationStory.interactive)),
      ];
    case 'button':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Button.stories Default — attention, size, slots',
            child: QaStoryCanvas(child: const ButtonDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'Bold / subtle / ghost variants',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'XS through L with slot padding',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role fills',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'With slots',
            subtitle: 'Start/end icon and badge slots',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.withSlots)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Buttons nested on bold surfaces',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Disabled and loading',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Live controls — press and loading',
            child: ButtonFoundationsPage(story: ButtonFoundationStory.interactive)),
      ];
    case 'chip':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Chip.stories Default',
            child: QaStoryCanvas(child: const ChipDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'High / medium / low fills',
            child: ChipFoundationsPage(story: ChipFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L chip heights',
            child: ChipFoundationsPage(story: ChipFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent roles',
            child: ChipFoundationsPage(story: ChipFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Chips on bold surfaces',
            child: ChipFoundationsPage(story: ChipFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Selected and disabled',
            child: ChipFoundationsPage(story: ChipFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Live controls — selectable chip toggle',
            // ChipFoundationStory.interactive renders ChipDefaultStoryPage, which
            // uses Expanded and therefore needs a bounded-height parent. Rendering
            // it directly inside the unbounded scenarios scroll view triggers a
            // "RenderFlex children have non-zero flex but incoming height
            // constraints are unbounded" cascade that blanks the whole page, so it
            // must be wrapped in QaStoryCanvas (same as the Default band).
            child: QaStoryCanvas(child: const ChipDefaultStoryPage())),
      ];
    case 'chip-group':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'ChipGroup.stories Default',
            child: QaStoryCanvas(child: const ChipGroupDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Variants',
            subtitle: 'Single vs multi selection modes',
            child: ChipGroupFoundationsPage(story: ChipGroupFoundationStory.variants)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Group size tokens',
            child: ChipGroupFoundationsPage(story: ChipGroupFoundationStory.sizes)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Chip group on tinted surfaces',
            child: ChipGroupFoundationsPage(story: ChipGroupFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Disabled group and chips',
            child: ChipGroupFoundationsPage(story: ChipGroupFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Multi select',
            subtitle: 'Checkbox-style chip group',
            child: ChipGroupFoundationsPage(story: ChipGroupFoundationStory.multiSelect)),
      ];
    case 'icon':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Icon.stories Default',
            child: QaStoryCanvas(child: const IconDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Dimension f-step icon sizes',
            child: IconFoundationsPage(story: IconFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based icon colours',
            child: IconFoundationsPage(story: IconFoundationStory.appearances)),
        _band(QaScenarioCategory.api,
            title: 'Emphasis levels',
            subtitle: 'High / medium / low icon emphasis',
            child: IconFoundationsPage(story: IconFoundationStory.emphasisLevels)),
        _band(QaScenarioCategory.realWorld,
            title: 'In context',
            subtitle: 'Icon beside text and inside buttons',
            child: IconFoundationsPage(story: IconFoundationStory.inContext)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Icon on tinted surfaces',
            child: IconFoundationsPage(story: IconFoundationStory.surfaceContext)),
      ];
    case 'icon-contained':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'IconContained.stories Default',
            child: QaStoryCanvas(child: const IconContainedDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'Bold / subtle / ghost containers',
            child: IconContainedFoundationsPage(story: IconContainedFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Container and icon size matrix',
            child: IconContainedFoundationsPage(story: IconContainedFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role fills',
            child: IconContainedFoundationsPage(story: IconContainedFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Contained icon on tinted surfaces',
            child: IconContainedFoundationsPage(story: IconContainedFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Disabled container',
            child: IconContainedFoundationsPage(story: IconContainedFoundationStory.states)),
      ];
    case 'icon-button':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'IconButton.stories Default',
            child: QaStoryCanvas(child: const IconButtonDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'Bold / subtle / ghost icon buttons',
            child: IconButtonFoundationsPage(story: IconButtonFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Container size matrix',
            child: IconButtonFoundationsPage(story: IconButtonFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent roles',
            child: IconButtonFoundationsPage(story: IconButtonFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Icon buttons on bold surfaces',
            child: IconButtonFoundationsPage(story: IconButtonFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Loading',
            subtitle: 'Spinner replaces icon when loading',
            child: IconButtonFoundationsPage(story: IconButtonFoundationStory.loadingStates)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Press and focus states',
            // IconButtonFoundationStory.interactive renders IconButtonDefaultStoryPage, which
            // uses Expanded and therefore needs a bounded-height parent. Rendering
            // it inside the unbounded scenarios scroll view blanks the whole page
            // (same cascade as chip — wrap in QaStoryCanvas).
            child: QaStoryCanvas(child: const IconButtonDefaultStoryPage())),
      ];
    case 'circular-progress-indicator':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'CPI.stories Default',
            child: QaStoryCanvas(child: const CircularProgressIndicatorDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L ring diameters',
            child: CircularProgressIndicatorFoundationsPage(
                story: CircularProgressIndicatorFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Variants',
            subtitle: 'Indeterminate vs determinate',
            child: CircularProgressIndicatorFoundationsPage(
                story: CircularProgressIndicatorFoundationStory.variants)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based stroke colours',
            child: CircularProgressIndicatorFoundationsPage(
                story: CircularProgressIndicatorFoundationStory.appearances)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Progress ring on tinted surfaces',
            child: CircularProgressIndicatorFoundationsPage(
                story: CircularProgressIndicatorFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'With content',
            subtitle: 'Ring with centred label or icon',
            child: CircularProgressIndicatorFoundationsPage(
                story: CircularProgressIndicatorFoundationStory.withContent)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Determinate value slider',
            child: QaStoryCanvas(child: const CircularProgressIndicatorInteractiveStoryPage())),
      ];
    case 'linear-progress-indicator':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'LPI.stories Default',
            child: QaStoryCanvas(child: const LinearProgressIndicatorDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'S / M / L track heights',
            child: LinearProgressIndicatorFoundationsPage(
                story: LinearProgressIndicatorFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Types',
            subtitle: 'Determinate vs indeterminate',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                LinearProgressIndicatorFoundationsPage(
                    story: LinearProgressIndicatorFoundationStory.determinate),
                const SizedBox(height: 16),
                LinearProgressIndicatorFoundationsPage(
                    story: LinearProgressIndicatorFoundationStory.indeterminate),
              ],
            )),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Role-based indicator colours',
            child: LinearProgressIndicatorFoundationsPage(
                story: LinearProgressIndicatorFoundationStory.appearances)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Caps',
            subtitle: 'Round vs flat end caps',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                LinearProgressIndicatorFoundationsPage(
                    story: LinearProgressIndicatorFoundationStory.roundCaps),
                const SizedBox(height: 16),
                LinearProgressIndicatorFoundationsPage(
                    story: LinearProgressIndicatorFoundationStory.flatCaps),
              ],
            )),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Progress bar on tinted surfaces',
            child: LinearProgressIndicatorFoundationsPage(
                story: LinearProgressIndicatorFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Live value slider + type toggle',
            child: QaStoryCanvas(child: const LinearProgressIndicatorInteractiveStoryPage())),
      ];
    case 'bottom-navigation':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'BottomNavigation.stories Default — items, labelType, appearance',
            child: QaStoryCanvas(child: const BottomNavigationDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Label types',
            subtitle: 'Figma Label: 1line / 2line / none',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.labelTypes)),
        _band(QaScenarioCategory.api,
            title: 'Item counts',
            subtitle: 'Figma Items: 2 / 3 / 4 / 5 — equal-width strip',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.itemCounts)),
        _band(QaScenarioCategory.api,
            title: 'Appearances',
            subtitle: 'Multi-accent role accents (auto → informative)',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.appearances)),
        // Covers BottomNav.Item: active vs inactive icon swap + per-item icons.
        _band(QaScenarioCategory.realWorld,
            title: 'With icons',
            subtitle: 'Active/inactive icon swap per BottomNav.Item',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.withIcons)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Bar docked on tinted / bold surfaces',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.surfaceModes)),
        _band(QaScenarioCategory.realWorld,
            title: 'Responsive',
            subtitle: 'Per-platform sizing across breakpoints',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.responsive)),
        // Covers BottomNav.Item: active / disabled item states.
        _band(QaScenarioCategory.edgeCases,
            title: 'States',
            subtitle: 'Item active, disabled, and divider toggle',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.states)),
        _band(QaScenarioCategory.interaction,
            title: 'Focus state',
            subtitle: 'Informative focus halo on the focused tab',
            child: BottomNavigationFoundationsPage(
                story: BottomNavigationFoundationStory.focusState)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Controlled value + onValueChange tab switching',
            child: QaStoryCanvas(
                minHeight: 200,
                child: const BottomNavigationInteractiveStoryPage())),
      ];
    case 'divider':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle:
                'Divider.stories Default — orientation, size, appearance, attention, roundCaps controls',
            child: QaStoryCanvas(child: const DividerDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Orientations',
            subtitle: 'Figma orientation: horizontal (full-width) / vertical (inline)',
            child: DividerFoundationsPage(story: DividerFoundationStory.orientations)),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'Figma size: S / M / L stroke widths (--Stroke-S/M/L = 0.5/1/1.5px)',
            child: DividerFoundationsPage(story: DividerFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Attention levels',
            subtitle: 'Figma attention: high / medium / low — stroke colour tier',
            child: DividerFoundationsPage(story: DividerFoundationStory.attentionLevels)),
        _band(QaScenarioCategory.api,
            title: 'Round caps',
            subtitle: 'Figma roundCaps: true (default) / false — pill vs square stroke ends',
            child: DividerFoundationsPage(story: DividerFoundationStory.roundCaps)),
        _band(QaScenarioCategory.realWorld,
            title: 'With icon',
            subtitle: 'Figma slot: icon — start / center / end contentAlign',
            child: DividerFoundationsPage(story: DividerFoundationStory.withIcon)),
        _band(QaScenarioCategory.realWorld,
            title: 'With label',
            subtitle: 'Figma slot: label — start / center / end contentAlign',
            child: DividerFoundationsPage(story: DividerFoundationStory.withLabel)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'Neutral stroke remaps to primary inside tinted / bold surfaces',
            child: DividerFoundationsPage(story: DividerFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.realWorld,
            title: 'Vertical inline usage',
            subtitle: 'Breadcrumb-style inline vertical separators',
            child: DividerFoundationsPage(story: DividerFoundationStory.verticalInlineUsage)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Vertical sizes',
            subtitle: 'Vertical S / M / L stroke widths in a bounded-height host',
            child: DividerFoundationsPage(story: DividerFoundationStory.verticalSizes)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Attention with text',
            subtitle: 'Plain-string centre content auto-styled Label XS Medium',
            child: DividerFoundationsPage(story: DividerFoundationStory.attentionLevelsWithText)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle:
                'Separator landmark + live controls (non-interactive — excluded from tab order)',
            child: QaStoryCanvas(
                minHeight: 200, child: const DividerInteractiveStoryPage())),
      ];
    case 'logo':
      return [
        _band(QaScenarioCategory.api,
            title: 'Default',
            subtitle: 'Logo.stories Default — brand mark',
            child: QaStoryCanvas(child: const LogoDefaultStoryPage())),
        _band(QaScenarioCategory.api,
            title: 'Sizes',
            subtitle: 'XS / S / M / L / XL + custom',
            child: LogoFoundationsPage(story: LogoFoundationStory.sizes)),
        _band(QaScenarioCategory.api,
            title: 'Variants',
            subtitle: 'Mark (circular) vs full wordmark',
            child: LogoFoundationsPage(story: LogoFoundationStory.variants)),
        _band(QaScenarioCategory.realWorld,
            title: 'Content sources',
            subtitle: 'children > svgContent > src',
            child: LogoFoundationsPage(story: LogoFoundationStory.contentSources)),
        _band(QaScenarioCategory.realWorld,
            title: 'Surface context',
            subtitle: 'currentColor remap on bold / subtle surfaces',
            child: LogoFoundationsPage(story: LogoFoundationStory.surfaceContext)),
        _band(QaScenarioCategory.edgeCases,
            title: 'Image fallback',
            subtitle: 'Broken src and empty-content fallbacks',
            child: LogoFoundationsPage(story: LogoFoundationStory.imageFallback)),
        _band(QaScenarioCategory.interaction,
            title: 'Interactive',
            subtitle: 'Tappable logo with focus ring (interactive=true)',
            child: QaStoryCanvas(
                minHeight: 200, child: const LogoInteractiveStoryPage())),
      ];
    default:
      return const [];
  }
}

