// Generated by scripts/generate.mjs — do not edit manually.
import type { IconComponent } from './iconProps';

export const categoryLoaders: Record<
  string,
  () => Promise<Record<string, IconComponent>>
> = {
  "00": () => import('./categories/00'),
  "01": () => import('./categories/01'),
  "02": () => import('./categories/02'),
  "03": () => import('./categories/03'),
};
