export { ChatSurface } from './ChatSurface';
export type {
  ChatMessage,
  ChatSurfaceProps,
  ChatSurfaceComposerProps,
  ChatStatus,
  RenderMessagePart,
  UIMessage,
} from './ChatSurface.shared';

export {
  ASTPreviewCard,
  AssetCard,
  CompositionCodePreviewCard,
  ToneGuardCard,
  AgentThinking,
  StreamingText,
  defaultRenderMessagePart,
  PART_COMPOSITION_AST,
  PART_COMPOSITION_CODE,
  PART_COMPOSITION_ERROR,
  PART_COMPOSITION_REFERENCES,
  PART_COMPOSITION_RETRIEVAL_TRACE,
  PART_TONE_GUARD,
  PART_ASSET,
  isCompositionASTPart,
  isCompositionCodePart,
  isCompositionErrorPart,
  isCompositionReferencesPart,
  isCompositionRetrievalTracePart,
  isToneGuardPart,
  isAssetPart,
} from './parts';
export type {
  ASTPreviewCardProps,
  AssetCardProps,
  AgentThinkingProps,
  StreamingTextProps,
  AssetData,
  AssetKind,
  AssetPart,
  ChatSurfaceDataPart,
  CompositionASTData,
  CompositionASTPart,
  CompositionCodeData,
  CompositionCodePart,
  CompositionCodePreviewCardProps,
  CompositionErrorData,
  CompositionErrorPart,
  CompositionReferencesData,
  CompositionReferencesPart,
  CompositionReferenceSummary,
  CompositionRetrievalTraceData,
  CompositionRetrievalTracePart,
  ToneGuardCardProps,
  ToneGuardData,
  ToneGuardPart,
  ToneGuardPhase,
} from './parts';
