import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

const srcRoot = resolve(__dirname, 'src');

function collectIndexEntries(directory: string): Record<string, string> {
  const absoluteDir = resolve(srcRoot, directory);
  if (!existsSync(absoluteDir)) return {};

  return Object.fromEntries(
    readdirSync(absoluteDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const indexPath = resolve(absoluteDir, entry.name, 'index.ts');
        return existsSync(indexPath)
          ? [`${directory}/${entry.name}/index`, indexPath]
          : null;
      })
      .filter((entry): entry is [string, string] => entry !== null),
  );
}

function collectFileEntries(directory: string, extensions = ['.ts', '.tsx']): Record<string, string> {
  const absoluteDir = resolve(srcRoot, directory);
  if (!existsSync(absoluteDir)) return {};

  return Object.fromEntries(
    readdirSync(absoluteDir, { withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => {
        const extension = extensions.find((candidate) => entry.name.endsWith(candidate));
        if (!extension) return null;
        const basename = entry.name.slice(0, -extension.length);
        if (basename.endsWith('.test') || basename.endsWith('.stories')) return null;
        return [`${directory}/${basename}`, resolve(absoluteDir, entry.name)];
      })
      .filter((entry): entry is [string, string] => entry !== null),
  );
}

const entry = {
  index: resolve(srcRoot, 'index.ts'),
  // Released-only barrel (generated by scripts/generate-public-barrel.ts).
  // The publish pipeline points the tarball's root export at this entry.
  'index.public': resolve(srcRoot, 'index.public.ts'),
  'brand-loader': resolve(srcRoot, 'brand-loader.ts'),
  'cdn-bootstrap/jio': resolve(__dirname, 'cdn-bootstrap/jio.ts'),
  'cdn-bootstrap/jio-loader': resolve(__dirname, 'cdn-bootstrap/jio-loader.ts'),
  'engine/index': resolve(srcRoot, 'engine/index.ts'),
  'hooks/index': resolve(srcRoot, 'hooks/index.ts'),
  'icons/index': resolve(srcRoot, 'icons/index.ts'),
  'icons/semanticMappings/index': resolve(srcRoot, 'icons/semanticMappings/index.ts'),
  'runtime/index': resolve(srcRoot, 'runtime/index.ts'),
  ...collectIndexEntries('components'),
  ...collectFileEntries('contexts'),
  ...collectFileEntries('hooks'),
  ...collectFileEntries('icons'),
  ...collectFileEntries('icons/semanticMappings'),
  ...collectFileEntries('registry'),
  ...collectFileEntries('runtime'),
  ...collectFileEntries('utils'),
};

export default defineConfig({
  // Substitute Node-only `process.env` references at build time. The published
  // library runs in browsers; `process` isn't defined there, so any unguarded
  // `process.env.X` access throws ReferenceError. NODE_ENV defaults to
  // "production" so dev-warning checks (`process.env.NODE_ENV !== "production"`)
  // dead-code-eliminate. The other three appear in inlined transitive deps
  // (`@babel/types`, `debug`) and resolve to falsy values that match their
  // own `if (process.env.X) ...` guards. If a future dep references a
  // different `process.env.Y`, add it here.
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
    'process.env.BABEL_TYPES_8_BREAKING': 'false',
    'process.env.DEBUG': '""',
    'process.env.FORCE_COLOR': '""',
    // WIP `<Surface material="transparent">` gate. Baked from the build env:
    // unset on a normal release build → `''` → flag is false → the transparent
    // code path dead-code-eliminates out of the published tarball. Internal
    // builds that want the real behaviour set ONEUI_EXPERIMENTAL_MATERIAL_TRANSPARENT=true.
    'process.env.ONEUI_EXPERIMENTAL_MATERIAL_TRANSPARENT': JSON.stringify(
      process.env.ONEUI_EXPERIMENTAL_MATERIAL_TRANSPARENT ?? '',
    ),
    'import.meta.env.ONEUI_EXPERIMENTAL_MATERIAL_TRANSPARENT': JSON.stringify(
      process.env.ONEUI_EXPERIMENTAL_MATERIAL_TRANSPARENT ?? '',
    ),
  },
  plugins: [
    react(),
    dts({
      insertTypesEntry: true,
      entryRoot: 'src',
      outDir: 'dist',
      include: ['src'],
      exclude: [
        'src/**/*.stories.tsx',
        'src/**/*.test.tsx',
        'src/**/*.spec.tsx',
        'src/**/__tests__/**',
      ],
      rollupTypes: false,
    }),
    {
      name: 'oneui-styles-types',
      generateBundle() {
        this.emitFile({
          type: 'asset',
          fileName: 'styles.d.ts',
          source: 'declare const stylesheet: string;\nexport default stylesheet;\n',
        });
      },
    },
  ],
  css: {
    modules: {
      localsConvention: 'camelCase',
    },
  },
  build: {
    lib: {
      entry,
      name: 'OneUIWeb',
      formats: ['es', 'cjs'],
      fileName: (format, entryName) =>
        `${entryName}.${format === 'es' ? 'mjs' : 'cjs'}`,
    },
    rollupOptions: {
      // @oneui/shared and @oneui/tokens are intentionally NOT externalized:
      // they get inlined into dist/ so consumers install a single @jds4/oneui-react
      // package (no transitive @oneui/* deps in the published tarball). Source
      // imports keep working via pnpm workspace symlinks in dev/Storybook.
      external: (id) =>
        [
          'react',
          'react-dom',
          'react/jsx-runtime',
          '@base-ui/react',
        ].includes(id) ||
        id.startsWith('@base-ui/react/') ||
        id.startsWith('@phosphor-icons/react') ||
        id.startsWith('@remixicon/react') ||
        id.startsWith('@tabler/icons-react') ||
        id.startsWith('embla-carousel') ||
        id.startsWith('hugeicons-react') ||
        id.startsWith('lucide-react') ||
        id.startsWith('use-sync-external-store') ||
        // Lazy icon registration — must stay a runtime import of the peer
        // package (with generated icon chunks), not a bundled ../packages/ stub.
        id === '@oneui/icons-jio/register' ||
        id.startsWith('@oneui/icons-jio/') ||
        id.includes('icons-jio/src/register') ||
        id.includes('icons-jio/dist/register') ||
        // Brand manifest — resolved via package subpath (plugin overrides at consumer build).
        id === '@oneui/ui/brand-loader' ||
        id === '@jds4/oneui-react/brand-loader' ||
        id === '@oneui/ui/cdn-bootstrap/jio' ||
        id === '@jds4/oneui-react/cdn-bootstrap/jio' ||
        id === '@oneui/ui/cdn-bootstrap/jio-loader' ||
        id === '@jds4/oneui-react/cdn-bootstrap/jio-loader' ||
        // Provided by @oneui/vite-plugin at consumer build time.
        id.startsWith('virtual:oneui'),
      output: {
        inlineDynamicImports: false,
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          '@base-ui/react': 'BaseUI',
        },
        preserveModules: true,
        preserveModulesRoot: 'src',
      },
    },
  },
});
