import type { NotionBug } from './types';

const BASE = 'https://www.notion.so/oneui-bugs';

type MockSeed = Omit<NotionBug, 'platforms'>;

function toMockBug(seed: MockSeed): NotionBug {
  const platforms =
    seed.platform && seed.platform !== '—'
      ? seed.platform.split(',').map((p) => p.trim()).filter(Boolean)
      : [];
  return { ...seed, platforms: platforms.length > 0 ? platforms : [seed.platform] };
}

/** Demo dataset when Notion credentials are not configured. */
export const MOCK_NOTION_BUGS: NotionBug[] = [
  toMockBug({
    id: 'mock-1',
    bugId: 'ONEUI-001',
    title: 'Error state field does not expose aria-invalid to screen readers',
    severity: 'Major',
    status: 'New',
    platform: 'React',
    component: 'InputField',
    assignee: 'Priya Sharma',
    reportedBy: 'Swapnil Parab',
    category: 'Accessibility',
    release: 'v4.1',
    createdAt: '2026-05-20T10:00:00.000Z',
    updatedAt: '2026-05-28T14:30:00.000Z',
    notionUrl: `${BASE}/mock-1`,
  }),
  toMockBug({
    id: 'mock-2',
    bugId: 'ONEUI-002',
    title: 'TouchSlider range input missing accessible name',
    severity: 'Critical',
    status: 'In Progress',
    platform: 'React Native',
    component: 'TouchSlider',
    assignee: 'Arjun Mehta',
    reportedBy: 'Prathip Kattekola',
    category: 'Accessibility',
    release: 'v4.1',
    createdAt: '2026-05-18T09:15:00.000Z',
    updatedAt: '2026-05-29T08:00:00.000Z',
    notionUrl: `${BASE}/mock-2`,
  }),
  toMockBug({
    id: 'mock-3',
    bugId: 'ONEUI-003',
    title: 'Modal footer Cancel and Save buttons missing',
    severity: 'Critical',
    status: 'Closed',
    platform: 'React',
    component: 'Modal',
    assignee: 'Sneha Reddy',
    reportedBy: 'Swapnil Parab',
    category: 'Functional',
    release: 'v4.0',
    createdAt: '2026-05-10T11:00:00.000Z',
    updatedAt: '2026-05-25T16:45:00.000Z',
    notionUrl: `${BASE}/mock-3`,
  }),
  toMockBug({
    id: 'mock-4',
    bugId: 'ONEUI-004',
    title: 'Selected tab panel not linked via aria-controls',
    severity: 'Minor',
    status: 'New',
    platform: 'React',
    component: 'Tabs',
    assignee: 'Rahul Verma',
    reportedBy: 'Prathip Kattekola',
    category: 'Accessibility',
    release: 'v4.2',
    createdAt: '2026-05-22T13:20:00.000Z',
    updatedAt: '2026-05-27T10:10:00.000Z',
    notionUrl: `${BASE}/mock-4`,
  }),
  toMockBug({
    id: 'mock-5',
    bugId: 'ONEUI-005',
    title: 'CheckboxField helper text not associated with input',
    severity: 'Major',
    status: 'Ready to Test',
    platform: 'React',
    component: 'CheckboxField',
    assignee: 'Priya Sharma',
    reportedBy: 'Swapnil Parab',
    category: 'Accessibility',
    release: 'v4.1',
    createdAt: '2026-05-05T08:30:00.000Z',
    updatedAt: '2026-05-29T09:00:00.000Z',
    notionUrl: `${BASE}/mock-5`,
  }),
  toMockBug({
    id: 'mock-6',
    bugId: 'ONEUI-006',
    title: 'Pagination current page not announced on change',
    severity: 'Minor',
    status: 'Closed',
    platform: 'React',
    component: 'Pagination',
    assignee: 'Arjun Mehta',
    reportedBy: 'Prathip Kattekola',
    category: 'Accessibility',
    release: 'v4.0',
    createdAt: '2026-04-28T15:00:00.000Z',
    updatedAt: '2026-05-15T12:00:00.000Z',
    notionUrl: `${BASE}/mock-6`,
  }),
  toMockBug({
    id: 'mock-7',
    bugId: 'ONEUI-007',
    title: 'Tooltip not dismissible with Escape key',
    severity: 'Minor',
    status: 'On Hold',
    platform: 'React',
    component: 'Tooltip',
    assignee: 'Sneha Reddy',
    reportedBy: 'Swapnil Parab',
    category: 'Functional',
    release: 'v4.2',
    createdAt: '2026-05-24T07:45:00.000Z',
    updatedAt: '2026-05-26T18:20:00.000Z',
    notionUrl: `${BASE}/mock-7`,
  }),
  toMockBug({
    id: 'mock-8',
    bugId: 'ONEUI-008',
    title: 'RadioField group legend missing when label hidden',
    severity: 'Major',
    status: 'In Progress',
    platform: 'Flutter',
    component: 'RadioField',
    assignee: 'Rahul Verma',
    reportedBy: 'Prathip Kattekola',
    category: 'Accessibility',
    release: 'v4.1',
    createdAt: '2026-05-19T12:00:00.000Z',
    updatedAt: '2026-05-28T11:30:00.000Z',
    notionUrl: `${BASE}/mock-8`,
  }),
  toMockBug({
    id: 'mock-9',
    bugId: 'ONEUI-009',
    title: 'Badge slot icon tokens diverge from Figma library',
    severity: 'Minor',
    status: 'New',
    platform: 'React',
    component: 'Badge',
    assignee: 'Design QA',
    reportedBy: 'Swapnil Parab',
    category: 'Figma mapping',
    release: 'v4.0',
    createdAt: '2026-05-12T09:00:00.000Z',
    updatedAt: '2026-05-20T14:00:00.000Z',
    notionUrl: `${BASE}/mock-9`,
  }),
  toMockBug({
    id: 'mock-10',
    bugId: 'ONEUI-010',
    title: 'Switch thumb contrast fails on bold surface (RN)',
    severity: 'Critical',
    status: 'New',
    platform: 'React Native',
    component: 'Switch',
    assignee: 'Mobile Team',
    reportedBy: 'Prathip Kattekola',
    category: 'Visual',
    release: 'v4.2',
    createdAt: '2026-05-21T16:00:00.000Z',
    updatedAt: '2026-05-29T07:15:00.000Z',
    notionUrl: `${BASE}/mock-10`,
  }),
];
